### ISSUE TITLE
Need to create option to add multiple event schema

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#1005]
The user has added one event schema on all the posts of website. In a particular post, he modified the event schema and added all the information manually. like this: https://prnt.sc/shunyd

So we need to create option for adding event schema multiple times in that post.

Ref:
https://secure.helpscout.net/conversation/1164069450/0/?folderId=3257665

**Comment by Sanjeevsetu** [comment]
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Event",
  "url": "http://www.example.org/events/1",
  "name": "Tai chi Class",
  "description": "A weekly Tai-Chi class",
  "duration": "PT60M",
  "eventSchedule": {
     "@type": "Schedule",
     "startDate": "2017-01-01",
     "endDate": "2017-12-31",
     "repeatFrequency": "P1W",
     "byDay": "http://schema.org/Wednesday",
     "startTime": "19:00",
     "endTime": "20:00",
     "scheduleTimezone": "Europe/London"
  }
}
</script>
