### ISSUE TITLE
If the Microdata option is enabled then the font size gets increases.

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/schema-and-structured-data-for-wp#1007]
Issue is strange and occurs only at users end.
Ref : https://secure.helpscout.net/conversation/1158316472/128225?folderId=3611365

**Comment by Sanjeevsetu** [comment]
This issue was not from this plugin. this was due to their theme handystore. It has broken html in side menu so when we remove itemprop microdata it remove inverted comma and class remains open.  Evidence : https://prnt.sc/sm9ca0.

I have solved the issue at user end
