### ISSUE TITLE
Need to make compatibility with the wp review plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1010]
Need to make compatibility with the wp review plugin.

Use case :

As the aggregate reviews from wp review and video property from the total recipe generator are not rendering in the recipe schema.

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fcomohacersalsa.com%2Fbechamel%2Fbrocoli-con-bechamel%2Famp%2F

https://secure.helpscout.net/conversation/1168030686/130449?folderId=2632030

**Comment by Sanjeevsetu** [comment]
the issue was solved in pro version on recipe schema
