### ISSUE TITLE
Need to make compatibility with bimber theme.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1019]
Case :1 https://secure.helpscout.net/conversation/1170225993/130820?folderId=2770543

Ref link: https://www.dropbox.com/s/qnhheu6xomocun7/bimber-2.zip?dl=0

NOTE: Need to remove unnecessary markup from the theme, which is not valid 

need check with amp by automatic

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
still waiting for user reply

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply.

**Comment by Sanjeevsetu** [comment]
Since User is not replying from long time and we need more data about this. So we are closing this ticket
