### ISSUE TITLE
"Rating Badge" is not displaying perfectly in Mobile versions.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#1021]
Issue URL: https://yuppie.bg/detski-centar-yuppie/
Screenshot: https://prnt.sc/slnqdf

The issue is when we check on mobile. 

Ticket: https://secure.helpscout.net/conversation/1171107016/131045?folderId=3126461

**Comment by Sanjeevsetu** [comment]
The issue is not valid. This is fine with wordpress default theme. User has done some customization and added footer menu so he needs to customize this badge as well.
