### ISSUE TITLE
In Review collection presentation, Design type gallery with slider of carousel is not working when amp  by automatic plugin is activated

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1023]
In Review collection presentation,Desing type gallery with slider of carousel is not woking when amp  by automatic plugin is activated.

Please see the ref video it is clearly shown: https://monosnap.com/file/8eSBO2rPkZw08lFsK806vbeZVf2mHO

https://secure.helpscout.net/conversation/1169273672/130647?folderId=2632030

Issue recreated in an internal system.

**Comment by Sanjeevsetu** [comment]
This issue has already been covered in ticket https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1008.
