### ISSUE TITLE
The duplicate FAQ fields are adding in the schema 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1025]
Ref: https://secure.helpscout.net/conversation/1170199514/130817/
URL: https://devilonwheels.com/solo-trip-to-ladakh/
Screenshot: https://prnt.sc/soleay

Test URL: https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdevilonwheels.com%2Fsolo-trip-to-ladakh%2F

The user is adding the FAQ block using the YOAST FAQ block in the gutenberg editor. The issue is not occurring on the local.

**Comment by Sanjeevsetu** [comment]
The issue is stranger and unable to create on our side. User will do teamviewer session on monday.
8 June  2020

**Comment by Sanjeevsetu** [comment]
This issue has been fixed. It was not due to this plugin.
