### ISSUE TITLE
If the archive option is enabled in the schema setup then the thumbnail images are not showing in the blog page

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1031]
Ref: https://secure.helpscout.net/conversation/1152128326/126353?folderId=2770545

URL: https://www.saveatrain.com/blog/

Screenshot: https://prnt.sc/sqn3k9

**Comment by udiudiudiudi** [comment]
i see this wasn't pushed into 1.9.39
