### ISSUE TITLE
Multisite Maindomain/Subdomain Issue

### ISSUE THREAD

**Issue by tokach** [ahmedkaludi/schema-and-structured-data-for-wp#1032]
Hi, I wrote the review on plugin's directory page but you asked to write here 

So, I have a site. It works, to say, on domain.com
We have also multisite option enabled. We have two subwebsites added. So, to the end we have, let's say:
domain.com
domain.com/one
domain.com/two

domain.com is set as Main Website in terms of wp multisite mode.

When I installed your plugin at /wp-admin/network/plugins.php and activated for the network (for all sites) it appeared only in /one and /two dashboards but wasn't available at domain.com/wp-admin/

I really like your plugin but this issue prevents me of using it.

Thank you. You are free to contact me for more information, I do not know what you may need to solve this.

**Comment by Sanjeevsetu** [comment]
Hi @tokach 

I have done some testing on my localhost and can see plugin appears for main site as well as subsite ( https://prnt.sc/stocwv https://prnt.sc/stoe45 ). Can you help us to debug more on this issue.

**Comment by Sanjeevsetu** [comment]
Hi @tokach. I am still waiting for your reply. If you do not reply, I am going to close the ticket as its not valid one in my case.

**Comment by tokach** [comment]
@Sanjeevsetu 

Thank you for reminding me. 

I've checked again what was wrong, and it is strange, but now it works. Sorry for the inconvenience. I will rate your plugin in WordPress directory properly.

Thanks!
