### ISSUE TITLE
WP Recipe card is not visible in Structured data test for the amp post - Proper parent conditioning

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/schema-and-structured-data-for-wp#1034]
The bug happened because the user had "Structured data for non-amp" unchecked.  

REF:https://secure.helpscout.net/conversation/1159727408/128600?folderId=3528427

DES: WP recipe card is not able to view in the structured data on the amp post with the wp-recipe 
maker.

**Comment by ahmedkaludi** [comment]
Please check this usecase:

1. on Non-amp: WP Recipe make schema should be activated
2. SasWp should be deactivated on Non-AMP
3. AMP should show the schema from Saswp and non-AMP should show the schema from WP Recipe maker.
