### ISSUE TITLE
After excluding article schema for particular Category, it still shows the schema markup

### ISSUE THREAD

**Issue by LaxmiBhavani-98** [ahmedkaludi/schema-and-structured-data-for-wp#1050]
Ref : https://secure.helpscout.net/conversation/1184074105/133949?folderId=3611365

https://monosnap.com/file/oLgYgsIAn9VHpNoaCPevtNwq2XqUnN

**Comment by Sanjeevsetu** [comment]
The issue is not valid. What I see in video. She has cleard the cache after changing placement but she has not refreshed the page to see new result.
