### ISSUE TITLE
Need to provide feature for removing the "Article Body" attribute from NewsArticle schema type

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1051]
Ref: https://secure.helpscout.net/conversation/1189430259/134937?folderId=2770545

**Comment by ahmedkaludi** [comment]
it will be a special advanced section

**Comment by Sanjeevsetu** [comment]
We already have this option. Just need to create a tutorial. Which we are going to create.
