### ISSUE TITLE
all schema types showing in posts, pages

### ISSUE THREAD

**Issue by lonelydrone** [ahmedkaludi/schema-and-structured-data-for-wp#106]
all schema types are showing and populate for any and all posts types. need a way to disable other schema per post. need a drop down to select type on per post/page basis etc.

**Comment by Sanjeevsetu** [comment]
Hi @lonelydrone,

Thanks for the feedback.

Yeah, there shoud be on/off button to display schemas. We have already started working on it. This option will come in our next update. we have already created a ticket for that https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/99 but we will also keep your reference.

regards
Sanjeev

**Comment by Sanjeevsetu** [comment]
Hi @lonelydrone,

Please try our new version 1.0.7. It has option to enable or disable other schema type on posts or pages.

Hope this helps you.
