### ISSUE TITLE
Need to make stars color yellow as default.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#1062]
Need to make stars color yellow as default.

Ref:https://secure.helpscout.net/conversation/1187666820/134588?folderId=3575684

**Comment by ahmedkaludi** [comment]
I guess it should be active stars

**Comment by vladilil** [comment]
It is the default stars in the coment form. They are currently orange: https://prnt.sc/t265hu. The color to change to is "gold" or "#ffd700". Thank you!
