### ISSUE TITLE
JS bug after 1.9.41

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#1067]
1. https://secure.helpscout.net/conversation/1183781178/133882/
2. https://wordpress.org/support/topic/classic-editor-12/#post-12992470
3. https://wordpress.org/support/topic/button-not-working-on-admin-woocommerce-page-after-update/

**Comment by Sanjeevsetu** [comment]
Pushed in v 1.9.41.2
