### ISSUE TITLE
Need to add publishingPrinciples & address field support in publisher 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1068]
Case:1https://secure.helpscout.net/conversation/1188817884/134832?folderId=2770543

Ref:https://www.thesprucepets.com/

**Comment by Sanjeevsetu** [comment]
We already have an organization schema from main schema dropdown where user can add these data. In Knowledge Graph, we do not have a proper example so I am closing this ticket.
