### ISSUE TITLE
Delay time of the Rating badge on posts/pages is not working.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#1071]
Settings screenshot: https://prnt.sc/t1c1pk
Issue: https://prnt.sc/t1c3pt

I have placed a Rating badge on post by using collection id shortcode, The main issue is I have set the delay timing to display the rating on my post but it is displaying when the post is loaded.

Ref Ticket: https://secure.helpscout.net/conversation/1146466478/124920?folderId=3126461#thread-3414757440

**Comment by Sanjeevsetu** [comment]
The issue is not valid one. There was some confusion on the settings so I am closing it.
