### ISSUE TITLE
Need to provide alternative text option for the images

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1076]
Ref: https://secure.helpscout.net/conversation/1200146483/136817?folderId=2770545
Screenshot:
1.  https://prnt.sc/t50nvt
2. https://prnt.sc/t50ld2
3. https://prnt.sc/t50p3w

**Comment by Sanjeevsetu** [comment]
The issue has been fixed in this ticket https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1235
