### ISSUE TITLE
If a post has 2 schema and we disable one, it automatically disables both of those

### ISSUE THREAD

**Issue by aditya-dua** [ahmedkaludi/schema-and-structured-data-for-wp#1077]
If a post has 2 schema and we disable one, it automatically disables both of those

**Comment by Sanjeevsetu** [comment]
Hi @aditya-dua 

We can not see the issue in our end. We just test it again and it is working fine. only one schema is being disabled. Could you please check it again.

**Comment by aditya-dua** [comment]
I have checked and on further analysis i found the below issue:
If we modify the output of any post type it automatically disables the output of JSON.

**Comment by Sanjeevsetu** [comment]
@aditya-dua . It disabled or it just changed the output for that particular post. 

Can you share some screen shots ?

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
Since user is not active related to this ticket. I am going to close this one
