### ISSUE TITLE
 "User ID Missing" issue when fetching the "Capterra" reviews

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1086]
Ref: https://secure.helpscout.net/conversation/1196527966/136288/

The user is getting the "User ID Missing" issue when fetching the "Capterra" reviews. The issue is not occurring in the local.

Screenshot: https://monosnap.com/file/6HDA1WrWZtUNd5OkHPVHUW8BM6iT1o

**Comment by Sanjeevsetu** [comment]
Reviewshake dashbord is not opening so I am not able to work on this ticket currently. I am moving it to next milestone.

**Comment by Sanjeevsetu** [comment]
issue has been fixed on our server
