### ISSUE TITLE
Review counts are decrementing without fetching the reviews

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1087]
Ref: https://secure.helpscout.net/conversation/1205703877/137984?folderId=2770545

At the user's end, the reviews count get decreasing when fetching the HomeAdvisor reviews without fetching the reviews.

**Comment by chioibasu** [comment]
FTP credentials:
FTP Username: friendly@super.friendly.solutions
FTP server: ftp.friendly.solutions
FTP & explicit FTPS port:  21
Pass: zqPEe#.R5g2h

**Comment by Sanjeevsetu** [comment]
Reviewshake dashbord is not opening so I am not able to work on this ticket currently. I am moving it to next milestone.

**Comment by Sanjeevsetu** [comment]
this issue has been fixed on our server files
