### ISSUE TITLE
Need to add compatibility with the Sensei LMS plugin.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#1091]
Need to add compatibility with the Sensei LMS plugin.

Ref:https://secure.helpscout.net/conversation/1207306440/138250?folderId=3575684

**Comment by ahmedkaludi** [comment]
There;s already a request for this: https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1029
