### ISSUE TITLE
Course post is getting blank when poduct shcema is addedd to the ip

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1100]
Ref: https://secure.helpscout.net/conversation/1169273672/130647?folderId=2632030

https://suporte.hebraicosemfronteiras.com.br/courses/curso-de-hebraico-modulo-iniciantes/

**Comment by Sanjeevsetu** [comment]
this one is similar to https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1101. so closing it
