### ISSUE TITLE
Schema Does not appear with condition "Page template"

### ISSUE THREAD

**Issue by Phil9175** [ahmedkaludi/schema-and-structured-data-for-wp#1119]
Impossible to make schema appear with condition "Page template" equal or not equal to.
Works with others conditions except this one.

**Comment by Sanjeevsetu** [comment]
Hi @Phil9175 Thank you for reporting this bug. Its a valid bug and we are fixing it.

**Comment by Phil9175** [comment]
Hi @Sanjeevsetu @ahmedkaludi , is it available? I have installed 1.9.47 version and it seems doesn't work.
