### ISSUE TITLE
Need to add the compatibility for the "Google Reviews For Site" plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1136]
Ref: https://secure.helpscout.net/conversation/1240446097/145236?folderId=1060556

We need to remove the unnecessary schema loading from the plugin.

**Comment by Sanjeevsetu** [comment]
It seems, Issue fixed at user end. Closing this ticket. if issue occurs again, create new ticket.
