### ISSUE TITLE
Need to make compatibility with the wp reviews pro plugin.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#1139]
Need to make compatibility with the wp reviews pro plugin.

Use case :

The user is adding reviews by using the above plugin on his site, he wants to fetch the same reviews in markup & frontend without any issues.

Ref Ticket: https://secure.helpscout.net/conversation/1232872524/143614/#thread-3563611480

**Comment by Sanjeevsetu** [comment]
Waiting for user reply.

**Comment by ahmedkaludi** [comment]
This will be added in Reviews for schema addon
