### ISSUE TITLE
Warning Error: The text tag script type=application/ld+json contains html comments, which is disallowed

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/schema-and-structured-data-for-wp#1140]
Reference: https://wordpress.org/support/topic/script-typeapplication-ldjson-contains-html-comments-4/

**Comment by Sanjeevsetu** [comment]
The issue is no longer exists. Unable to re create on localhost and user has not shared more info on it so I am closing it. If User faces the issue, I will open it again.
