### ISSUE TITLE
Modify Schema button is not working:- (Videopro theme and Cactus Video plugin) are active.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#1153]
https://secure.helpscout.net/conversation/1247769393/147090?folderId=1060554

https://monosnap.com/direct/tur1TW2IqxKCjAWftZaAlkiicX3Y7f
Theme and plugin zip is available, ask me when working on it. (Not attached as it is too big)

**Comment by Sanjeevsetu** [comment]
The issue is due to the theme and it should be fixed in the theme only. Theme has used jquery live function which has been deprecated since jquery v 1.7. Better to contact theme developer
