### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function fifu_amp_url() in /schema-and-structured-data-for-wp/core/3rd-party/aqua_resizer.php:334

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/schema-and-structured-data-for-wp#1155]
https://wordpress.org/support/topic/error-after-upate-5-5/

**Comment by Zabi09** [comment]
Need to add fallback like - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/50ca0eecf97ee96cbc8eacc00a9cadc42546cc2f
