### ISSUE TITLE
The review count getting tripped while fetching Google review

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1158]
Ref: https://secure.helpscout.net/conversation/1252128023/148040?folderId=2770545

When the user is fetching the google review, out of 118 reviews only 86 reviews are fetched and the rest of the reviews are not fetching. Also, the review count getting reduced but the review is not showing in the review list.

**Comment by Sanjeevsetu** [comment]
Still waiting for user. And I think we have fixed in our previous update
