### ISSUE TITLE
Add Menu Property to FoodEstablishment

### ISSUE THREAD

**Issue by rmvgaines** [ahmedkaludi/schema-and-structured-data-for-wp#116]
Google now supports the Schema.org menu property for FoodEstablishment

It looks like Google is using the older "menu" property instead of the newer hasMenu / Menu entity.

Additional information:
https://moz.com/blog/schema-new-restaurant-menu-markup
https://schema.org/FoodEstablishment
https://developers.google.com/search/docs/data-types/local-business

**Comment by Sanjeevsetu** [comment]
Hi @rmvgaines,

Thanks for the valuable feedbacks. We reviewed your request and its good. We are going to add menu property for FoodEstablishment.

If you have any more suggestions please suggest us. We appreciate user input.

Thanks

**Comment by Sanjeevsetu** [comment]
Hi @rmvgaines, 

Sorry for the delay to implement this ticket. We have planned this ticket in our new milestone 1.0.9

**Comment by rmvgaines** [comment]
@Sanjeevsetu Awesome. Thank you.
