### ISSUE TITLE
Need to add integration with multi-currency plugin for woocommerce.

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/schema-and-structured-data-for-wp#1160]
Need to add integration with multi-currency plugin for Woocommerce.

Ref plugin:
https://wordpress.org/plugins/woocommerce-currency-switcher/

https://wordpress.org/plugins/woo-multi-currency/

https://wordpress.org/plugins/wc-multi-currency/

Ref :https://secure.helpscout.net/conversation/1253772758/148379/

**Comment by Sanjeevsetu** [comment]
These has been added to woocommerce-compatibility-for-schema pro extension.
