### ISSUE TITLE
Errors in Google Search Console

### ISSUE THREAD

**Issue by rodrigo-orlandini** [ahmedkaludi/schema-and-structured-data-for-wp#1168]
Good morning, I'm having some issues with Google Search Console.
I have a WordPress application that has its plugin installed, however, I am having some Snnipets Review errors in Search Console, follow the attached errors:
![Capturar](https://user-images.githubusercontent.com/69695209/90894866-a077e400-e397-11ea-8368-ff0f505650d2.PNG)
![Capturar2](https://user-images.githubusercontent.com/69695209/90894872-a241a780-e397-11ea-9960-b8982c2ec61b.PNG)
![Capturar3](https://user-images.githubusercontent.com/69695209/90894878-a372d480-e397-11ea-8253-a17b0343ace2.PNG)

URL with errors: https://lenscope.com.br/blog/especificacao-de-lente-para-miopia/

I've been trying to solve it for days, I checked my settings, I updated my plugin to the latest version, but nothing solved it.
In my plugin settings SchemaType BlogPosting is selected, I saw that this type is no longer supported, however, I have another WordPress application that is with the same Schema Type BlogPosting and does not have errors in Search Console, it works perfectly. How can I fix this?

**Comment by ahmedkaludi** [comment]
@rodrigo-orlandini Github is for tested and re-creatable bugs, for support please go to website and reach out to our technical team
