### ISSUE TITLE
Facebook user profile picture not showing (Reviews for Schema)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1170]
Case 1:https://secure.helpscout.net/conversation/1252463617/148152?folderId=2770543
Case 2:https://secure.helpscout.net/conversation/1261029660/149829?folderId=2770543

Screenshots:
https://prnt.sc/u3ak42
https://monosnap.com/file/j1vgHwRCQL4aOVDVRPlOnl02cIJcfi

**Comment by Sanjeevsetu** [comment]
This issue has been fixed on our server with a fallback
