### ISSUE TITLE
Plugin security - coderisk.com showing security issues.

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/schema-and-structured-data-for-wp#1175]
When testing plugin security in [coderisk.com](https://coderisk.com/)  it is showing  security issues in the plugin.

report url: https://coderisk.com/wp/plugin/schema-and-structured-data-for-wp
ref : https://secure.helpscout.net/conversation/1262579649/150168?folderId=3953286

**Comment by Sanjeevsetu** [comment]
coderisk.com is not exists anymore it has been acquired  SonarSource and the issue I can not see there. If We get the issues again. We will re open this.
