### ISSUE TITLE
Some properties of the modified schema on the product pages are not rendering

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/schema-and-structured-data-for-wp#1176]
Some properties of the modified schema on the product pages are not rendering in the schema markup values such as name, price, SKU, etc.

The schema on this URL is the modified schema of the product:

https://staging.maxtour.co/tours/grand-canyon-west-hoover-dam-seven-magic-mountains-day-tour/

This is the auto-generated schema: https://staging.maxtour.co/tours/2-day-grand-canyon-antelope-canyon-tour/

Ref: https://secure.helpscout.net/conversation/1260981324/149825?folderId=3575684

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
User said "The issue has been solved". So, I am going to close the ticket. If it again comes, I will re open it
