### ISSUE TITLE
The values of custom fields are not getting for job posting schema for the events

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1178]
Ref: https://secure.helpscout.net/conversation/1262104917/150078/

When the user is adding the job posting schema for the events adding from the Event Calendar plugin the values of the custom fields are not getting for the fields like address locality,addressregion are not loading. It is causing the warning issues.

Screenshot:
https://prnt.sc/u650ak
Test URL: https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fjobfairsin.com%2Fevent%2Fdrive-thru-job-fair%2F

I tested the issues on the local as well and the issue is recreating.

Steps to recreate it:
1. Add the event using the Event Calendar Plugin.
2. Add the job posting scheme and target it for the tribe events.
3. Click on the modify schema and add the postal address and other values from here. Screenshot:
https://prnt.sc/u64y78
4.Output: https://prnt.sc/u64xpp

**Comment by Sanjeevsetu** [comment]
The issue is not valid. Actually custom field is the postmeta of that particular post but in this case venueCity is not a post meta of tribe_events post type.
