### ISSUE TITLE
Need to add the support for the Table schema type

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1179]
Ref: https://secure.helpscout.net/conversation/1244939883/146515?folderId=2770545

Ref: https://schema.org/Table

**Comment by akashagrjsr** [comment]
One more user-requested for the Table schema type support
Ref: https://secure.helpscout.net/conversation/1273163899/152563?folderId=2770545

**Comment by amaherjr** [comment]
Hi Ahmed, any progress with this request? It's really an important type for us.

**Comment by JNAzeem** [comment]
Ref: https://secure.helpscout.net/conversation/1284686609/154912?folderId=3953286

**Comment by Sanjeevsetu** [comment]
We are not getting a proper example of  table schema Json-Ld so we keep it on hold. Once We get a a proper example we will work on this ticket.
