### ISSUE TITLE
Need to create a filter that would let a user fetch reviews only above certain ratings.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#1180]
Need to create a filter that would let a user select reviews only above certain ratings.
and also if a review is deleted it should not be fetched again.

Reference: https://secure.helpscout.net/conversation/1261491351/149895?folderId=3514643

**Comment by Sanjeevsetu** [comment]
With the current option panel we are not going to add the filter as our backend service provider does not provide filter with rating. We are closing this ticket till we update our review section.
