### ISSUE TITLE
thumbnailUrl

### ISSUE THREAD

**Issue by AndyRenard** [ahmedkaludi/schema-and-structured-data-for-wp#1191]
Google complains that thumbnailUrl is missing for VideoObject.

Is it a bug or am I doing something wrong?

[Hem och kontor AB](https://hemochkontor.se)

Best regards,
Andy

**Comment by AndyRenard** [comment]
This was amazing!
Today, the day after I reported the bug - there is an update with a fix!

That's what I call support!

Best regards,
Andy

**Comment by ahmedkaludi** [comment]
Thanks, please share your good words as review on Wordpress.org plug-in page
