### ISSUE TITLE
Need to integrate  mariage.net and zankyou.com in the review system

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1196]
Ref: https://secure.helpscout.net/conversation/1266630034/150973?folderId=2632030

Example: https://www.mariages.net/decoration-mariage/rev-&-deco--e170050

https://www.zankyou.fr/f/so-et-ju-799213

Use case: user wants the fetch these reviews which is present on this URL: https://www.mariages.net/decoration-mariage/rev-&-deco--e170050

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/saswp-server/commit/615c348d7659d3328d13ea0087677bffeb16f26d
