### ISSUE TITLE
When video object schema placement is selected as shown on all post, then Video object schema markup should not generate on the post when it doesn't contain a video 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1197]
When video object schema placement is selected as shown on all post then Video object schema markup should not generate on that post particular when the video is not present in that post. 

Use case: To get rid of the warning Either "contentUrl" or "embedUrl" should be specified 

on the post where the video is not present.

Ref: https://monosnap.com/file/xRD02oyKnEFjHiWSLs2QVot8i8JEci

in this use case, we need to check video is present then only video object schema should get generate or else not.

to get rid of this warning in GSC.

https://secure.helpscout.net/conversation/1274874370/152918?folderId=2632030

https://search.google.com/u/1/search-console/videos/drilldown?resource_id=sc-domain%3Asaveatrain.com&item_key=ChgIKBoKY29udGVudFVybBoIZW1iZWRVcmwQAhgU

**Comment by udiudiudiudi** [comment]
HI, any update on this ?
