### ISSUE TITLE
Issue with fetching CLUTCH reviews: Displays message "Something went wrong while preparing database".

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#1198]
1.  Issue1: Problem with fetching CLUTCH reviews: Displays message "Something went wrong while preparing database".

2.  issue2: API Key invalid error pops up when trying to fetch reviews:
Screengrab(video): https://monosnap.com/file/o38GbvpvdGBMQ3kV8aOoq7OsKHsBcf
Displays this message in the Network section (Response): "API key is not valid"
Message: https://monosnap.com/file/H9uSpZ0Z0Z7bKi2551rXgbSkjabfbZ

Reference: https://secure.helpscout.net/conversation/1261491351/149895?folderId=3514643

**Comment by Sanjeevsetu** [comment]
Currently, We do not support clutch.co

**Comment by Sanjeevsetu** [comment]
Other issues have been solved at our server
