### ISSUE TITLE
Add Schema for the Jobs.

### ISSUE THREAD

**Issue by mdsam10** [ahmedkaludi/schema-and-structured-data-for-wp#120]
Ref:- https://secure.helpscout.net/conversation/744869095/48137?folderId=2206768

Desc:- https://schema.org/JobPosting
           https://developers.google.com/search/docs/data-types/job-posting and Make the schema compatibility with the WP job manager plugin.

**Comment by ahmedkaludi** [comment]
need to make this compatible: https://wordpress.org/plugins/wp-job-manager/

**Comment by janKir** [comment]
[Google requires the description field to be in HTML](https://developers.google.com/search/docs/data-types/job-posting#definitions). However, all my html tags are stripped out when updating the JobPost. I tried to escape the tags using `&lt;` and `&gt;` which works on the first save. But after saving these seem to be converted to `<>` chars which will be stripped out again after another saving. Any ideas?
