### ISSUE TITLE
Review count is showing as a minus value: Maximum Reviews Limits -10 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1201]
https://secure.helpscout.net/conversation/1282540636/154521?folderId=2632030

Use: Use has fetched the Facebook review overall 30 reviews and the remaining count of review fetch section is showing as -10

He as one purchase of 50 reviews.

**Comment by DikshantJoshi** [comment]
Same issue with another user.
Reference: https://secure.helpscout.net/conversation/1286721940/155220?folderId=3514643

User unable to fetch reviews, and the review count is in negative.

**Comment by Sanjeevsetu** [comment]
This issue has been solved on our server code
