### ISSUE TITLE
Need to add Car schema 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#1205]
Use case: 
A user is building a new car directory that will list available cars and channel leads to the new vehicle dealers.
As people are searching for the car in google it would be great if rich snippets could show particular specifications of each vehicle. For example what is the cargo space of a Tesla model X. I would map the fields of the directory to the schema output.

ref: https://secure.helpscout.net/conversation/1288872318/155565?folderId=3514643

**Comment by Sanjeevsetu** [comment]
This ticket has been pushed in https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1305
