### ISSUE TITLE
Need to add compatibility of "Slim SEO" plugin with Schema

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/schema-and-structured-data-for-wp#1214]
User is interested in Webmaster Package and seeking for compatibility of Slim SEO with Schema plugin.

Ref : https://secure.helpscout.net/conversation/1300806890/157590?folderId=4074390

**Comment by cakobox** [comment]
Hi,

Yes. Specifically I need Slim SEO work together with https://wordpress.org/plugins/schema-and-structured-data-for-wp/ and https://codecanyon.net/item/dw-question-answer-pro-wordpress-plugin/15057949 . The purpose is I want my Q&A website to be auto SEO optimized using SlimSEO with schema&structured. 

Regards.
