### ISSUE TITLE
Stop auto-generating images in "1200, 900, 675, 720 px"

### ISSUE THREAD

**Issue by paavandc** [ahmedkaludi/schema-and-structured-data-for-wp#1220]
Now I have one small issue with your plugin is that its auto-generating images in "1200, 900, 675, 720 px" to my host and I have already 2000 images there. So is there any code to add in my functions.php to stop generating new images because my all default logo images are 256x256px and 75x75px only…

Thank you

**Comment by Sanjeevsetu** [comment]
It is recommended by google but if you do not want it. You can enable "Allow Multiple Size Image Creation
" option (https://prnt.sc/v2tn63) in Advanced tap
