### ISSUE TITLE
Issue with event schema plugin.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#1222]
Fatal error: Uncaught Error: Call to undefined function mptt_get_event_data () in /home/estiloswing/www/wp-content/plugins/event-schema-for-saswp/output/output.php:1077 Stack trace: # 0 / home / styleswing / www / wp-includes / class-wp-hook.php (287): saswp_timetable_event_schema (Array) # 1 /home/estiloswing/www/wp-includes/plugin.php(206): WP_Hook-> apply_filters (Array, Array) # 2 /home/estiloswing/www/wp-content/plugins/schema-and-structured-data-for-wp/output/output.php(1108): apply_filters ('saswp_modify_ev ...', Array) # 3 / home / styleswing / www / wp-content / plugins / schema-and-structured-data-for-wp / output / function.php (252): saswp_schema_output () # 4 / home / styleswing / www / wp-content / plugins /schema-and-structured-data-for-wp/output/function.php(117): saswp_get_all_schema_markup_output () # 5 /home/estiloswing/www/wp-includes/class-wp-hook.php(287):saswp_schema_markup_output ('') # 6 /home/estiloswing/www/wp-includes/class-wp-hook.php(311): WP_Hook-> apply_filters (NULL, Array) # 7 / home / styleswing / www / wp-includes /plugin.php(478): WP_Hook-> do_ in/home/estiloswing/www/wp-content/plugins/event-schema-for-saswp/output/output.php on line 1077

Fetching the above fatal error when Event schema is enabled.

Ref URL: https://secure.helpscout.net/conversation/1308400809/159139?folderId=1060556

**Comment by Sanjeevsetu** [comment]
The issue has been fixed in Event Extension
