### ISSUE TITLE
Issue in fetching reviews when trying to fetch reviews for the second or nth-time

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#1223]
Issue in fetching reviews when trying to fetch reviews for the second or nth-time:
Generally adding the number higher than the previous fetch, yields new reviews, but it does not work efficiently. 
and sometimes does not work altogether.

**Comment by Sanjeevsetu** [comment]
The issue has been solved on our server.
