### ISSUE TITLE
Need to add schema custum editor.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1224]
Ref:https://secure.helpscout.net/conversation/1314884011/160347?folderId=2770543

Need to add the custom field for adding the  custom schema markup along with the schema type.

create  a option for custum scheme editor, so we can add raw json schema markup.

**Comment by Sanjeevsetu** [comment]
We have this option. go to tutorial. https://structured-data-for-wp.com/docs/article/how-to-add-custom-schemajson-code-without-writing-code-in-wordpress/
