### ISSUE TITLE
Judge.me reviews are not updating in backend.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#1232]
Though the user fetched all the reviews from the judge.me on his site - not updating in the backend.

Issue URL: https://e-watts.fr/produit/lock-renforce-xiaomi-m365-pro/

in the above URL, we can check the review count difference in both frontend & backend(schema tool).

Ref Ticket: https://secure.helpscout.net/conversation/1325665530/162581?folderId=3126461

**Comment by Sanjeevsetu** [comment]
the issue has been solved on our server
