### ISSUE TITLE
A user wants to set a default image for the manually entered reviews.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#1237]
The user would like the PHP file/ template for these manually entered reviews, so he can just hard code the image link in the template file as a solution.

Ref: https://secure.helpscout.net/conversation/1261491351/149895?folderId=3514643

We would also need to create a tutorial for the same on our website.

**Comment by ahmedkaludi** [comment]
a user wants to hard code and add a standard icon to the reviews that he manually adds

and wanted to know how he could do it, and was requesting for the php template via which he could do it.
