### ISSUE TITLE
Speed issue when 'Archive' option is enabled in Schema settings.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#1248]
Facing the low-speed issue when we enable the 'Archive' option in Schema settings.

Screenshot: https://prnt.sc/vldnkz

Ref Ticket: https://secure.helpscout.net/conversation/1340824028/165528?folderId=3126461

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply. Once We get more data on it. We will work on it.
