### ISSUE TITLE
Import functionality not working

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/schema-and-structured-data-for-wp#1250]
Unable to import  configuration and schema  using "Import All Settings & Schema" option in Structure Data>settings>Advanced.

Ref: https://wordpress.org/support/topic/plugin-causing-long-loading-and-resulting-in-timeout-524-error/
screenshot: https://prnt.sc/vlzg67

**Comment by Sanjeevsetu** [comment]
This is not a valid issue. Actually user was mission to allow uploads true.
