### ISSUE TITLE
Why inLanguage property is absent from NewsArticle and Article schema types?

### ISSUE THREAD

**Issue by mmprep** [ahmedkaludi/schema-and-structured-data-for-wp#1260]
Why did you decide that your audience is exclusively English-speaking and speaks American English?

Why can't I choose inLanguage property in NewsArticle and Article schema types?

For example, all my posts are in Russian. But when checking via https://search.google.com/test/rich-results, inLanguage is set to en-US. This is not acceptable.

**Comment by Sanjeevsetu** [comment]
Hi @mmprep, 

We take current site language internally. Are you talking about "inLanguage property is missing from modify schema" where user can choose own language.?

**Comment by mmprep** [comment]
Hi @Sanjeevsetu,

But what if the Wordpress interface language is set to English, but the posts are made in a completely different language?

It's better to let you choose the language in inLanguage property in EVERY schemas you've supported.

**Comment by Sanjeevsetu** [comment]
Yes, I agree.

We will fix it.
