### ISSUE TITLE
If the"Product Default Review" option is enabled then the "Unspecified type"showing as the schema type

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1268]
Ref : https://secure.helpscout.net/conversation/1361391560/169522/

When the user enabling the "Product Default Review" option, it is showing the "Unspecified Type" in the schema type for the product schema type.

Issue recreated on the local.

Screenshot: https://prnt.sc/vyypoz

**Comment by Arihantkankariya09** [comment]
The same user reported one more issue

In webpage schema, modify schema -> add property -> keywords -> manual text. 
The text entered is not displayed and captured in the markup. 
Keyword is blank = Local https://prnt.sc/w0iws3
Users screenshot https://prnt.sc/w0iy60

**Comment by Sanjeevsetu** [comment]
2nd issue is created and solved but waiting for 1st one to re create it. Waiting for user reply

**Comment by Sanjeevsetu** [comment]
The 1st issue is not being created on localhost and user has not replied. I am currently closing this ticket.
