### ISSUE TITLE
When Elementor Testimonial compatibility is selected, local business schema type is missing its type(unspecified Type)

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1270]
When Elementor Testimonial compatibility is selected, the local business schema type is missing its type and showing as (unspecified Type) in the schema test.

https://secure.helpscout.net/conversation/1359560433/168796?folderId=2632030

https://fiorellainsurance.com/google-reviews/

issue recreated in local as well.

**Comment by sardarui** [comment]
Another user facing the same issue,

Ref Ticket: https://secure.helpscout.net/conversation/1365505718/170172/
