### ISSUE TITLE
Need to add an option to show the price in the schema including the Vat

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1273]
Ref: https://secure.helpscout.net/conversation/1358841057/168643?folderId=2770545

We need to add the option in the "WooCommerce Compatibility for Schema" plugin to add the price including the VAT in the schema.

Currently, if the price field in the frontend is $26 (https://prnt.sc/w2cv2w) and then when we add the product in the exclusive tax, it is not adding in the schema. Please see the screenshots:
https://prnt.sc/w2d4sg
https://prnt.sc/w2d5hg

**Comment by Sanjeevsetu** [comment]
Need user collaboration and waiting for user response. Currently I am putting this ticket in progress but leaving from milestone. Once it is done. I will push the current developed milestone.

**Comment by Sanjeevsetu** [comment]
User has not replied yet so I am closing this ticket currently. When I get anything related to this will open it again
