### ISSUE TITLE
If the Valid through is empty in modify schema output it does not allow job posting to display.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#1276]
If the Valid through is empty in modify schema output it does not allow job posting to display.

Ref:https://secure.helpscout.net/conversation/1362656937/169722?folderId=3575684

Ref link: https://www.dakdekkervolendam.nl/vacatures/ervaren-zinkwerker/

**Comment by jawadkhakh** [comment]
valid through property is necessary for job posting schema. job posting schema depends on valid through property. After passing valid through date, the job posting schema should be off.
I want old setting back where schema was off when there was no date. Is it possible?
here is the direction from google.
https://www.seroundtable.com/google-job-listing-penalty-25578.html
