### ISSUE TITLE
Need to add reviews form the "goodreads.com"

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#1278]
Need to add reviews form the "goodreads.com"

Ref link: https://www.goodreads.com/

Ref: https://secure.helpscout.net/conversation/1373819918/171378?folderId=3575684

**Comment by ahmedkaludi** [comment]
https://www.goodreads.com/api

**Comment by Sanjeevsetu** [comment]
This ticket is on hold to get more data to get it implemented.
