### ISSUE TITLE
AMP: plugin is activated, yet checkbox is greyed out when using global filter

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [ahmedkaludi/schema-and-structured-data-for-wp#129]
On our setup I am using the following AMP plugin filter in our theme's functions.php:
`add_filter( 'amp_post_status_default_enabled', '__return_false' );`

using this filter, allows us to enable AMP on a per post basis via checkbox in post editor.
However somehow this filter causes your plugin to not recognize AMP plugin to be activated and outgreyes the use markup for AMP checkbox.

Desired behaviour:
do not grey out the checkbox and make it available with this filter.

**Comment by Sanjeevsetu** [comment]
Hi @s-a-s-k-i-a,

Could you please provide us more details at team@magazine3.com so that we can debug your issue and will fix it. Please mention that you come from github and attach this link.

Thanks
Sanjeev.

**Comment by s-a-s-k-i-a** [comment]
Well, there is not much more to say:
How to reproduce:
Add mentioned filter function to rheme or child theme functions.php to turn OFF amp by default for all post types, that are enabled for AMP in AMP settings.

However when this filter is being used, it is impossible to activate schema structures in your plugin‘s settings, as you plugin seems to believe that no amp is available at all. this is incorrect behaviour, as amp may be enabled on a per post basis.
