### ISSUE TITLE
NewsArticle markup is missing organization logo url / make use of yoast seo settings if available

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [ahmedkaludi/schema-and-structured-data-for-wp#130]
I activated NewsArticle on posts, however structured data test tool shows missing organization logo url:
https://search.google.com/structured-data/testing-tool?hl=de#url=https%3A%2F%2Fwww.gegen-hartz.de%2Furteile%2Fjobcenter-verweigert-kostenuebernahme-fuer-tv-receiver-8520258

How can I add this?
The plugin should recognize, if Yoast SEO is activated and pull organizational/personal info from their settings.

**Comment by Sanjeevsetu** [comment]
Hi @s-a-s-k-i-a ,

I can see your schema markup and organization logo url is there but it has invalid width and height. I should be 160*50 as per google norm.

Regarding your 2nd question, Yes we are making compatibility with Yoast SEO, if it is activated than we will not show our organization/personal markup.

**Comment by Sanjeevsetu** [comment]
Hi @s-a-s-k-i-a, 

We have made compatibility with Yoast SEO, and released new version 1.0.8. Please try our new version

Thanks
