### ISSUE TITLE
Validation issues with "HTML5 Responsive FAQ" plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1302]
-  The "main Entity field" error showing for the FAQ custom post types.
URL: https://www.lemiapps.com/hrf_faq/how-to-install-android-app-from-website/

Screenshot: 
https://prnt.sc/xp3py7
https://prnt.sc/xp3sxg

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in our pro extension.
