### ISSUE TITLE
yoast premium

### ISSUE THREAD

**Issue by iamkingsleyf** [ahmedkaludi/schema-and-structured-data-for-wp#134]
Hello;

The Yoast check box is not active where i have yoast premium installed but its check-able where i have yoast FREE version.

Please see the screenshot...

Yoast Premium https://healthable.org >>> https://imgur.com/a/N5vAeoP
Yoast Free https://thegloor.com >>> https://imgur.com/a/dlqowOM 

Thanks

**Comment by Sanjeevsetu** [comment]
Hi @iamkingsleyf,

Could you please send us yoast premium plugin at team@magazine3.com ????

**Comment by iamkingsleyf** [comment]
you mean the ZIP file?

**Comment by Sanjeevsetu** [comment]
yeah

**Comment by iamkingsleyf** [comment]
> yeah

sent

**Comment by iamkingsleyf** [comment]
email bounced back

**Comment by iamkingsleyf** [comment]
Message may contain a virus
--
Your message wasn't delivered to team@magazine3.combecause it may contain a virus. Learn how to check for and prevent viruses.

**Comment by Sanjeevsetu** [comment]
Please send here operations@magazine3.com

**Comment by iamkingsleyf** [comment]
sent again

**Comment by Sanjeevsetu** [comment]
Thanks, 
We got it and has fixed it. Tomorrow, we are going to push an update.

**Comment by iamkingsleyf** [comment]
oh, great
