### ISSUE TITLE
Add Support for WP GraphQL plugin

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/schema-and-structured-data-for-wp#1343]
Add support for WP GraphQL plugin and also needed to add PHP function to get schema markup.

Ref: https://secure.helpscout.net/conversation/1450025397/185135?folderId=4473027

**Comment by MohammedKaludi** [comment]
Need to add the support for WP GraphQL this is very important.
Please do let me know if you need my help in this one
