### ISSUE TITLE
Breadcrumbs not correct

### ISSUE THREAD

**Issue by ndv80** [ahmedkaludi/schema-and-structured-data-for-wp#1364]
I have installed the plugin and everything is perfect apart from the breadcrumbs output - the output is different from the actual breadcrumbs on my website - it's like its getting the data from somewhere else on the website...
Exclude category is unchecked etc...

**Comment by Sanjeevsetu** [comment]
Hi @ndv80. 

Can you share your urls where We can see the difference?

**Comment by Sanjeevsetu** [comment]
Hi @ndv80. 

Can you help us to find the issue or We will close this ticket???
