### ISSUE TITLE
Reviews Schema for Real Estate

### ISSUE THREAD

**Issue by sirnewbee** [ahmedkaludi/schema-and-structured-data-for-wp#137]
Hello! Is it possible to request for a schema about reviews in real estate? This is the website ([https://properties-philippines.com/properties/](https://properties-philippines.com/properties/)). I was thinking of a schema that may support the following; star ratings, reviews, interested buyers, and so on. But if you have any other suggestions that would be great too.

 Have a great day!

**Comment by ahmedkaludi** [comment]
@sirnewbee what plugin or theme are you using for real estate directory?

**Comment by Sanjeevsetu** [comment]
Hi @sirnewbee,
Can you please let us know the plugin or theme name for realestate directory? How you are listing them on your website?

**Comment by Sanjeevsetu** [comment]
I will suggest you to use product schema and add reviews on it.
