### ISSUE TITLE
Need to provide an option for changing the FAQ (SASWP) text to H1 H2 H3

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1382]
https://secure.helpscout.net/conversation/1483584372/190974/

use case: user want to change the FAQ text to H1 H2 H3

as mentioned in the screenshot

![image](https://user-images.githubusercontent.com/46995400/115019096-53242600-9ed6-11eb-8334-97eecdc2de74.png)

**Comment by mohammed-qutubuddin** [comment]
https://secure.helpscout.net/conversation/1507247240/195332?folderId=4409869
One more user request for it.
