### ISSUE TITLE
"Thumbnail URL" and "Duration" field data are not fetching automatically. 

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/schema-and-structured-data-for-wp#1389]
"Thumbnail URL" and "Duration" field data are not fetching automatically in the video object schema. This issue is occurring on the local as well.

Ref: https://secure.helpscout.net/conversation/1487875063/191682?folderId=3575684.

**Comment by HaripriyaHari** [comment]
Another user has the same issue: https://secure.helpscout.net/conversation/1490664878/192109?folderId=4195936
