### ISSUE TITLE
Need compatibility with video map schema of Rank Math Pro

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [ahmedkaludi/schema-and-structured-data-for-wp#1397]
When we use both our schema and Rank Math's video map schema, only one out of them is fetched in markup.
Need compatibility to get both of them to work simultaneously.
Reference ticket - https://secure.helpscout.net/conversation/1474079215/189280?folderId=4074390

**Comment by Sanjeevsetu** [comment]
Needed user support on this ticket but user was not interested. Except this user no one user is reporting the same issue so currently I am closing this ticket,
