### ISSUE TITLE
Inf and NaN cannot be JSON encoded

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1399]
https://secure.helpscout.net/conversation/1487317910/191599?folderId=2632030

https://stagingfortorontoclearview.torontoclearview.com/test-page/

The issue is as we are facing JSON error:

![image](https://user-images.githubusercontent.com/46995400/117142504-68052280-adcd-11eb-963c-0cae68456532.png)

**Comment by Sanjeevsetu** [comment]
This issue is fixed on pro reviews for schema extension
