### ISSUE TITLE
Schema & Structured Data for WordPress - #1 Rich Snippets Plugin "Bug / php8.0.3 incompatability?"

### ISSUE THREAD

**Issue by raza-web** [ahmedkaludi/schema-and-structured-data-for-wp#1409]
[https://secure.helpscout.net/conversation/1509999042/195779?folderId=1060556](url)

**Comment by Arihantkankariya09** [comment]
Warnings on product pages while using PHP version 8.0.3. 
https://secure.helpscout.net/conversation/1509999042/195779?folderId=1060556
Warning given by user :- Warning: Undefined array key "key_4" in /home/customer/www/unicornfibres.com.au/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 645

Warning on my local:- https://prnt.sc/12u93p2

**Comment by Arihantkankariya09** [comment]
Another user reported some debug warnings 
https://secure.helpscout.net/conversation/1511040924/195960?folderId=1060554

Notice: Undefined index: administrator in /home/demohpjk/public_html/hgc/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 3272

Notice: Undefined variable: currentuserrole in /home/demohpjk/public_html/hgc/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 3277
