### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_bookings() on null in event-schema-for-saswp/output/service.php:8

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/schema-and-structured-data-for-wp#1410]
Fatal error: Uncaught Error: Call to a member function get_bookings() on null in event-schema-for-saswp/output/service.php:8

Ref:  https://secure.helpscout.net/conversation/1503067098/194663?folderId=3575684

**Comment by Sanjeevsetu** [comment]
This issue was fixed on pro extension
