### ISSUE TITLE
 Feature support for polylang extension  with schema 

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1431]
Here is user scenario: 

The user website is multilingual (polylang)
In general settings schema plugin ask for about,contact page and navigation menu. Now he want to set them as per language. 

Ref ticket : https://wordpress.org/support/topic/multilingual-website-22/

**Comment by MyWebmasterD** [comment]
thanks, I'll follow this issue

**Comment by MyWebmasterD** [comment]
Hello, in new plugin version this is not solved. I'm not able to select different pages for language on the general settings page

**Comment by Sanjeevsetu** [comment]
Hi @MyWebmasterD.

Sorry for the inconvenience. Actually this feature is related to our pro extension ( https://structured-data-for-wp.com/polylang-compatibility-for-saswp ). You do not need to add multiple pages inside about or contact page. We have automated it based on languages by Polylang for that about or contact page.

If you have our pro extension and still facing issue. Please let us know.

**Comment by MyWebmasterD** [comment]
ok I understand, I didn't know it was related to the pro extension
