### ISSUE TITLE
NewsMediaOrganization schema

### ISSUE THREAD

**Issue by amirariff91** [ahmedkaludi/schema-and-structured-data-for-wp#147]
Hi,

News media sites badly need this organization schema please add NewsMediaOrganization in the next release, thank you so much for your amazing work on the plugin!

Best,
Amir

**Comment by Sanjeevsetu** [comment]
Do you have any references of json markup.? if you are adding manually than how you are adding??

**Comment by amirariff91** [comment]
Hi Sanjeev, I've been using this plugin https://wordpress.org/plugins/wp-structuring-markup/ and it has the NewsMediaOrganization schema readily available for selection.

**Comment by amirariff91** [comment]
Should I get the json markup?

**Comment by Sanjeevsetu** [comment]
If you could than it will be better for us to implement it quickly. However you will add it
