### ISSUE TITLE
License Key {Fatal Error}- Reviews for Schema

### ISSUE THREAD

**Issue by raza-web** [ahmedkaludi/schema-and-structured-data-for-wp#1473]
When the parent plugin(Structured data) is not installed/activated on the user's end, and if he clicks on the "Please enter the license key"  in Review for Schema, the page displays "Sorry You are not allowed to access this page.

Helpscout Link- https://secure.helpscout.net/conversation/1559929591/204934?folderId=4626537

**Comment by Sanjeevsetu** [comment]
this issue is fixed on reviews for schema add on
