### ISSUE TITLE
Article category("Thing" is not a known valid target type for the publisher property)

### ISSUE THREAD

**Issue by raza-web** [ahmedkaludi/schema-and-structured-data-for-wp#1474]
The user receives error in the Article category("Thing" is not a known valid target type for the publisher property) in the structured data testing tool in the latest version(1.9.81) in Schema & Structured Data
But, when rollback to the previous version - 1.9.80, these testing tool displays no errors.

https://search.google.com/search-console/amp/drilldown?resource_id=sc-domain%3Abitcoin-casino-no-deposit-bonus.com&item_key=GgQIExAC&hl=en&sharing_key=c4-bZi_YP7KkWAR6mpVy1A

Helpscout link - https://secure.helpscout.net/conversation/1566706602/205684?folderId=4626537

**Comment by Sanjeevsetu** [comment]
Issue is not seen on the given url so I am moving this ticket to close.
