### ISSUE TITLE
Compatibility for Hivepress paid listings in Local business schema.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#1479]
https://secure.helpscout.net/conversation/1566176440/205627?folderId=1060554

[hivepress-paid-listings.zip](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/files/6815259/hivepress-paid-listings.zip)
[hivepress.zip](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/files/6815261/hivepress.zip)

User is using hivepress to create listings for his local business.

**Comment by Sanjeevsetu** [comment]
We need more data on it and user is still not replying on it. I am currently closing this ticket.
