### ISSUE TITLE
Call to undefined function ampforwp_saswp_get_the_ID()

### ISSUE THREAD

**Issue by Shwayze23** [ahmedkaludi/schema-and-structured-data-for-wp#1483]
This error was created after update of SASWP plugin.  I have Elementor, elementor pro as page builder.  Astra  Child theme.  WP Version is latest.  And it is used with AMP accelerated Mobile Pages

[15-Jul-2021 20:59:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ampforwp_saswp_get_the_ID() in /home/c9fo89vg4yu8/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:3642
Stack trace:
#0 /home/c9fo89vg4yu8/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php(181): saswp_update_global_post()
#1 /home/c9fo89vg4yu8/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php(128): saswp_get_all_schema_markup_output()
#2 /home/c9fo89vg4yu8/public_html/wp-includes/class-wp-hook.php(292): saswp_schema_markup_output(Object(AMPforWP\AMPVendor\AMP_Post_Template))
#3 /home/c9fo89vg4yu8/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#4 /home/c9fo89vg4yu8/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#5 /home/c9fo89vg4yu8/public_html/wp-content/plugins/accelerated-mobile-pages/templates/design-manager/design-3/frontpage.php(15): do_action('amp_post_templa...', Object(AMPforWP\AMPVend in /home/c9fo89vg4yu8/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 3642

**Comment by Sanjeevsetu** [comment]
Hi @Shwayze23 

We have fixed the issue and pushed in latest v1.9.82.1. Please update to that and let us know.
