### ISSUE TITLE
Fatal error in post category edit section 

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1484]
`[17-Jul-2021 10:04:35 UTC] PHP Fatal error: Uncaught Error: Call to undefined function saswp_post_exists() in /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:4304
Stack trace:
#0 /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php(1682): saswp_get_post_meta()
#1 /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/core/array-list/schema-properties.php(873): saswp_get_the_tags()
#2 /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/view/common.php(40): saswp_get_fields_by_schema_type()
#3 /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/view/post_specific.php(34): saswp_view_common_class->__construct()
#4 /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/view/post_specific.php(650): saswp_post_specific->__construct()
#5 /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/structured-data-for-wp.php(87): require_once(‘/home/myserver…’)
#6 /home/myserver/public_html/wp-settings.php(391): include_once(‘/home/myserver…’)
#7 /home/myserver/public_html/wp-config.php(93): require_once(‘/home/myserver…’)
#8 /home/myserver/public_html/wp-load.php(37): require_once(‘/home/myserver…’)
#9 /home/myserver/public_html/wp-admin/admin.php(34): require_once(‘/home/myserver…’)
#10 /home/myserver/public_html/wp-admin/term.php(11): require_once(‘/home/myserver…’)
#11 {main}
thrown in /home/myserver/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 4304`

Reference ticket: https://wordpress.org/support/topic/unable-to-edit-post-category/

**Comment by Sanjeevsetu** [comment]
this issue is same as https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1485. So I am closing it and will fix there.
