### ISSUE TITLE
technical error

### ISSUE THREAD

**Issue by shawaizehsan** [ahmedkaludi/schema-and-structured-data-for-wp#1485]
WordPress version 5.7.2
Current theme: Goya Child Theme (version 1.0)
Current plugin: Schema & Structured Data for WP & AMP (version 1.9.82.1)
PHP version 7.3.12

Error Details
=============
An error of type E_ERROR was caused in line 4304 of the file /var/www/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php. Error message: Uncaught Error: Call to undefined function saswp_post_exists() in /var/www/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:4304
Stack trace:
#0 /var/www/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php(1682): saswp_get_post_meta(1888, 'mtm_data', true)
#1 /var/www/wp-content/plugins/schema-and-structured-data-for-wp/core/array-list/schema-properties.php(873): saswp_get_the_tags()
#2 /var/www/wp-content/plugins/schema-and-structured-data-for-wp/view/common.php(40): saswp_get_fields_by_schema_type(NULL, NULL, 'Article', 'manual')
#3 /var/www/wp-content/plugins/schema-and-structured-data-for-wp/view/post_specific.php(34): saswp_view_common_class->__construct()
#4 /var/www/wp-content/plugins/schema-and-structured-data-for-wp/view/post_specific.php(650): saswp_post_specific->__construct()
#5 /var/www/wp-content/plugins/schema-and-structured-data-for-wp/structured-data-for-wp.php(87): require_once('/var/www/wp-con...')
#6 /var/www/wp-settings.php(391):

I have installed a plugin “ wp advanced columns” after installing a fetal error was created in site but site load in google properly but just in wordpress dashboard product categories are unable to edit and show error message. Now I have uninstall this plugin(“ wp advanced columns” ) and delete it. But due to this plugin the issue created with this plugin “Schema & Structured Data for WP & AMP “. If I uninstall this plugin(“Schema & Structured Data for WP & AMP “) then error removes and site get back to normal.

**Comment by shawaizehsan** [comment]
But i want to use use this plugin for my schemas please help me to resolve this issue.

**Comment by Sanjeevsetu** [comment]
Please contact here for any quick response. https://structured-data-for-wp.com/contact-us/
