### ISSUE TITLE
conflict with popup maker when schema enabled

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1495]
Getting error in create -popup when using both schema and popup maker plugin. if we deactivate the schema the error not showing. only when activated schema only it is showing the error

Reference screengrab: https://prnt.sc/1hje3vr 
Reference ticket: https://wordpress.org/support/topic/possible-plugin-conflict-with-popup-maker/

**Comment by mohammed-qutubuddin** [comment]
One more user-facing the same issue.
Reference Ticket: https://secure.helpscout.net/conversation/1584558741/207896/
