### ISSUE TITLE
Shortcode to Insert FAQ in product page frontend

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1502]
The user wants to insert FAQ on the product page frontend. 

Reference screengrab: https://prnt.sc/1q9swuo
Reference ticket: https://wordpress.org/support/topic/insert-faq-in-product-page/

**Comment by Sanjeevsetu** [comment]
There is a new feature "SASWP Schema block" added to classic editor. It will help user's to add content as well as jsonld to product or any page or post.
