### ISSUE TITLE
1 click indexing: PHP Fatal error issue 

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/schema-and-structured-data-for-wp#1504]
Helpscout ref: https://secure.helpscout.net/conversation/1602979458/210098?folderId=3448167

PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in D:\XAMPP\htdocs\M3\wp-content\plugins\1-click-indexing-api-integration-for-saswp\vendor\google\apiclient\src\Google\Service\Resource.php:297
Stack trace:

**Comment by Sanjeevsetu** [comment]
This issue is fixed in 1 click pro extension.
