### ISSUE TITLE
When post having multiple categories, Only one category is rendering in in breadcrumbs list schema type.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1511]
Ref:https://secure.helpscout.net/conversation/1607585303/210581?folderId=2770543

When a single post has multiple categories,  but only one category is rendering in in breadcrumbs list.

ROLLBACK  15 OLDER VERSIONS TESTED THE ISSUE.

**Comment by Sanjeevsetu** [comment]
Its not an issue. It is a feature with yoast seo compatibility. It works as per seo primary category setup by user.
