### ISSUE TITLE
 PHP Fatal error:  Cannot redeclare saswp_add_more_placement_func()

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/schema-and-structured-data-for-wp#1517]
PHP Fatal error:  Cannot redeclare saswp_add_more_placement_func() (previously declared in C:\xampp\htdocs\w1\wp-content\plugins\wpml-schema-compatibility\output\output.php:112) in C:\xampp\htdocs\w1\wp-content\plugins\polylang-compatibility-for-saswp\output\function.php on line 119

**Comment by Sanjeevsetu** [comment]
Fixed pushed in wpml schema compatibility extension
