### ISSUE TITLE
Option to include the number of votes each comment has received in the structured data

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1523]
User using wpdiscuz plugin to include votes in comment system. 
Reference example URL: https://rebrand.ly/kokv3ps

Now he wants an option to include the number of votes each comment has received in the structured data. 

Reference ticket: https://wordpress.org/support/topic/including-votes-in-structured-data/

**Comment by dodgeballin345** [comment]
subscribed
