### ISSUE TITLE
Unable to fetch reviews.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1526]
Ref:https://secure.helpscout.net/conversation/1624751975/212380?folderId=2770543

Unable to fetch reviews, it shows We are preparing reviews. Please wait or we will send an email on it's completation.

Screenshot: https://monosnap.com/file/B3zqk0OHLISFzbtBTB3nJoU5WYt7Nk

Please fix ASAP

**Comment by kupveja** [comment]
Getting same issue on one user's end 

ref - https://secure.helpscout.net/conversation/1628034001/212653?folderId=4459751

**Comment by Sanjeevsetu** [comment]
This issue has been solved on our reviews server
