### ISSUE TITLE
Error message in “/wp-admin/widgets.php” when activate the “Schema & Structured Data for WP & AMP” plugin

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1527]
Reference screengrab: https://prnt.sc/1sj4vx0
Reference ticket:  https://wordpress.org/support/topic/wp-editor-should-not-be-enqueued-together-with-the-new-widgets-editor-2/

**Comment by ArtGoddess** [comment]
Great, after updating, no debug messages in log file or screen. As far as I can see, issue solved.
Congrats and thank you!
