### ISSUE TITLE
Issue with Yell an Yellowpages fetched reviews in collection

### ISSUE THREAD

**Issue by JNAzeem** [ahmedkaludi/schema-and-structured-data-for-wp#1534]
Review platform field in review is empty for reviews fetched using Reviews for schema extension, Issue occurring with  Yell and YellowPages https://prnt.sc/1tc1sqv. Due to which user is having an issue with selecting review source as those platforms are shown as inActive https://prnt.sc/1tc1yfo.

Helpscout ref: https://secure.helpscout.net/conversation/1632437085/213041?folderId=4544752

**Comment by Sanjeevsetu** [comment]
The issue happen because user fetched yell review in yellow-pages section. Its fine now at user end
