### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by Tktcleaning** [ahmedkaludi/schema-and-structured-data-for-wp#1538]
I get error when update to Version 1.9.85
Warning: require_once(/home/tktgvn/domains/tktg.vn/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/service.php): failed to open stream: No such file or directory in /home/tktgvn/domains/tktg.vn/public_html/wp-content/plugins/schema-and-structured-data-for-wp/structured-data-for-wp.php on line 91

Fatal error: require_once(): Failed opening required '/home/tktgvn/domains/tktg.vn/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/service.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/tktgvn/domains/tktg.vn/public_html/wp-content/plugins/schema-and-structured-data-for-wp/structured-data-for-wp.php on line 91

**Comment by Sanjeevsetu** [comment]
This issue is not occurring at our end. We need more information on it. Kindly contact us via https://structured-data-for-wp.com/contact-us/

**Comment by Sanjeevsetu** [comment]
Hi @Tktcleaning.

As you said on our forum ( https://wordpress.org/support/topic/error-updating-the-plugin-2/ ). It is working fine so I am closing this ticket here. If again you face issue, Please let us know
