### ISSUE TITLE
Latest Update Issues: Woocommerce Category Page

### ISSUE THREAD

**Issue by yabdali** [ahmedkaludi/schema-and-structured-data-for-wp#1554]
Hi,
Updated last night to the latest release but when running the schema.org validation I see that the ItemList section for the Woocommerce Category page misconfigured the product element review part. It includes the short description for the product as the review, puts the author of the product page as the reviewer! Would you please check the links below to validate the issue? Thanks

[https://www.capitano.om/discover/categories/tours/](url)
[https://validator.schema.org/?hl=en-US#url=https%3A%2F%2Fwww.capitano.om%2Fdiscover%2Fcategories%2Ftours%2F](url)

**Comment by Sanjeevsetu** [comment]
Great, You got the solution. I am closing this ticket right now. If you need further help or find any issue create a new ticket.
