### ISSUE TITLE
When we are adding reviews from the "WP review slider pro" plugin aggregate rating field markup is missing. 

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#1555]
When we are adding reviews from the "WP review slider pro" plugin aggregate rating field markup is missing. 

Ref  URL:  https://torontoclearview.com/

Ref: https://secure.helpscout.net/conversation/1669708987/215802?folderId=3575684

**Comment by Sanjeevsetu** [comment]
Waiting for user reply till than moving to next milestone.

**Comment by Sanjeevsetu** [comment]
User has not used WP review slider pro shortcode to homepage to show reviews that's why reviews schema markup is not being added to homepage. Guided to setup it. 

Closing this ticket
