### ISSUE TITLE
Reviews are not translated website's native language.(Review for schema)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1561]
Ref:https://secure.helpscout.net/conversation/1685519172/216774?folderId=2770543

the original Reviews is dutch language, but it does translate into dutch lang, it default shows the English language on the website.

Screenshot:https://monosnap.com/file/PgxSbHmSL28Q5dbuc8WQXS36p0CkBd

**Comment by amer07** [comment]
My name is Beth from Google Maps Platform Technical Support, and I'll be very glad to help and guide you today.

We understand that you wanted to show your reviews in the original (Dutch) language on your website. Just to set the correct expectation, implementation through wordpress themes/plugins are out of scope for us. Although we would love to help, we lack the knowledge, access to the source code or tools to debug the issues. Problems with themes/plugins are best to be reported to the ones who developed them.

Upon checking, I can see that you're using the Place Details API in the server-side (web service). As best effort, I would suggest to use a language parameter in your request and set it to Dutch (nl). Please see the sample Place Details API web request below:

https://maps.googleapis.com/maps/api/place/details/json
?fields=name%2Crating%2Creview
&place_id=ChIJ48VUaPG3xUcRHeMIKTz11iw
&language=nl
&key=YOUR_API_KEY

For more information about Place Details API web services, please see our documentation: https://developers.google.com/maps/documentation/places/web-service/details

Since you are using Wordpress, kindly ask with your theme or plugin developer if changing the language for the Place Details API reviews is possible. If not, then please consider looking for other plugins with where you can set the reviews in Dutch language. It would be best for you to reach out to your website or theme developer for they are the ones who can customize the code implementation of the third party.

**Comment by ankit644** [comment]
Ref: https://secure.helpscout.net/conversation/1688143999/216955?folderId=4874234
when user fetched the reviews, they are in french but when displayed they are translated in english.
