### ISSUE TITLE
Woocommerce: Simple products aren't listed with Prices in Google, Variable products are!

### ISSUE THREAD

**Issue by yabdali** [ahmedkaludi/schema-and-structured-data-for-wp#1578]
Hi,
Something seems to be wrong with simple products (without variation), Google doesn't show the prices on search results wheras it shows the pricing for variable products! Can you please verify if this is by design or a bug? Thanks 
Note: latest release of both structured data and WC. 

![Structured data_products](https://user-images.githubusercontent.com/30695308/144714843-55505b0e-5ae5-4fec-84e3-34a7db8ac65f.jpg)

**Comment by Sanjeevsetu** [comment]
Hi @yabdali.

We tested your few single products in rich results tool ( https://search.google.com/test/rich-results ) and it showed all good for rich snippets. We are also not sure why this is happening.

Here is the preview: https://monosnap.com/direct/YBsNvgeCMHAgJTiOBiaFx4nMNmPbUJ

**Comment by yabdali** [comment]
> Hi @yabdali.
> 
> We tested your few single products in rich results tool ( https://search.google.com/test/rich-results ) and it showed all good for rich snippets. We are also not sure why this is happening.
> 
> Here is the preview: https://monosnap.com/direct/YBsNvgeCMHAgJTiOBiaFx4nMNmPbUJ

Could it be due to how Google handles pages with different structured data elements?  I think even if this is the case, pages of simple and variable products having the same structured elements!  The only difference is that those pages with variable products are published one month earlier than those with simple products.

**Comment by Sanjeevsetu** [comment]
We follow google rich result and It showing price and valid schema. Sometime Google takes time to index it or it shows different result as Google is also saying same that actually appearance in rich results may be differ. 

I am closing this ticket. You still have any issue please new ticket
