### ISSUE TITLE
SiteNavigationElement content not translated website's native language (wpml for schema)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1583]
Ref:https://secure.helpscout.net/conversation/1700624371/217873?folderId=2770543

use case: select UA lang in SiteNavigationElement, it shows a default lang UK on schema validator tool.

Screenshots: 

https://monosnap.com/file/L4JOYzUujFm28dfGd65Uy13nHy2TUv

https://monosnap.com/file/PmsF8O79NQ113Dhp8xbU5IgdPgdrr9

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
This issue has been solved in our pro extension. (wpml-schema-compatibility) https://github.com/ahmedkaludi/wpml-schema-compatibility
