### ISSUE TITLE
Unable to fetch reviews. 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#1588]
REf:https://secure.helpscout.net/conversation/1741256265/221073?folderId=2770543

Unable to fetch reviews, it shows We are preparing reviews. Please wait or we will send an email on it's completion.

Screenshot: https://monosnap.com/file/qz9AImc6UGEpeXWq2igbwLuA8HqqnU

**Comment by ankit644** [comment]
Ref:- https://secure.helpscout.net/conversation/1741748023/221106?folderId=4874234

One user facing the issue facing the same issue.

Screenshot:- https://prnt.sc/25sn7pg

**Comment by Sanjeevsetu** [comment]
issue fixed in our review's server
