### ISSUE TITLE
FAQ list is not showing in the FAQ schema using Accordion Pro plugin.

### ISSUE THREAD

**Issue by kupveja** [ahmedkaludi/schema-and-structured-data-for-wp#1593]
FAQ list is not showing in the FAQ schema using Accordion Pro plugin. In standard version Accordion plugin, FAQ list is working fine.
free plugin ref - https://prnt.sc/26c1cai
Pro plugin ref - https://prnt.sc/26c1cmh
 ticket link - https://secure.helpscout.net/conversation/1741420235/221086?folderId=4459751

**Comment by Sanjeevsetu** [comment]
This does not seems a valid bug. I am closing it
