### ISSUE TITLE
Need to test our plugins up to the new WordPress version 5.9

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#1600]
Need to test our plugins up to the new WordPress version 5.9
https://secure.helpscout.net/conversation/1765126376/223090?folderId=2498305

**Comment by Sanjeevsetu** [comment]
Plugin has been tested with WordPress v5.9 and working fine without any issues. I have updated change log and it would be pushed in latest SASWP version
