### ISSUE TITLE
Reviews are not getting fetched from HomeStars

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1602]
After checking HomeStars option, when we click on fetch it shows request timed out fetch again.

Reference helpscout ticket -: https://secure.helpscout.net/conversation/1764666767/223041?folderId=5893230

reference screenshot -:
![Screenshot (261)](https://user-images.githubusercontent.com/78167698/150952653-6dc6e2a8-bfa8-447e-b10f-d13b54b5f744.png)

**Comment by Sanjeevsetu** [comment]
Related To https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/2230
