### ISSUE TITLE
Structured Data in custom page

### ISSUE THREAD

**Issue by fmerlat-choosit** [ahmedkaludi/schema-and-structured-data-for-wp#1614]
Hi,

I have created a Schema Type for my CPT for 2 placements : https://i.imgur.com/x7jjQ7O.png

- In my CPT single page, structured data are displaying well.
- They’re not displaying in my custom page built with a specific template ‘page-cars.php’ in which I have used the Facet WP shortcodes to display filters and the Posts list.

This is the page : https://www.grim-occasion.com/voitures/

Is that possible to make Structured Data plugin work in these conditions ?

Thank you in advance

**Comment by ahmedkaludi** [comment]
Github is for the tested and valid bugs, this bug hasn't been confirmed yet. 

This is more of a technical issue for which we have a team of technical support dev who can help you to fix the issues. Just contact the support team via https://structured-data-for-wp.com/contact-us/
