### ISSUE TITLE
Add Schema for the Place

### ISSUE THREAD

**Issue by digontobd** [ahmedkaludi/schema-and-structured-data-for-wp#162]
Can you add 'Place' schema type please? It'll be very helpful to me.

https://schema.org/Place

Thanks

**Comment by ahmedkaludi** [comment]
do you add this in the current site? and if so then how?

**Comment by Sanjeevsetu** [comment]
@digontobd Can you please help me understand where will you get the data from?

**Comment by Sanjeevsetu** [comment]
Hi @digontobd ,

We mean. Are you using any plugin or theme to display places?  can you share the name with your website links?

**Comment by MohammedKaludi** [comment]
I am running a directory for rentable Locations/Houses/Places for live action roleplay (LARP) at 
and I cannot find a suitable scheme at google until now. 

https://secure.helpscout.net/conversation/916802545/76977?folderId=3126461

**Comment by ahmedkaludi** [comment]
We have local business and the parent schemas, which has place schema built-in.
