### ISSUE TITLE
PHP Deprecated: _content_template is deprecated since version 2.9.0

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1643]
`PHP Deprecated:  _content_template is <strong>deprecated</strong> since version 2.9.0! Use Elementor\Controls_Stack::content_template() instead. in .../wp-includes/functions.php on line 5316
PHP Stack trace:
PHP   1. {main}() .../wp-admin/post.php:0
PHP   2. require_once() .../wp-admin/post.php:12
PHP   3. do_action() .../wp-admin/admin.php:419
PHP   4. WP_Hook->do_action() .../wp-includes/plugin.php:474
PHP   5. WP_Hook->apply_filters() .../wp-includes/class-wp-hook.php:331
PHP   6. Elementor\Core\Editor\Editor->init() .../wp-includes/class-wp-hook.php:307
PHP   7. Elementor\Core\Editor\Editor->print_editor_template() .../wp-content/plugins/elementor/core/editor/editor.php:158
PHP   8. include() .../wp-content/plugins/elementor/core/editor/editor.php:317
PHP   9. wp_footer() .../wp-content/plugins/elementor/includes/editor-templates/editor-wrapper.php:71
PHP  10. do_action() .../wp-includes/general-template.php:3058
PHP  11. WP_Hook->do_action() .../wp-includes/plugin.php:474
PHP  12. WP_Hook->apply_filters() .../wp-includes/class-wp-hook.php:331
PHP  13. Elementor\Core\Editor\Editor->wp_footer() .../wp-includes/class-wp-hook.php:307
PHP  14. Elementor\Widgets_Manager->render_widgets_content() .../wp-content/plugins/elementor/core/editor/editor.php:821
PHP  15. SASWPElementorModule\Widgets\HowTo_Block->print_template() .../wp-content/plugins/elementor/includes/managers/widgets.php:447
PHP  16. Elementor\Modules\DevTools\Deprecation->deprecated_function() .../wp-content/plugins/elementor/includes/base/controls-stack.php:1949
PHP  17. _deprecated_function() .../wp-content/plugins/elementor/modules/dev-tools/deprecation.php:239
PHP  18. trigger_error() .../wp-includes/functions.php:5316`

Reference ticket: https://wordpress.org/support/topic/php-deprecated-_content_template-is-deprecated-since-version-2-9-0/

**Comment by Sanjeevsetu** [comment]
The issue is not fully fixed. I reopen it
