### ISSUE TITLE
Breadcrums schema: Invalid URL in field 'id' (in 'itemListElement.item')

### ISSUE THREAD

**Issue by micody** [ahmedkaludi/schema-and-structured-data-for-wp#1645]
Google is flagging Invalid URL in field 'id' (in 'itemListElement.item') in the breadcrumbs schema.
It expects a link in the last item, where it finds a string.
Is it possible that in the plugin either we remove the last itemprop="item" in the span element or convert it to the link of the respective page?

**Comment by Sanjeevsetu** [comment]
Yest got your point but the issue currently coming seems at only your site. Could you contact us at https://structured-data-for-wp.com/contact-us/
