### ISSUE TITLE
Store schema is not showing on product shop page.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1647]
Store schema is not showing on the product shop page.

ref:https://secure.helpscout.net/conversation/1835734531/235179?folderId=6370795

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
Issue does not seem to valid and user is not co-operating so I am closing it.
