### ISSUE TITLE
Yoast SEO Plugin Compatibility should be updated

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1648]
Yoast compatibility should be updated.
Ref:https://secure.helpscout.net/conversation/1838322634/235636?folderId=6370795

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
User had not setup correct schema. Now its fine
