### ISSUE TITLE
Add Fetch review from guaranteed-reviews.com functionality

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1655]
Helpscout:-
https://secure.helpscout.net/conversation/1829071541/234057?folderId=5893563

**Comment by Sanjeevsetu** [comment]
We are not getting a proper way to fetch review from this website so currently removing from the milestone

**Comment by Sanjeevsetu** [comment]
This has been pushed in v1.16
