### ISSUE TITLE
Disable Schema on Post Category is not working

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1656]
When we add any schema type and try to disable it for any specific category, it is not working.

reference help scout URL -: https://secure.helpscout.net/conversation/1840843343/236140?folderId=5893230

**Comment by shawnabc77** [comment]
wow.. no solution and close? 

i also got this issue..

**Comment by mohammed-qutubuddin** [comment]
Hi @shawnabc77 

We have added fix and it was working fine on that time, are you facing this issue?
any particular scenario?
