### ISSUE TITLE
Add option to enable or disable JSON_UNESCAPED_UNICODE

### ISSUE THREAD

**Issue by janvitos** [ahmedkaludi/schema-and-structured-data-for-wp#1659]
Hi,

I have a french media website and I noticed the special characters in the schema output are encoded in unicode (\u00e9, \u00e0, etc.)

I would like it if there was an option similar to Pretty Print Schema Markup where you could enable or disable JSON_UNESCAPED_UNICODE for the main json_encode function.

Here's an excerpt of some schema data taken from my website as an example:

`"headline":"Voici les meilleures r\u00e9ponses \u00e0 la question \u00ab&nbsp;Quelles sont les r\u00e8gles non \u00e9crites de la vie&nbsp;?&nbsp;\u00bb"`

With JSON_UNESCAPED_UNICODE enabled, it would look like this:

`"headline":"Voici les meilleures réponses à la question « Quelles sont les règles non écrites de la vie »"`

I believe this option would be useful for websites in other languages than English that use special characters.

Thanks!

**Comment by Sanjeevsetu** [comment]
hi @janvitos,

Yeah, you are right but I do not think we need an option for it. We can directly implement while encoding json-ld. I have fixed it and it will work for all user automatically.

**Comment by janvitos** [comment]
Sounds good!

Thanks.
