### ISSUE TITLE
Reviews are not fetching from Podcast platform.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1663]
The user is unable to fetch the reviews from the podcast as when clicked on fetch it shows "we are preparing" and get failed after some time.

Reference URL -: https://secure.helpscout.net/conversation/1869147707/240584?folderId=5893230

**Comment by Sanjeevsetu** [comment]
It has been solved in our latest reviews for schema. Please check and let us know if issue persist
