### ISSUE TITLE
In  review  CSV file Source URL should come on"Place ID"

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1666]
When we try to Import the review CVS file  Source URL should come in the "Place ID".

Ref:https://secure.helpscout.net/conversation/1877860621/241657?folderId=6370795

**Comment by tyhallcsu** [comment]
EXAMPLE CSV:

```
Author, Author Url, Author Image, Date, Time, Rating, Title, Text, Platform, Language
Brian S,,https://a0.muscache.com/im/pictures/user/b39a4f44-1ec5-4f2b-aa60-214244d76fb1.jpg?aki_policy=profile_x_medium,8/1/2020,,5,On The Beach Property in Galveston,Our extended family had a great time here and property is only steps away from the beach and a great view of the beach. Peaceful and quiet. Master Bedroom needs a King Size Bed.,Airbnb,
```

ALL previous reviews in the CSV will have the "Place ID" set as "On The Beach Property in Galveston" or whatever "TITLE" is for the last item in the CSV

**Comment by tyhallcsu** [comment]
How am I supposed to set the "Place ID" manually for CSV-imported reviews?
