### ISSUE TITLE
Apply filter to modify the capability

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1668]
Helpscout:-
https://secure.helpscout.net/conversation/1881567920/242227?folderId=5893563

wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php

function saswp_get_capability_by_role($role){
- $cap = 'manage_options';
+ $cap = apply_filters('saswp_default_manage_option_capability', 'manage_options' );

**Comment by ahmedkaludi** [comment]
In our schema and structured data for the wp plugin. We have a Role-Based Access feature that allows you to allow access to an Editor, Author, and so on. If it works, please let us know.

You can see the reference tutorial documentation
https://structured-data-for-wp.com/docs/article/how-to-assign-full-access-to-schema-structured-data-plugin-to-other-users/
