### ISSUE TITLE
Request for new Schema type : TouristAttraction

### ISSUE THREAD

**Issue by rakeshprabhuvj** [ahmedkaludi/schema-and-structured-data-for-wp#167]
Could you please  add schema types for tourism domain such as:
* TouristAttraction
* Place > TouristDestination
* Place > CivicStructure > PlaceOfWorship > HinduTemple
* Place > CivicStructure > PlaceOfWorship > Church
* Place > CivicStructure > PlaceOfWorship > Mosque
* Place > LandmarksOrHistoricalBuildings

**Comment by westaussie** [comment]
+1 for this Schema type :-)

Also to add to this:
Trip - http://schema.org/Trip
TouristTrip - http://schema.org/TouristTrip

This will help out sites offering tours and itineraries I think.

Scott

**Comment by Sanjeevsetu** [comment]
Tourist trip schema will be added in this ticket #289
