### ISSUE TITLE
Remove <Span> Element from itemlist schema

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1673]
Reference screenshot: https://wordpress.org/support/topic/how-to-remove-from-itemlistelement/

**Comment by MohammedAkramU7** [comment]
Another user with the same issue
https://magazine3.in/conversation/11487?folder_id=21

**Comment by Sanjeevsetu** [comment]
This issue is fixed in our latest v1.9.107 so I am closing it
