### ISSUE TITLE
Need to make functionality by default disable FAQ on all pages.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1681]
HelpScout:-
https://secure.helpscout.net/conversation/1885977082/242881?folderId=5893563

Description:-
Users want to disable FAQ on all pages.

**Comment by TimSauer94** [comment]
Seems like that broke the FAQ output for some people:
https://wordpress.org/support/topic/faq-schema-is-not-showing/
