### ISSUE TITLE
When the WP Customer Reviews plugin is not installed but after enabling the option, it overrides reivews

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1691]
Ref:https://magazine3.in/conversation/10293?folder_id=4
When the WP Customer Reviews plugin is not installed after enabling the option, it overrides the reviews.
https://prnt.sc/00kpN6DucfHy

**Comment by ajithkumar072** [comment]
This issue was fixed by support team
https://magazine3.in/conversation/10293?folder_id=4
