### ISSUE TITLE
Problem with "priceCurrency" rich result

### ISSUE THREAD

**Issue by DogMap** [ahmedkaludi/schema-and-structured-data-for-wp#1695]
Hello there,

I'm not really good in English, so sorry for that !

I'm using Schema & Structured Data for WP & AMP with Wordpress and WooCommerce to add some structured datas to my products.
I completed every fields and tested one product page with [this tool](https://search.google.com/test/rich-results).

Everything seems ok, but the only problem is the "priceCurrency" data, which is obviously not detected. (the rich results tool displays "`missing field "priceCurrency"`").

When I chose "**Currency**" in the first column in the plugin, none of the suggestions in the 2nd column matches, so I chose "**Custom field**".
And then when I write "_currency_" in the 3rd column field, I have the choice between :
- **order currency**
- **wcpay intent currency**
- **saswp product schema currency 5908**

I tried to pick up each of these choices, but none seems to work, and the rich results tool always displays "_missing field "priceCurrency"_"...

I also tried to chose "manual text" and wrote "EUR" or "€" in the 3rd column, but same problem...

Could someone tell me how to set up this "**priceCurrency**" rich result please ?

Thank you a lot !

Have a good day =)

**Comment by Sanjeevsetu** [comment]
Hi @DogMap. 

Thanks for using our plugin. Really sorry for delay in reply.

You are the only one facing this issue so could you help us by providing more information on it. Do you use or pro WooCommerce for Schema extension and How have you setup schema. Just share some screenshots?

**Comment by Sanjeevsetu** [comment]
Hi @DogMap,

We are not able to re create the issue at our end and we are closing this ticket. If you still have the issue please create the issue with more details
