### ISSUE TITLE
Option for turn off( hide) the ordered and unordered item list in FAQ

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1698]
Reference screenshot: https://prnt.sc/w09gm2LqAKsU
Reference ticket: https://wordpress.org/support/topic/how-to-hide-faq-block-numbering/

**Comment by Sasirekhamarella** [comment]
1. The option to set the heading tag as P or DIV. currently, we have the option of H1 – H6.
2.  Improvement regarding aligning any image inside the HOWTO block.
3.  Improvements regarding the UI of the Gutenberg blocks.

**Comment by Sanjeevsetu** [comment]
Option label is not relevant to context. https://prnt.sc/IClej-qdHnx2
