### ISSUE TITLE
"FAQ" and "HOW TO" blocks need improvement.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1701]
"FAQ" and "HOW TO" blocks need improvement.

1. Users can choose if they want to show the steps in a numeric Order-list or not.

2. Headings and steps should be aligned.

Ref screenshot: 
https://monosnap.com/direct/VjIiriuYcPYLb9wTQq60GWngMyukgd
https://monosnap.com/direct/jgDNmQN0ENw2T1QZxkno3N9d7YAcxJ

**Comment by ajithkumar072** [comment]
This issue was fixed pushed in version 1.9.100 update
