### ISSUE TITLE
Conflict issue with Disable Admin Notices Individually plugin (user specific issue)

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1704]
Freescout:- https://magazine3.in/conversation/14247?folder_id=21

Description:-
When the user tries to add a new schema type a white page will appear at the user end.

Console errors screenshot
https://prnt.sc/lYN8HhI0JDoe

**Comment by ajithkumar072** [comment]
for now we close this ticket. once we get response from client and let us know
