### ISSUE TITLE
Multiple video objects on same page (bonus for handling pagebreaks)

### ISSUE THREAD

**Issue by jeanmichelroy** [ahmedkaludi/schema-and-structured-data-for-wp#1705]
Looks like currently it only pulls the first video that shows up. In some WP posts there may be multiple videos especially when using pagebreaks. Would be nice if it can create entries for each video that is on the post. (bonus if you can handle pagebreaks too)

**Comment by jeanmichelroy** [comment]
Sorry for late reply, something like this one where there's a few videos but only the first one gets a VideoObject created: https://ssprod.me/blog/2021/12/24/trip-report-28-aug-2021-petite-nation-river-5-5m3-s/ ?

**Comment by jeanmichelroy** [comment]
this one as well is an example with pagebreaks where the first video seems to be grabbed and kept for all pages.  https://ssprod.me/blog/2022/05/24/trip-report-9-to-13-jul-2010-dumoine-river/

**Comment by ajithkumar072** [comment]
@jeanmichelroy Please contact us via https://structured-data-for-wp.com/contact-us/

So we can rectify the issue
