### ISSUE TITLE
Issues found after Review 2

### ISSUE THREAD

**Issue by MohammedKaludi** [ahmedkaludi/schema-and-structured-data-for-wp#171]
- [x] code added twice. https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/flexmls.php#L11

- [x] escaping missing above and below this code https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/flexmls.php#L248

- [x] why `html_entity_decode` and not `json_decode`? https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L144?

**Comment by MohammedKaludi** [comment]
- [ ] escaping is missing above and beyond https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/flexmls.php#L250

- [ ] duplicate code https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L190 and  https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L197

-[ ] escaping is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L200

- [ ] use `esc_url` at all the `wp_login_url` instances https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L193 as `wp_login_url` doesnot sanitize the url by itself

- [ ] use escaping `$data[$index][0]` https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L239

- [ ] use escaping  `$word_count` and `seconds`  https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L274

- [ ] escaping is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L342

- [ ] escaping is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L434 and https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L471

- [ ] use class exisits WooCommerce instead if is_plugin_active https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/function.php#L492

- [ ] escaping is missing above and below https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L115

- [ ] escaping is missing above and below https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L171

- [ ] remove unwanted code https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L1404

- [ ] escape the complete function https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L1424

- [ ]  escaping missing for all instances of `$schema_id` https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L1581

- [ ] url escaping is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L2664

**Comment by MohammedKaludi** [comment]
- [ ] escaping is missing above and below ` trailingslashit(get_home_url()).$type,` https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/output.php#L2967

**Comment by MohammedKaludi** [comment]
- [ ] use if `$custom_logo_id`  https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/service.php#L1757 to wrap `$custom_logo` and use `isset` to wrap `$custom_logo` 

- [ ] escaping is missing above and below https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/output/service.php#L1768

**Comment by MohammedKaludi** [comment]
- [ ] add proper wp_admin url and escape it https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/help.php#L20

- [ ] don't add CSS and js directly https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/help.php#L27 and 
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/help.php#L56

**Comment by MohammedKaludi** [comment]
- [ ] avoid adding CSS directly  https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/paywall.php#L34

- [ ] translation missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/paywall.php#L114 

- [ ] escaping required https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/paywall.php#L124

**Comment by MohammedKaludi** [comment]
- [ ] remove unused `__construct` https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L10

- [ ] escaping is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L102

- [ ] escaping missing above and below https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L141

- [ ] missing text domain https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L222

- [ ] escaping is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L322

- [ ] remove commented code https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L414

- [ ] escaping https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L523

- [ ] escaping above and below https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L585

- [ ] text doamin missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L683

- [ ] use if `$image_id` https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L831

**Comment by MohammedKaludi** [comment]
- [ ] text domain is missing https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L923

- [ ] text domain https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/view/post_specific.php#L1064

**Comment by ajeetku** [comment]
- [ ] Add pre-fix in function `item_reviewed_fields`
