### ISSUE TITLE
Need to add option in adding date format for reviews like 12 days ago

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1713]
Currently, the plugin gives date format like yyyy-mm-dd, dd-mm-yyyy, but user need to text how many days ago like 12 days ago, 1 month ago, etc.

Reference ticket -: https://magazine3.in/conversation/16535?folder_id=23

**Comment by Sanjeevsetu** [comment]
the functionality is not working and it has to be on reviews collection as well not only on single reivew
