### ISSUE TITLE
Need to update for PHP  version 8

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1718]
There is a need to update for PHP version 8 and on the wordpress.org site. Currently, on wordpress.org it is not showing.

Reference screenshot -: 
![image_2022-07-28_11-33-38](https://user-images.githubusercontent.com/78167698/181432457-663ded7f-4468-4347-a005-257edbdde948.png)

**Comment by ajithkumar072** [comment]
This issue was fixed pushed in version 1.9.100 update
