### ISSUE TITLE
Need to add compatibility with Ultimate FAQ pro plugin 

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/schema-and-structured-data-for-wp#1719]
Need to add compatibility with Ultimate FAQ pro plugin 

- [ ] Need to change the slugname cause our plugin is unable to find the ultimate faq plugin,
- [ ] add compatibility with faq ultimate faq pro plugin

**Comment by ajithkumar072** [comment]
pushed in version 1.9.100
