### ISSUE TITLE
WordPress 6.0.1 Site Down after installing "Schema & Structured Data for WP & AMP" Plugin

### ISSUE THREAD

**Issue by Fruytje** [ahmedkaludi/schema-and-structured-data-for-wp#1720]
Hello,

I've installed the "Schema & Structured Data for WP & AMP" Plugin on a WordPress site. The site went down after the installation: "There has been a critical error on this website".

I've uninstalled and deleted the Schema WordPress Plugin, the site isn't live yet.

There are about 12 Plugins active at the moment. Should I try to deactivate them all or does #anyone have advice on what to do?

Thanks a lot!

![WhatsApp Image 2022-07-28 at 08 01 27](https://user-images.githubusercontent.com/60100643/181431988-ae6f4650-0c27-496b-ac07-918f9cb3e390.jpeg)

![Screenshot 2022-07-28 at 08 06 36](https://user-images.githubusercontent.com/60100643/181432622-da45710f-12c4-46f8-ad6c-c395366e0b2a.png)

**Comment by ahmedkaludi** [comment]
@Fruytje Please contact us via https://structured-data-for-wp.com/contact-us/

So we can rectify the issue

**Comment by Fruytje** [comment]
okay thanks a lot @ahmedkaludi, will do that!

**Comment by ajithkumar072** [comment]
https://magazine3.in/conversation/23961?folder_id=4
its communitcated, not an  issues
