### ISSUE TITLE
 Not able to fetch a review for the cusrev.com

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1723]
While fetching the review for the Cusrev, there is an error after clicking on the fetch as "Keys are invalid or do not have any reviews associated with this" as the user has the 150 review renaming in his account still facing the issue.

This issue is recreated on the local, as the below screenshot is of our local.
Ref screenshot: https://prnt.sc/wByn4KoSaNXS

Ref freescout :https://magazine3.in/conversation/26713?folder_id=29

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in our latest update so I am closing it.
