### ISSUE TITLE
Plugin is not working with Elementor Pro

### ISSUE THREAD

**Issue by Jennifer7597** [ahmedkaludi/schema-and-structured-data-for-wp#1728]
Elementor Pro will not work with your plugin.  I deactivated all plugins to find the issue and it was your plugin.  I really want to use your plugin so please let me know when an update will help fix this issue.

Thanks,
Jennifer
![Screenshot 2022-08-14 144653](https://user-images.githubusercontent.com/64101433/184551609-84a93ead-6315-4bfa-8dc2-5aff1c8e0b93.jpg)

**Comment by MohammedKaludi** [comment]
Thank you @Jennifer7597 for letting us know about this issue

Please give us some time will look into it and get back to you

Also if we need any assistance regarding the version number of your WP install, version no of elementor etc, will get in touch with you

Thank you once again

**Comment by ahmedkaludi** [comment]
This github repo is for valid issues, Technical support is provided via our website. Kindly contact there so our support team can help you debug and solve this.
