### ISSUE TITLE
Custom attribute for the products page

### ISSUE THREAD

**Issue by thxnlo** [ahmedkaludi/schema-and-structured-data-for-wp#1730]
Hello, 
I want to know if there's feature to add something like this. We could add custom things like Category, Android, Type, and more.

![image](https://user-images.githubusercontent.com/106380871/186197346-aff1131a-c6fd-470f-bb74-998ad3f62429.png)

Thanks
Thoufeeq

**Comment by ahmedkaludi** [comment]
Yes, you can do that, but you need to specifically to the team on https://structured-data-for-wp.com/contact-us/
