### ISSUE TITLE
Fatal Error only for login users while using Event Schema Extension (User Specific) 

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/schema-and-structured-data-for-wp#1738]
The fatal error appears when the user activates the Event Schema extension, it appears only for the Single Event page and login users, not for logout users.
Reference Screenshot: https://prnt.sc/CUtcfVqURPbd
Trello Card: https://trello.com/c/Og0KP9cK/159-67-keywan-rezaei-ravi
Free scout URL: https://magazine3.in/conversation/24585?folder_id=19

**Comment by Sanjeevsetu** [comment]
I can not see any commit here. If it is fixed on pro than we must write comment here.
