### ISSUE TITLE
Small Update Request.

### ISSUE THREAD

**Issue by hmimthiaz** [ahmedkaludi/schema-and-structured-data-for-wp#1739]
Can you please update this in your function.

`function saswp_get_capability_by_role($role)`

`$cap = 'manage_options';`

to 

`$cap = apply_filters('saswp_default_manage_option_capability', 'manage_options' );`

By this we can enable this plugin with custom capability.

**Comment by ahmedkaludi** [comment]
@hmimthiaz what's the use-case and the purpose behind it?

**Comment by hmimthiaz** [comment]
we can add a specific capability and assign to users who does not have manage_options cap.

In our case we have seo team who does not have cap manage_options but we want to give access to the plugin options.

So we kind of use this hack.

```
        add_filter('saswp_default_manage_option_capability', function (){
            return 'manage_saswp_options';
        });

```
