### ISSUE TITLE
Modify schema output button not working when we use Forminator plugin

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1745]
Reference screenshots:
https://prnt.sc/jpz9KX9S-99z
https://prnt.sc/hTlNKNqhDvhe

Reference ticket: https://wordpress.org/support/topic/button-modify-schema-output/

**Comment by Sanjeevsetu** [comment]
Function must has a prefix.
