### ISSUE TITLE
I get this error after the last update

### ISSUE THREAD

**Issue by Nayakaan** [ahmedkaludi/schema-and-structured-data-for-wp#1748]
Fatal error: Uncaught Error: Undefined constant "AUTH_COOKIE" in D:\xampp\htdocs\website\wp-includes\pluggable.php:931 Stack trace: #0 D:\xampp\htdocs\website\wp-includes\pluggable.php(694): wp_parse_auth_cookie(false, '') #1 D:\xampp\htdocs\website\wp-includes\class-wp-hook.php(307): wp_validate_auth_cookie(false) #2 D:\xampp\htdocs\website\wp-includes\plugin.php(191): WP_Hook->apply_filters(false, Array) #3 D:\xampp\htdocs\website\wp-includes\user.php(3583): apply_filters('determine_curre...', false) #4 D:\xampp\htdocs\website\wp-includes\pluggable.php(70): _wp_get_current_user() #5 D:\xampp\htdocs\website\wp-includes\user.php(628): wp_get_current_user() #6 D:\xampp\htdocs\website\wp-content\plugins\schema-and-structured-data-for-wp\admin_section\common-function.php(1777): get_current_user_id() #7 D:\xampp\htdocs\website\wp-content\plugins\schema-and-structured-data-for-wp\admin_section\common-function.php(1829): saswp_default_settings_array() #8 D:\xampp\htdocs\website\wp-content\plugins\schema-and-structured-data-for-wp\admin_section\common-function.php(4189): saswp_defaultSettings() #9 D:\xampp\htdocs\website\wp-content\plugins\schema-and-structured-data-for-wp\admin_section\add-schema\add_new.php(27): saswp_t_string('Schema & Struct...') #10 D:\xampp\htdocs\website\wp-content\plugins\schema-and-structured-data-for-wp\structured-data-for-wp.php(89): require_once('D:\\xampp\\htdocs...') #11 D:\xampp\htdocs\website\wp-settings.php(373): include_once('D:\\xampp\\htdocs...') #12 D:\xampp\htdocs\website\wp-config.php(103): require_once('D:\\xampp\\htdocs...') #13 D:\xampp\htdocs\website\wp-load.php(50): require_once('D:\\xampp\\htdocs...') #14 D:\xampp\htdocs\website\wp-admin\admin.php(34): require_once('D:\\xampp\\htdocs...') #15 D:\xampp\htdocs\website\wp-admin\network\admin.php(13): require_once('D:\\xampp\\htdocs...') #16 D:\xampp\htdocs\website\wp-admin\network\plugins.php(11): require_once('D:\\xampp\\htdocs...') #17 {main} thrown in D:\xampp\htdocs\website\wp-includes\pluggable.php on line 931

**Comment by Sanjeevsetu** [comment]
Hi @Nayakaan,

This issue has been fixed in version 1.9.101.1. Please update to that and let us know?
