### ISSUE TITLE
https://schema.org/Publisher should be https://schema.org/publisher

### ISSUE THREAD

**Issue by dimon00** [ahmedkaludi/schema-and-structured-data-for-wp#175]
https://schema.org/Publisher gives 404 where  https://schema.org/publisher should be the right url.

**Comment by dimon00** [comment]
Similarly http://schema.org/Image should be http://schema.org/image

(I guess there are others occurrences) .

**Comment by Sanjeevsetu** [comment]
can you clarify this?. Google automatically converts capital letter to small while crawling. you can see in structured-data testing-tool.

**Comment by dimon00** [comment]
Formally it is not correct.
Google converts it in it testing tool but other search engines don't. Like yandex:
https://webmaster.yandex.com/tools/microtest/
which shows it as an error.
Personally I would prefer to have the correct schema url, just to be safe.

**Comment by Sanjeevsetu** [comment]
Yeah, You are right. We will make changes.

Thanks for the support
