### ISSUE TITLE
Video object schema issues in GSC after the update

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1750]
https://wordpress.org/support/topic/video-schema-issue-2/
https://wordpress.org/support/topic/video-object-error-on-pages-with-youtube-embeds/
https://wordpress.org/support/topic/video-schema-issue/
https://wordpress.org/support/topic/post-format-video-3/

**Comment by sajandara** [comment]
https://magazine3.in/conversation/51766?folder_id=27
Same issue is faced by the user

**Comment by Sdaud1950** [comment]
Same issue with this user. https://magazine3.in/conversation/51620?folder_id=29

**Comment by Sdaud1950** [comment]
Same issue with this user https://magazine3.in/conversation/53187?folder_id=29

**Comment by 77naveenop** [comment]
The user is facing an issue with data fetching in the video object schema, in the earlier version it was working fine, and from the recent version i.e. 1.9.101, data is not fetching from the post/page.

Reference user -:  https://magazine3.in/conversation/51791?folder_id=23
