### ISSUE TITLE
While activating the Schema plugin, there is a fatal error

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1751]
While activating the Schema plugin, there is a fatal error. We have two users with the same issue.

Ref screenshot. https://prnt.sc/zwj8-TO3_ucy 

1. Ref freescout .  https://magazine3.in/conversation/52085?folder_id=29
2. Ref Freescout .https://magazine3.in/conversation/52579?folder_id=29

**Comment by warwickandersonza** [comment]
If it helps, we are also seeing this error being triggered by wp-content/plugins/schema-and-strcutred-data-for-wp/view/schema_type.php, lines 1234, 1317, and 1318.

**Comment by sajandara** [comment]
https://magazine3.in/conversation/52705?folder_id=27

User is facing the same issue.
