### ISSUE TITLE
Need to add additional fields in Article Schema

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/schema-and-structured-data-for-wp#1752]
Ref ticket:- https://magazine3.in/conversation/51011?folder_id=11
Need to add following fields in Article schema 

honorificSuffix 
alumniOf
knowsAbout
reviewedBy

**Comment by MohammedAkramU7** [comment]
Ref ticket:-https://magazine3.in/conversation/53071?folder_id=21
Another user wants the above fields in the article schema.
