### ISSUE TITLE
Getting PHP error messages after the update

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1756]
Error notice: 

`AH01071: Got error ‘PHP message: PHP Warning: Trying to access array offset on value of type null in /…./wp-content/plugins/schema-and-structured-data-for-wp/core/3rd-party/youtube.php on line 25PHP message: PHP Warning: Trying to access array offset on value of type null in /…./wp-content/plugins/schema-and-structured-data-for-wp/core/3rd-party/youtube.php on line 25PHP message: PHP Warning: Trying to access array offset on value of type null in /…./wp-content/plugins/schema-and-structured-data-for-wp/core/3rd-party/youtube.php on line 25PHP message: PHP Warning: Undefined array key “thumbnail_url” in /…./wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 3634PHP message: PHP Warning: Undefined array key “thumbnail_url” in /…./wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 3635’`

Reference tickets:
https://wordpress.org/support/topic/video-schema-issue/
https://wordpress.org/support/topic/undefined-array-keys-2/

**Comment by ravindra193** [comment]
can you give more details please like screenshot of error because I checked not fetching like issue so..

**Comment by sajandara** [comment]
The user is facing the same issue.
https://magazine3.in/conversation/56144?folder_id=27
