### ISSUE TITLE
There is an error while adding the productreview.com.au reviews.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1757]
While adding the productreview.com.au reviews is an error as "Keys are invalid or does not have any reviews associated to this"

Ref screenshot.    https://prnt.sc/momLDfz2M_QA

Ref Ticket .https://magazine3.in/conversation/53345?folder_id=29

**Comment by Sanjeevsetu** [comment]
Issue was in our server files. We have fixed there

**Comment by ravindra193** [comment]
hi 

productreview.com.au from import reviews resolved, code comiinted in pro plugin ( reviews-for-schema-master ) and 
label chnaged "Business Slug"
