### ISSUE TITLE
Missing fields in the video object schema.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1758]
Missing fields in the video object schema.

- Missing field "description"
- Missing field "uploadDate"

Ref screenshot: https://prnt.sc/Nyl0rKPtvYUr

Ref ticket: https://magazine3.in/conversation/51766?folder_id=27
https://magazine3.in/conversation/57162?folder_id=27

**Comment by ankit644** [comment]
https://magazine3.in/conversation/57037?folder_id=11
This use is also facing the same issue.

**Comment by Sdaud1950** [comment]
Same issue with this user .. https://magazine3.in/conversation/58651?folder_id=29
