### ISSUE TITLE
The option "Business Type" under local business schema type is not visible anymore.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1766]
The option "Business Type" under Local Business Schema Type is not visible anymore.

Ref Ticket: https://magazine3.in/conversation/59804?folder_id=27

Ref screenshot: https://prnt.sc/_hiQ_HWWqseg

**Comment by Sasirekhamarella** [comment]
Another user facing the same: https://wordpress.org/support/topic/cannot-setup-schema-for-local-business/
