### ISSUE TITLE
FAQ / How To schema

### ISSUE THREAD

**Issue by michaelnorthern** [ahmedkaludi/schema-and-structured-data-for-wp#177]
Please add FAQ / Q&A, How To shema. 

Here's more information on why this is important:  https://searchengineland.com/google-confirms-new-faqs-qa-and-how-tos-for-search-results-snippets-303116

Here's a clarification: https://www.seroundtable.com/google-q-a-page-structured-data-faqs-26772.html

**Comment by Sanjeevsetu** [comment]
Hi @michaelnorthern,

We have already added Q&A compatibility with this plugin https://wordpress.org/plugins/dw-question-answer/.

Regarding FAQ and How To. Which plugin are you using to list them. Can you tell us so that we can make compatibility for them.



Regarding
