### ISSUE TITLE
While using the YouTube video, there is an issue with the schema and it is found in the Query Monitor plugin.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1771]
While adding the YouTube video, there is an error with the schema plugin. The error is found in the Query Monitor plugin. I have added the reference screenshot of the error below.

Ref screenshot. https://prnt.sc/Tq1lr1Rnv9wA

Ref ticket. https://magazine3.in/conversation/62518?folder_id=29

**Comment by Sdaud1950** [comment]
Same issue with this user .https://magazine3.in/conversation/68617?folder_id=29

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/cannot-parse-supplied-iri-2/
