### ISSUE TITLE
Getting error notice when embeddeding a Vimeo/Youtube video 

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1784]
`Notice: Undefined index: query in /home/customer/www/garage3.magazine3.com/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 3653`

Reference screenshot: https://prnt.sc/Y8KVPR9tOQiR
Reference garage link: https://garage3.magazine3.com/11/16/testing/1691

Reference ticket: https://wordpress.org/support/topic/error-message-on-vimeo-embed/

**Comment by Sdaud1950** [comment]
same issue with this user. ; https://magazine3.in/conversation/68934?folder_id=29
