### ISSUE TITLE
FAQs are not shown in the classic editor front end.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1785]
Ref ticket:- https://magazine3.in/conversation/66884?folder_id=21

Description:- 
User add the FAQ schema but it not reflected in front end.

**Comment by ravindra193** [comment]
I did checked it is working fine. it reflected in front end.

**Comment by ravindra193** [comment]
waiting for user reply
