### ISSUE TITLE
warning: Missing "review" field.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#179]
https://costume-medicale.ro/produs/bluza-imprimata-fluturi-mici/

https://secure.helpscout.net/conversation/807200750/60529/
 Just a warning but its urgent requirement from user fix it as soon as possible.

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/809888032/60943?folderId=2632030

He is also facing the same issue.
