### ISSUE TITLE
Reviews pro API key Activate button is not visible.

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/schema-and-structured-data-for-wp#1797]
Ref ticket: https://magazine3.in/conversation/74682?folder_id=21
Ref screenshot: https://prnt.sc/V8f20FkWHcYf

Class prefix is mission that's why issue is occurring.

**Comment by ravindra193** [comment]
https://user-images.githubusercontent.com/45510412/205551473-6fb8a65d-32de-401b-b18e-8dac97553258.jpg

I can see button and also working fine. can you please  check again
