### ISSUE TITLE
VideoObject schema is getting added even if only the "href" link is present.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1802]
Bug Name: VideoObject schema is getting added even if only the "href" link is present.
Area: Schema Validator/page source
Version Number: 1.9.106
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/72202?folder_id=27

Description: VideoObject schema is being added even if only the Href link is present

Reference screenshot: https://prnt.sc/uC_V1hy_HoP7

Steps to recreate the issue:

Download and activate the plugin Schema & Structured Data for WP & AMP
Add a href link on the post/page and validate it on the schema validator

**Comment by 77naveenop** [comment]
User with the same issue -: https://magazine3.in/conversation/77373?folder_id=23

**Comment by sajandara** [comment]
The user is facing the same issue.
https://magazine3.in/conversation/81761?folder_id=27
