### ISSUE TITLE
Product schema conflicts with the FAQ in the post section.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1803]
Ref ticket:- https://magazine3.in/conversation/78510?folder_id=21

Description:-
The user used a product schema and FAQ schema, but the post section FAQ showed blank.

Issue video:-
https://monosnap.com/file/64VHuzOswYjiW3YC3wHejheqBoIXxN

**Comment by ravindra193** [comment]
https://user-images.githubusercontent.com/45510412/209539025-b7faabc5-99cb-4cf1-a98e-0c5fda6bc2fb.png

it is Disable button issue after unable this we can see
