### ISSUE TITLE
Add new functionality to fetch the author name from the taxonomy.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1839]
Add new functionality to fetch the author name from the taxonomy.

Ref ticket: https://magazine3.in/conversation/91282?folder_id=27

**Comment by sajandara** [comment]
The issue is occurring again.
https://magazine3.in/conversation/91282?folder_id=27

**Comment by Sanjeevsetu** [comment]
There was issue in settings. It is fixed.
