### ISSUE TITLE
If the FAQ block is not available on the post and the FAQ schema type is targeted to the posts, an error appears in GSC

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1842]
If the FAQ block is not available on the post and the FAQ schema type is targeted to the posts, an error appears in GSC
Missing Feild "mainEntity"
Ref screenshot: https://monosnap.com/direct/JoXJ6qKnb2C6Q1MZBXcQ5s0mRVyzDF

Ref ticket: https://magazine3.in/conversation/93720?folder_id=27

**Comment by sajandara** [comment]
Another user is facing the same issue: 
https://magazine3.in/conversation/99436?folder_id=27

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in this ticket. https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1681
