### ISSUE TITLE
When we add reviews for the services schema, "missing reviewed item name" and "item does not support reviews"

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1843]
Ref ticket:- https://magazine3.in/conversation/93791?folder_id=21

Description:-
Even if the review name is already set, critical errors appear when we add the reviews collection to the services schema. 

Issue screenshot:-
https://prnt.sc/tmXzOCrdpwUh

**Comment by sajandara** [comment]
Another user is facing the same issue.
https://magazine3.in/conversation/138496?folder_id=27

**Comment by Sanjeevsetu** [comment]
@sajandara 

That client issue is due to wrong schema setup. Please setup it again
