### ISSUE TITLE
Clicking on reviews redirecting to site can't reached 

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1853]
When adding google reviews and showing them on the frontend, after clicking on any of the reviews, it is redirecting to the page saying the site can't be reached.

Reference ticket -: https://magazine3.in/conversation/102823?folder_id=23

Reference URL -: https://uq6eb4fdr0-staging.onrocket.site/lp-test

**Comment by ravindra193** [comment]
it is working fine i have checked

**Comment by Sanjeevsetu** [comment]
This ticket is similar to #1876 so closing it.
