### ISSUE TITLE
"User ID Missing" issue when fetching the reviews.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1855]
Ref ticket:- https://magazine3.in/conversation/91698?folder_id=21

Description:-
When we try to fetch the review from a different platform, a message appears that the user ID is missing.

Issue screenshots:
https://prnt.sc/-VMvsakjsqyr
https://prnt.sc/gEftyJBFfDir
https://prnt.sc/ndUhjsPCRgxE
https://prnt.sc/DV0qwmdKR735

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in our latest reviews for schema pro extension.
