### ISSUE TITLE
User want to user profile custom filed in schema

### ISSUE THREAD

**Issue by ankit644** [ahmedkaludi/schema-and-structured-data-for-wp#1865]
Ref ticket: https://magazine3.in/conversation/51011?folder_id=11

**Comment by zmunetsi** [comment]
Hi
I am getting the following error after the recent update:
Fatal error: Uncaught Error: Object of class WP_Term could not be converted to string.

How do I resolve this?

**Comment by iasgharalikhan** [comment]
Experiencing downtime after the update.
