### ISSUE TITLE
Unable to fetch reviews from hipages

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#1870]
Unable to fetch the reviews from hipages.

Ref screenshot: https://prnt.sc/vwZ_YXXxFbGu

Ref ticket: https://magazine3.in/conversation/104171?folder_id=27

**Comment by Sanjeevsetu** [comment]
This is duplicate ticket of https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1972 so I am closing it
