### ISSUE TITLE
Version 1.10.1 Recipe schema type setting recipeIngredient null

### ISSUE THREAD

**Issue by Serranosoft** [ahmedkaludi/schema-and-structured-data-for-wp#1873]
I just updated to version 1.10.1 and all my recipes are getting recipeIngredient to null

**Comment by lopesgon** [comment]
Don't know if it is related to my issue but recipeIngredients is crashing application completely due to miss usage of strip_tags with an array() instead of String.

Don't know exactly if it is the same cause as yours but I opened a Pull Request to fix at least the usage of strip_tags.

**Comment by Sanjeevsetu** [comment]
Hi @Serranosoft . This issue is similar to https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1859. I have already fixed it there before your pull request so going to close your pull request as well.

**Comment by lopesgon** [comment]
Hello @Sanjeevsetu,

I think my pull request is still valid and not related to this issue.

I can guarantee that the plugin doesn't work with Recipe schema due to the current usage of strip_tags passing an array as argument instead of a string (see output/markup.php).

**Comment by Sanjeevsetu** [comment]
Hi @lopesgon 

Please look at the function saswp_explod_by_semicolon inside function.php. I have used wp_strip_all_tags inside that for every string set so no need to use at other place. If you still have issue with latest update??? We will try to re create at our end just confirm it.

**Comment by lopesgon** [comment]
Hello @Sanjeevsetu,

I confirm latest update fixed the issue.

Thanks a lot !

**Comment by Sanjeevsetu** [comment]
Hi @lopesgon 

Thanks for the confirmation. Happy to help you.
