### ISSUE TITLE
Need to add full article body in schema description or reviewbody

### ISSUE THREAD

**Issue by ms-hasan** [ahmedkaludi/schema-and-structured-data-for-wp#188]
Ref: https://secure.helpscout.net/conversation/810891294/61042?folderId=2614130

URL of the full article body in the schema.
https://www.clubalfa.it/58559-ferrari-f8-tributo-foto-video-dal-vivo

https://urbanpost.it/cecilia-rodriguez-instagram-le-foto-in-costume-alle-maldive-fanno-impazzire-i-fan/

**Comment by Sanjeevsetu** [comment]
one more ref : https://secure.helpscout.net/conversation/875865879/70267?folderId=3004564

**Comment by Sanjeevsetu** [comment]
We have fixed this issue in ticket https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/363
