### ISSUE TITLE
Issues with rank math compatibilty

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/schema-and-structured-data-for-wp#1889]
Scenario:

 If we enable the rank math compatibility then getting errors: 

https://prnt.sc/ttczG1C_2s3o
https://prnt.sc/wO-mgw5G3Tma

Also, the headline is not showing correctly:: https://prnt.sc/sJxh96JOa-SC
If we disable the compatibility then only it is showing: https://prnt.sc/TJh2ZQk9utTT

Reference ticket: https://wordpress.org/support/topic/rank-math-compatibility-not-working/

**Comment by Sanjeevsetu** [comment]
It does not seem to valid issue so I am closing it

**Comment by Sanjeevsetu** [comment]
There was issue but that is different.
