### ISSUE TITLE
option to change default currency in apartment schema markup

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1890]
Ref ticket:-https://magazine3.in/conversation/119721?folder_id=21

Description:-
Property for Sale and unitCode are added automatically, but the user needs to change the option to property for ren and unitcode to another currency.

**Comment by Sanjeevsetu** [comment]
Waiting for user reply so moving next milestone

**Comment by Sanjeevsetu** [comment]
Still waiting for user reply. It does not seem to a valid issue. I am closing it for now.
