### ISSUE TITLE
Content url and Embed url are missing in video object of structured data

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#190]
Help Scout Link: https://secure.helpscout.net/conversation/811220144/61073?folderId=2770545

For using Video Object in the structured data format embed Url and content URL property need to be implemented as per structured data guidelines for video.

**Comment by Sanjeevsetu** [comment]
This ticket will be covered in https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/192
