### ISSUE TITLE
Warring is showing in the product merchant listings.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#1925]
Warring is showing in the product merchant listings.

Ref screenshot: https://prnt.sc/xSegoJ2sDiUJ 

Ref Ticket:https://magazine3.in/conversation/138612?folder_id=29

**Comment by Sasirekhamarella** [comment]
Same issue: https://wordpress.org/support/topic/how-to-add-hasmerchantreturnpolicy-and-shippingdetails/

**Comment by asheroto** [comment]
I'd like to see this as well. I'm getting an alert from Google Search Console every so often that my store doesn't have items I need.

![image](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/assets/49938263/cc2372be-9c9d-48dc-a7bd-f6de9431cef1)
