### ISSUE TITLE
Shopify Reviews are not fetching

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1944]
When we try to fetch the reviews from shopify platform, it shows Keys are invalid.

Reference ticket -: https://magazine3.in/conversation/148672?folder_id=23

**Comment by shridhamdeveloper** [comment]
Refer commit in saswp-server 

https://github.com/ahmedkaludi/saswp-server/commit/6ad2a299b06e68702eeac03f7dc310e91522272a
