### ISSUE TITLE
NewsArticle/Article Schema showing wrong featured image

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1947]
When we are adding article schema, it shows default image as featured image instead of the image added as Featured image.

reference ticket -: https://magazine3.in/conversation/149772?folder_id=23

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in ticket https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1952
