### ISSUE TITLE
Heading Tag affects List Order Type and H1 leads to <strong>

### ISSUE THREAD

**Issue by kraftner** [ahmedkaludi/schema-and-structured-data-for-wp#1960]
When choosing "Heading Tag" on a "How To" Block it has weird effects:

- Choosing "H1" actually displays a `<strong>` in the frontend
- Choosing anything else does display the heading tag in the frontend, but the same value is also written as list-style-type. So choosing e.g. h3 results in this:
```
<div class="saswp-how-to-block-section">
	<div class="saswp-how-to-block-steps">
		<ol style="list-style-type:none;">
			<li style="list-style-type: h3">
				<h3>Step</h3>
				<p class="saswp-how-to-step-text">Description</p>
			</li>
		</ol>
	</div>
	<div class="saswp-how-to-block-tools"></div>
	<div class="saswp-how-to-block-material"></div>
</div>
```

This may be related to #1959

**Comment by shridhamdeveloper** [comment]
Issue resolved in ticket number #1959
