### ISSUE TITLE
Dead Code

### ISSUE THREAD

**Issue by kraftner** [ahmedkaludi/schema-and-structured-data-for-wp#1962]
The plugin contains a lot of unused or commented out code. It's probably better to remove that completely, no?

### Examples

- This file is unused: https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/master/admin_section/tracking/class-saswp-plugin-usage-tracker.php
- https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/d2be4865c36c02b5cd9dbb6e9d547b23ab7ecc60/core/3rd-party/aqua_resizer.php#L324-L331
- https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/d2be4865c36c02b5cd9dbb6e9d547b23ab7ecc60/admin_section/common-function.php#L3185-L3188
- https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/d2be4865c36c02b5cd9dbb6e9d547b23ab7ecc60/admin_section/common-function.php#L3624-L3626

**Comment by Sanjeevsetu** [comment]
Hi @kraftner 

Thank you so much

Yes it must be removed. We will do it
