### ISSUE TITLE
Need to add compatibility with Swipe people plugin for job posting

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1966]
We need to add compatibility with Swipe people plugin.

references user -: https://magazine3.in/conversation/152293?folder_id=23

**Comment by Sanjeevsetu** [comment]
Swipe people plugin is custom made plugin user's developer and its not on wp.org or anywhere else so we should not make the compatibility.

Users all issue have already solved by us so I am closing the ticket.
