### ISSUE TITLE
PHP Warning in reveiw module

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1986]
Ref ticket:-https://magazine3.in/conversation/146342?folder_id=21

PHP Warning:  
Undefined variable $collection_review_imag in /home/burneralert2014/public_html/mygrillie.com/wp-content/plugins/schema-and-structured-data-for-wp/modules/reviews/reviews_collection.php on line 585

**Comment by Sdaud1950** [comment]
Same issue: 

https://magazine3.in/conversation/167761?folder_id=29
