### ISSUE TITLE
NewArticle schema is automatically added in homepage and categories.

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#1991]
Ref ticket:-https://magazine3.in/conversation/165889?folder_id=21

Description:-
NewArticle schema is reflected even when we exclude it from categories and the homepage.

Issue screenshot
https://prnt.sc/VqIK79CNDrTm
https://prnt.sc/N1b-bgWXvKJE

**Comment by shridhamdeveloper** [comment]
User has not set the correct placement configurations for schema, hence this issue is not valid
