### ISSUE TITLE
Need to make plugin version depending upon VIP wordpress code standard

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#1994]
There are few errors and warnings in the plugin when testing with VIP code standard and fixing them causes issue with the core plugin.

Reference user -: https://magazine3.in/conversation/167454?folder_id=23

**Comment by Sanjeevsetu** [comment]
Schema & Structured Data for WP & AMP is now fully compatible with WordPress VIP since version 1.35 or latest.
