### ISSUE TITLE
Output Buffering Interferes with WP CLI

### ISSUE THREAD

**Issue by kaelri** [ahmedkaludi/schema-and-structured-data-for-wp#2010]
When this plugin is active, output sent via the WordPress CLI (e.g. `WP_CLI::line( $string )`) is buffered—meaning, it all comes out at once at the end of the script, rather than in real-time as it executes, as (e.g.) `error_log` does. This interferes with the usage of many CLI operations.

To demonstrate this, you can save the following as a plugin:

```php
<?php

/*
Plugin Name: WP CLI Tester
*/

if ( class_exists('WP_CLI') ) {
	\WP_CLI::add_command( 'test-cli', function() {
		WP_CLI::line( "Begin…" );
		sleep(3);
		WP_CLI::line( "…end." );
	});
}
```

Then, try the registered WP CLI command:

```shell
$ wp test-cli                                           
Begin…
…end.
```

Normally, you will see the “Begin…” message, followed by a 3-second pause, and then “…end.” However, when this plugin is active, both lines are printed only after the 3-second pause completes.

With longer, more complex CLI scripts, I have found that the output never appears at all. I haven’t identified what causes that behavior; it might just be that there is some maximum length that the buffered string exceeds.

I can see that the plugin uses `ob_start` in a number of places. One solution would be to disable these when WordPress loads in a CLI context rather than a web context. For example:

```php
function saswp_wp_hook_operation(){

    // New condition:
    if ( class_exists('WP_CLI') ) { return; }
    
    ob_start('saswp_schema_markup_output_in_buffer');
    
}
```

However, I have no idea what that would do to the plugin behavior, so I’m not confident enough to submit it as a PR. I’ll just submit this for your consideration. :)

**Comment by Sanjeevsetu** [comment]
Hi @kaelri 

Thanks for the bug report and more information on it. Sure, We will look at the issue and will do what will be the best solution.
