### ISSUE TITLE
A deprecated warning is shown in the schema.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2012]
A deprecated warning is shown in the schema.

Ref ticket: https://magazine3.in/conversation/190465?folder_id=29
Ref ticket; https://magazine3.in/conversation/190685?folder_id=29

**Comment by adrianmarquez2020** [comment]
https://www.chromeexteriors.com/service-area/greenbelt-roofing/

I found this error on our website after doing a debug

Deprecated: Automatic conversion of false to array is deprecated in /xxx/xxxxx/xxxxx/chromeexteriors.com/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/service.php on line 8267

There has been a critical error on this website.

**Comment by shridhamdeveloper** [comment]
Thank you for sharing the details,
We are working on the issue, it will be fixed in next update.

**Comment by adrianmarquez2020** [comment]
> Thank you for sharing the details, We are working on the issue, it will be fixed in next update.

thank you very much, I'm paying attention
