### ISSUE TITLE
By default setting on option of selected Schema type 

### ISSUE THREAD

**Issue by Prafulcnc** [ahmedkaludi/schema-and-structured-data-for-wp#2016]
By default setting enable / disable option of selected Schema type in post or page or custom post type

**Comment by Sanjeevsetu** [comment]
Hi @Prafulcnc 

Could you explain it further??

**Comment by Sanjeevsetu** [comment]
This is not a tested issue so I closing the ticket. If you still have anything to say or get help, Please contact our support here. https://structured-data-for-wp.com/contact-us/
