### ISSUE TITLE
Add support for newer social networks on the 'sameAs' field

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2019]
Reference screenshot -: https://i.imgur.com/opE41UD.png

The following changes are needed:

myspace, jabber, yim, aim, etc. need to be removed.

x (the new name of Twitter), threads (by Meta) and mastodon need to be added.

Reference ticket -: https://magazine3.in/conversation/195192?folder_id=23

**Comment by ctomczyk** [comment]
I'd consider adding [Vibehut](https://vibehut.io/) as well.
