### ISSUE TITLE
A PHP warning is shown in the schema. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2020]
PHP Warning: Undefined array key is showing on user end .

Ref ticket: https://magazine3.in/conversation/195286?folder_id=29

**Comment by shridhamdeveloper** [comment]
Reference to ticket id
https://github.com/ahmedkaludi/event-schema-for-saswp/commit/5478d3912c7cd80a80ba5f12c4f9a0b4a24464b0
