### ISSUE TITLE
Add a feature (FAQ schema should be crawled from individual ACF fields step by step)

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#2026]
Add a feature (FAQ schema should be crawled from individual ACF fields step by step)

Ref ticket: https://magazine3.in/conversation/194514?folder_id=27

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/faq-schema-compatibility/commit/ab8289875a28e72d778822b94d1084d152f12ebd
https://github.com/ahmedkaludi/faq-schema-compatibility/commit/d50b9144b69fbc3d0ef6d5834ded6ea8d3ec7409
