### ISSUE TITLE
Need to Fix Fatal Error: Call to undefined function wp_getimagesize()

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/schema-and-structured-data-for-wp#2027]
User reported that are facing a Fatal error: Uncaught Error: Call to undefined function wp_getimagesize()
in /home/rbloggers/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 2124.

Reference Ticket: https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-undefined-function-wp_getimagesize/

**Comment by Sanjeevsetu** [comment]
Issue still there for some users so I am re opening it
