### ISSUE TITLE
PHP errors from schema pro in query monitor

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2029]
Ref ticket:-https://magazine3.in/conversation/192900?folder_id=21

Description:- 
Notice few errors in query monitor while using the Schema Pro version along with some of the pro extensions.

Issue screenshot
https://prnt.sc/APf3GEgTu2qT
https://prnt.sc/l5LYYZxMJr5z

Message appears:-
Creation of dynamic property SASWPPRO_EXTENSION_MANAGER_EDD_SL_Plugin_Updater::$beta is deprecated
wp-content/plugins/saswp-pro-extension-manager/updater/EDD_SL_Plugin_Updater.php:43
SASWPPRO_EXTENSION_MANAGER_EDD_SL_Plugin_Updater->__construct()
wp-content/plugins/saswp-pro-extension-manager/saswp-pro-extension-manager.php:1099
SASWPPROExtensionManager->plugin_updater()
wp-content/plugins/saswp-pro-extension-manager/saswp-pro-extension-manager.php:85
SASWPPROExtensionManager->manager_init()
wp-includes/class-wp-hook.php:310
do_action('init')
wp-settings.php:632

**Comment by shridhamdeveloper** [comment]
Refer below commits for solution
https://github.com/ahmedkaludi/saswp-pro-extension-manager/commit/c3afedfe2041778a14554a16a3878aedbea0a799
