### ISSUE TITLE
need to make a compatibility with Webwinkelkeur to fetch reviews

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2032]
Reed to make a compatibility with Webwinkelkeur to fetch reviews

Ref ticket: https://magazine3.in/conversation/203692?folder_id=3

**Comment by shridhamdeveloper** [comment]
Changes made in extensions related to this ticket
https://github.com/ahmedkaludi/reviews-for-schema/commit/5dfa91eb671008f506cc724fe2fdc33ff2f3a343
https://github.com/ahmedkaludi/saswp-server/commit/bf546a5ba52aeeba565987d078344ff07f3e4b26
