### ISSUE TITLE
When we modify the Artcile schema with fields, then job tittle is not showing and author is also not showing.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2033]
When we modify the Artcile schema with fields, then the manually added job title is not showing, and the full field author is also not showing, but author is showing editor.

ref screenshot of the settings: https://prnt.sc/skbs1wa1890m 

Ref ticket: https://magazine3.in/conversation/203295?folder_id=29

**Comment by Sanjeevsetu** [comment]
Issue is not valid. setup was not correctly done at user end now user is not co operating so I am closing the ticket
