### ISSUE TITLE
The issue with Graphql on the pages shows the internal server error.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2039]
The Graphql shows the internal server error on the pages.

Ref screenshoot: https://prnt.sc/vPN81RV2c6fN 

Ref ticket : https://magazine3.in/conversation/210019?folder_id=29

**Comment by mvinahorau** [comment]
Additional information about the build:
WordPress 6.3.2
PHP 7.4
![Uploading Screenshot 2023-11-06 at 15.28.45.png…]()
