### ISSUE TITLE
"@type":"Course" is Missing fields "hasCourseInstance" & "offers" (Critical Issue - Rich Results Checker)

### ISSUE THREAD

**Issue by 2StartLtd** [ahmedkaludi/schema-and-structured-data-for-wp#2042]
Hi,

While trying to add the schema type of "Course" to our pages I am currently unable to add the following missing schema fields:

- [ ] Missing field "hasCourseInstance"
- [ ] Missing field "offers"

Am I missing something or is this simply missing from the field options for "@type":"Course"?

Schema Source Links:

- [hasCourseInstance](https://schema.org/Course#:~:text=with%20the%20program.-,hasCourseInstance,-CourseInstance)
- [offers](https://schema.org/Course#:~:text=about%20a%20concept.-,offers,-Demand%C2%A0%20or%0AOffer)

**Comment by Sanjeevsetu** [comment]
Hi @2StartLtd 

Thanks for the request. Yes, We will add those properties in coming updates. Can you confirm that are you using any course plugin other than Schema & Structured Data for WP & AMP to add course contents so that we can make automation of markup.

In this case you do not have to modify schema on every course posts. Just add schema types and set placement and rest will be automated. Just confirm??

or you can contact us via https://structured-data-for-wp.com/contact-us/

**Comment by 2StartLtd** [comment]
> Hi @2StartLtd
> 
> Thanks for the request. Yes, We will add those properties in coming updates. Can you confirm that are you using any course plugin other than Schema & Structured Data for WP & AMP to add course contents so that we can make automation of markup.
> 
> In this case you do not have to modify schema on every course posts. Just add schema types and set placement and rest will be automated. Just confirm??
> 
> or you can contact us via https://structured-data-for-wp.com/contact-us/

Hi Sanjeevsetu,

In regards to Schema markup, we only use the Structured Data plugin and Yoast.
As for creating the courses, these are WooCommerce products that have been set to be courses from a schema perspective as this is all we provide.

We do use a couple of other additional WooCommerce plugins along side WooCommerce, but none that will impact Schema.

**Comment by 2StartLtd** [comment]
Hi @Sanjeevsetu 

After updating to the latest version I have noticed the new options ("hasCourseInstance" & "offers") are still not available for "@type":"Course"

I have flushed all Cache and browser caches but still just the same options available?
I am trying to set this here: **wp-admin > Structured Data > Schema Types > Edit Schema Type (Course)**

I have even tried creating a new "Course" schema type to see if that may have shown the updates, but same outcome?

Have I maybe missed something?

**Comment by Seliyu** [comment]
I have the same problem. There is no possibility to add the "Offers" field outside the instance.

It also marks another error:
Either "courseWorkload" or "courseSchedule" must be specified.

These fields also do not appear to be completed in either the individual entries or the general markup.

**Comment by MohammedAkramU7** [comment]
Another user facing same issue https://magazine3.in/conversation/226341?folder_id=21

**Comment by shridhamdeveloper** [comment]
We have fixed this issue in our latest update of version 1.27
Below are the steps 
->  Structure Data->Schema Types and select Course Schema
->  Modify the markup and select Manual from drop down
->  Click on Add Course Instance button
->  There you can see option for entering details for hasCourseInsance

Please check below screenshots for reference

![Course-2](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/assets/38998323/5dfaec88-69be-47ef-9575-4b06b6d31a90)
![course-1](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/assets/38998323/0bf9caf0-d417-4c1a-aeb6-a0f0f490975f)

**Comment by 2StartLtd** [comment]
Hi @shridhamdeveloper & @Sanjeevsetu 

I can confirm the "Manual" method of this appears to be working fine now, but would be nice to see this work on the Automatic option as well in the future.

**Comment by Sanjeevsetu** [comment]
Hi @2StartLtd

We do have automation in our pro extension. Link: https://structured-data-for-wp.com/course-schema/

You can contact us here for more details. https://structured-data-for-wp.com/contact-us/

**Comment by 77naveenop** [comment]
hi @2StartLtd , please create a ticket via https://structured-data-for-wp.com/contact-us/ and we will help you out immediately.
