### ISSUE TITLE
Course schema generated errors in rich result test

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2057]
When we are adding course schema, it shows some errors and even after adding "Offer" field, it shows error.

**Comment by Seliyu** [comment]
I have the same problem. There is no possibility to add the "Offers" field outside the "Course instance".

It also marks another error:
Either "courseWorkload" or "courseSchedule" must be specified.

These fields also do not appear to be completed in either the individual entries or the general markup.

**Comment by salonsop** [comment]
The same problem. 
There are no "HascourseInstance" and "offers" fields. Now for Google they are necessary.
