### ISSUE TITLE
Need to automate the instructions and ingrediencies from gutenberg list block 

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/schema-and-structured-data-for-wp#2066]
https://magazine3.in/conversation/233641?folder_id=3

**Comment by shridhamdeveloper** [comment]
Refer Below Commit
https://github.com/ahmedkaludi/recipe-schema-for-saswp/commit/044b6d1cfe379ef6aeb427ac349f691c3452e88b
