### ISSUE TITLE
Need to add (ProductGroup) Schema Type

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2071]
Need to add productGruop Schema Type

Ref ticket :https://magazine3.in/conversation/239769?folder_id=29

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/278514?folder_id=29

**Comment by sajandara** [comment]
A user requires the same functionality "The Product Group should be added under hasVarient"

Ref Document: https://developers.google.com/search/docs/appearance/structured-data/product-variants

Ref Ticket: https://magazine3.in/conversation/312513?folder_id=27

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/woocommerce-compatibility-for-schema/commit/f636ea1733bdf15c212e5492fcf06e4f0916a9df
