### ISSUE TITLE
Problem with DOM after filling data in the product schema

### ISSUE THREAD

**Issue by Zuablitsev-Mikhail** [ahmedkaludi/schema-and-structured-data-for-wp#2073]
Hello everyone. After the latest plugin updates, I found that when filling data in the product schema, the DOM tree is not formed correctly. The div tag is not closed before forming the next hidden elements.
This leads to the fact that the other items that come after the product schema are not available for editing, without intervening through the element inspector.
![2024-01-31_12-34](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/assets/46723526/2516623a-c9ce-4289-b915-ea91264b67ed)

A potential, but very crude solution, would be to add the following code $tabs_fields = force_balance_tags($tabs_fields);
to this file: 
plugins/schema-and-structured-data-for-wp/view/common.php:682

You can reproduce this behaviour in a traceable way:
- Create a product schema for page.
- Add multiple schemas to be displayed later.
- Edit the page. Update the information in the product schema (I filled in the fields: Name, URL, Description, Brand Name, Aggregate Rating: true, Rating: 4.7, Number of Reviews: 584623)
- After refreshing the page information, the items coming after the product will not be available when switching items.
![2024-01-31_12-35](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/assets/46723526/7f63423b-4572-4410-9955-1599a90a1ef1)
![2024-01-31_12-36](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/assets/46723526/5d498336-3381-491e-8583-e323079c517e)

Data backup:
[structuredatabackup (1).json](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/files/14109922/structuredatabackup.1.json)

P.S.
Also forgot to mention, all tests were conducted on a clean version of WP 6.4.3, plugin: 1.26.
Thanks for support!

**Comment by Sanjeevsetu** [comment]
Hi @Zuablitsev-Mikhail 

Thanks for the bug report. It seems valid bug. We have added it in our next milestone and would fix it soon.
