### ISSUE TITLE
Compatibility with WP-PostRatings

### ISSUE THREAD

**Issue by dimon00** [ahmedkaludi/schema-and-structured-data-for-wp#208]
I'd like to integrate WP-PostRatings with your plugin.
Is it possible to inject the values I get from WP-PostRatings in the JSON-LD? Maybe using a function?

Thanks

**Comment by ahmedkaludi** [comment]
Yes, this is totally possible. We will definitely make the compatibility with WP-PostRatings!

**Comment by dimon00** [comment]
If you want I have a modified version of your plugin, based on version  1.6 , which support WP-PostRatings.

**Comment by ahmedkaludi** [comment]
@dimon00 Sure, please share the code here.

**Comment by dimon00** [comment]
This is a patch against the version 1.6.
Hope it can help (next time I'm going to ask for a commit ;) )

[patch_1.zip](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/files/3123690/patch_1.zip)

**Comment by Sanjeevsetu** [comment]
Hi @dimon00 

It really helped us. We have reviewed your code and it was well implemented. We appreciate your help.

We have pushed the code here and going to release it in v1.9

Thanks
