### ISSUE TITLE
Site goes slow when we activate the review addon

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2097]
Ref ticket: https://magazine3.in/conversation/255171?folder_id=21

Description:-
When users activate the review plugin, the site goes slow. 

Here is a screenshot of the query monitor plugin.
https://monosnap.com/file/0ipLMiUtsxaJGIywFwQXTTCzvm0FDZ

**Comment by Sanjeevsetu** [comment]
This issue has been fixed and no longer exists.
