### ISSUE TITLE
Feedback from customer 

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/schema-and-structured-data-for-wp#21]
Point 1 - 8 

https://secure.helpscout.net/conversation/656722041/33422/

**Comment by ahmedkaludi** [comment]
1. Enable Sitelinks Search Box? & Enable Site Name? https://monosnap.com/file/zlIQEX8s6HbsCbPZ6Ro47ByeZHNcoL 

2. Site Type? https://monosnap.com/file/dGLoW5q3YZbmAKjSmTtt8sjEhrvgw5

3. Configuration wizard
4. Comments markup 
5. Disable Duplicate Features that Yoast SEO Offers

6. Schema type and count https://monosnap.com/file/EqgDu6PbIwh8N8NfhZXgdlI1TsNj6v
7. Hide unnessesary metaboxes https://monosnap.com/file/2bq1yFpyNV0RDcE0iuBtCzghG9RoYf

**Comment by ahmedkaludi** [comment]
**CURRENT TASKS**
- [ ]  Comments markup
