### ISSUE TITLE
Need to add a compatibility with dreams.co.uk to fetch reviews

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2102]
Ref ticket: https://magazine3.in/conversation/264118?folder_id=21

Description:-
The user wants to fetch the Dreams.co.uk reviews, but needs compatibility with our plugin.

**Comment by shridhamdeveloper** [comment]
Changes made in extensions related to this ticket
https://github.com/ahmedkaludi/reviews-for-schema/commit/ac1dcf1f4fe5271db0771bf88682bf633a91ffc1
https://github.com/ahmedkaludi/saswp-server/commit/01df2920554d4c7c655be9dc291e103421848117
