### ISSUE TITLE
PHP warning in SASWP Pro

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2104]
Ref ticket:- https://magazine3.in/conversation/268263?folder_id=21

Warnings:-
Creation of dynamic property SASWPPRO_EXTENSION_MANAGER_EDD_SL_Plugin_Updater::$beta is deprecated	
wp-content/plugins/saswp-pro-extension-manager/updater/EDD_SL_Plugin_Updater.php:43
1	Plugin: saswp-pro-extension-manager
Deprecated	Creation of dynamic property FAQ_Data_EDD_SL_Plugin_Updater::$beta is deprecated	
wp-content/plugins/faq-schema-compatibility/updater/EDD_SL_Plugin_Updater.php:42
1	Plugin: faq-schema-compatibility

PHP Warning: Attempt to read property "ID" on null in /home/***/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/service.php on line 719
https://magazine3.in/conversation/269550?folder_id=3

Here is the screenshots
https://prnt.sc/W2mV8kFcpwSS

**Comment by shridhamdeveloper** [comment]
Fixed
https://github.com/ahmedkaludi/saswp-pro-extension-manager/commit/32d9206139d77dd133a92ae9e9b41d421ea1872c
