### ISSUE TITLE
Line Breaks issue in schema using FAQ block.

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/schema-and-structured-data-for-wp#2112]
One user reached out for this concern that trying to add FAQ using gutenberg editor and facing line breaks issue . 

Reference ticket: https://wordpress.org/support/topic/line-breaks-not-getting-reflected-in-the-frontend/

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/multiple-paragraphs-line-breaks-not-supported-by-faq-block/

**Comment by sajandara** [comment]
A user is facing the same issue.
Ref ticket: https://magazine3.in/conversation/266109?folder_id=27
Ref video: https://monosnap.com/direct/kKWnVGaa1lfSznwTTEuG5O5pYpRJif
