### ISSUE TITLE
Need to add compatibility with EventPrime

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2115]
Need to make compatibility with https://wordpress.org/plugins/eventprime-event-calendar-management/ plugin as it is not collecting proper data.

Reference user -: https://magazine3.in/conversation/273292?folder_id=23

**Comment by shridhamdeveloper** [comment]
Compatibility with event prime
https://github.com/ahmedkaludi/event-schema-for-saswp/commit/b742bd38d1978a07d171310133d29ca06cd7c183
