### ISSUE TITLE
Image errors on AMP

### ISSUE THREAD

**Issue by miguelgaton** [ahmedkaludi/schema-and-structured-data-for-wp#212]
Hello,

Schemas are activated for AMP and NON AMP pages but:
– https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.hwlibre.com%2Fmartillo-de-thor%2F is OK
– https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.hwlibre.com%2Fmartillo-de-thor%2Famp%2F AMP version have 2 errors (2 missing images on article schema).

Could you help me please? You can see more info about the issue here https://wordpress.org/support/topic/image-errors-on-amp/#post-11425627

regards,

**Comment by ahmedkaludi** [comment]
Since the setup seems very normal, you shouldn't be having that error. Can you share the wp details via http://structured-data-for-wp.com/contact-us/

I'll go into it personally and figure out the fix for this bug

**Comment by miguelgaton** [comment]
Done!
