### ISSUE TITLE
Need to add an option to enable only custom schema

### ISSUE THREAD

**Issue by askcode21** [ahmedkaludi/schema-and-structured-data-for-wp#2121]
One user reached out for this concern,"Is it possible to disable global schema and only leave a custom schema types?" 

Reference ticket: https://wordpress.org/support/topic/how-to-disable-global-schema/

**Comment by yabdali** [comment]
> One user reached out for this concern,"Is it possible to disable global schema and only leave a custom schema types?"
> 
> Reference ticket: https://wordpress.org/support/topic/how-to-disable-global-schema/
Is there any guide about how to co-exist with Rank Math? I have similar challenge, I use woocommerce and it looks that things are messed up after installing Rank Math. Also, I when I try to customize the schema by adding a new property, I don't get any Rank Math related options. Like Rank Math Title or description. I don't want to enter data into two different areas as this increases the maintenance work.. Appreciate your guidance. Thanks.
