### ISSUE TITLE
Add compatibility with the plugin Joli FAQ SEO

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#2122]
Add compatibility with the plugin Joli FAQ SEO

Ref ticket: https://magazine3.in/conversation/270600?folder_id=27

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/faq-schema-compatibility/commit/00e67c21c5faff15346b0dcfb4dad5398b0a0068
