### ISSUE TITLE
Feature Request: Extending Custom Schema using variables/fields

### ISSUE THREAD

**Issue by yabdali** [ahmedkaludi/schema-and-structured-data-for-wp#2123]
Is there any plan to enable the use of variables or fields in the custom schema? For example, if we have more than one person making changing on a page which already having a custom schema, we don't want the person to change the schema. A schema for an article would (on a specific existing) page would have a variable or a field like title, author, date, photo, summary which should be updated automatically on any change to the page. Thanks for your support and efforts..

**Comment by Sanjeevsetu** [comment]
Hi @yabdali 

We had plan of this but we could not proceed further. We will make sure it would be implemented as soon as possible in future updates.

Related https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/101
