### ISSUE TITLE
Google reviews are not getting fetched.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2129]
Google reviews are not getting fetched.

Ref ticket : https://magazine3.in/conversation/53345?folder_id=29

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/286234?folder_id=29

**Comment by Sanjeevsetu** [comment]
It has been solved in reviews for schema pro extention.
