### ISSUE TITLE
Add salary range for Job Posting Schema

### ISSUE THREAD

**Issue by shridhamdeveloper** [ahmedkaludi/schema-and-structured-data-for-wp#2132]
https://magazine3.in/conversation/264433?folder_id=3

**Comment by shridhamdeveloper** [comment]
Refer Job Posting Schema for solution

https://github.com/ahmedkaludi/jobposting-schema-compatibility/commit/21aa45de7012f8e3aeace28b1bb3c56ac055bb70

**Comment by Sanjeevsetu** [comment]
It was pushed in v1.33
