### ISSUE TITLE
In the schema placement, we need to add an option for language sections.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2135]
While using the WPML plugin, we need to create an option in the schema  placement for language sections.

Ref ticket: https://magazine3.in/conversation/286445?folder_id=29

**Comment by Sanjeevsetu** [comment]
We already have this feature in pro extension. Link : https://structured-data-for-wp.com/wpml-schema-compatibility/
