### ISSUE TITLE
 Undefined offset errors

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#214]
Help Scout Link: https://secure.helpscout.net/conversation/826450897/63143/

Notice: Undefined offset: 0 in /home/izmirdet/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 1269

Notice: Undefined offset: 2 in /home/izmirdet/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 1271

Notice: Undefined offset: 1 in /home/izmirdet/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 1272

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in ticket #229
