### ISSUE TITLE
Fatal error after recent update.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2142]
technical issue description: Fatal error: Uncaught Error: Failed opening required \'/home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/schema-and-structured-data-for-wp/modules/elementor/widgets/faq-block.php\' (include_path=\'.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php\') in /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/schema-and-structured-data-for-wp/modules/elementor/class-saswp-elementor-loader.php:63 Stack trace: #0 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/schema-and-structured-data-for-wp/modules/elementor/class-saswp-elementor-loader.php(91): SASWPElementorModule\SASWP_Elementor_Loader->include_widgets_files() #1 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(324): SASWPElementorModule\SASWP_Elementor_Loader->register() #2 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #3 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/plugin.php(517): WP_Hook->do_action() #4 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/managers/widgets.php(145): do_action() #5 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/managers/widgets.php(344): Elementor\Widgets_Manager->init_widgets() #6 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/elements/container.php(336): Elementor\Widgets_Manager->get_widget_types() #7 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/base/element-base.php(1482): Elementor\Includes\Elements\Container->_get_default_child_type() #8 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/base/element-base.php(369): Elementor\Element_Base->get_child_type() #9 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/base/element-base.php(1527): Elementor\Element_Base->add_child() #10 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/includes/base/element-base.php(314): Elementor\Element_Base->init_children() #11 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/dynamic-tags/dynamic-css.php(39): Elementor\Element_Base->get_children() #12 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/post.php(178): Elementor\Core\DynamicTags\Dynamic_CSS->render_styles() #13 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/base.php(680): Elementor\Core\Files\CSS\Post->render_css() #14 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/base.php(180): Elementor\Core\Files\CSS\Base->parse_content() #15 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/base.php(131): Elementor\Core\Files\Base->update_file() #16 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/base.php(227): Elementor\Core\Files\CSS\Base->update() #17 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue() #18 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/dynamic-tags/manager.php(488): Elementor\Core\Files\CSS\Post->enqueue() #19 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(324): Elementor\Core\DynamicTags\Manager->after_enqueue_post_css() #20 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #21 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/plugin.php(517): WP_Hook->do_action() #22 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/base.php(274): do_action() #23 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/core/files/css/post.php(201): Elementor\Core\Files\CSS\Base->enqueue() #24 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor-pro/modules/theme-builder/classes/locations-manager.php(142): Elementor\Core\Files\CSS\Post->enqueue() #25 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(324): ElementorPro\Modules\ThemeBuilder\Classes\Locations_Manager->enqueue_styles() #26 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #27 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/plugin.php(517): WP_Hook->do_action() #28 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/script-loader.php(2265): do_action() #29 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts() #30 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #31 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/plugin.php(517): WP_Hook->do_action() #32 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/general-template.php(3050): do_action() #33 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/themes/hello-elementor/header.php(24): wp_head() #34 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/template.php(810): require_once(\'/home/ilcammino...\') #35 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/template.php(745): load_template() #36 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/general-template.php(48): locate_template() #37 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header() #38 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-includes/template-loader.php(106): include(\'/home/ilcammino...\') #39 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-blog-header.php(19): require_once(\'/home/ilcammino...\') #40 /home/ilcamminopedagog/stage.ilcamminopedagogico.it/index.php(17): require(\'/home/ilcammino...\') #41 {main} thrown in /home/ilcamminopedagog/stage.ilcamminopedagogico.it/wp-content/plugins/schema-and-structured-data-for-wp/modules/elementor/class-saswp-elementor-loader.php on line 63

**Comment by evilash182** [comment]
Yes, critical error on entire website when this latest update is applied.

**Comment by shridhamdeveloper** [comment]
Sorry for the inconvenience,  we have released an update that includes the fix for the error so I request you to please update the plugin to version 1.34.1 have a test on your end

**Comment by evilash182** [comment]
Working fine now, thanks.
