### ISSUE TITLE
Error after version 1.34.1

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2144]
Error Details
=============
An error of type E_ERROR was caused in line 7877 of the file
/var/www/[americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/output/class-saswp-output-service.php](http://americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/output/class-saswp-output-service.php).
Error message: Uncaught Error: Call to undefined method
WC_DateTime::gmdate() in
/var/www/[americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/output/class-saswp-output-service.php:7877](http://americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/output/class-saswp-output-service.php:7877)
Stack trace:
#0 /var/www/[americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/core/array-list/schema-properties.php(6021)](http://americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/core/array-list/schema-properties.php(6021)):
SASWP_Output_Service->saswp_woocommerce_product_details()
#1 /var/www/[americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/view/class-saswp-post-specific.php(482)](http://americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/view/class-saswp-post-specific.php(482)):
saswp_get_fields_by_schema_type()
#2 /var/www/[americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/view/class-saswp-post-specific.php(648)](http://americanoffroads.com/htdocs/wp-content/plugins/schema-and-structured-data-for-wp/view/class-saswp-post-specific.php(648)):
SASWP_Post_Specific->saswp_post_meta_box_fields()
#3 /var/www/[americanoffroads.com/htdocs/wp-admin/includes/template.php(1456)](http://americanoffroads.com/htdocs/wp-admin/includes/template.php(1456)):
SASWP_Post_Specific->saswp_post_meta_box_callback()
#4 /var/www/[americanoffroads.com/htdocs/wp-admin/edit-form-advanced.php(746)](http://americanoffroads.com/htdocs/wp-admin/edit-form-advanced.php(746)):
do_meta_boxes()
#5 /var/www/[americanoffroads.com/htdocs/wp-admin/post.php(206)](http://americanoffroads.com/htdocs/wp-admin/post.php(206)): require(‘…’)
#6 {main}
  thrown

**Comment by sajandara** [comment]
Ref ticket: https://magazine3.in/conversation/294901?folder_id=27
