### ISSUE TITLE
A fatal error is occurring in the latest update of Reviews for schema 

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#2148]
A fatal error is occurring in the latest update of Reviews for schema 

Fatal error: Uncaught Error: Cannot access offset of type string on string
in /wp-content/plugins/reviews-for-schema/admin/reviews_platform_markup.php on line 93

Plugin version: 1.34.2
Ref ticket: https://magazine3.in/conversation/296618?folder_id=27

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/reviews-for-schema/commit/10a67e145f9b6b8da9b18d68843ab984d7d04bf0
