### ISSUE TITLE
Error on tags page

### ISSUE THREAD

**Issue by AdamFartassi** [ahmedkaludi/schema-and-structured-data-for-wp#215]
Hello, 
I have some errors on AMP tags page. Not only the type of structured data isn’t specified but the link for the mainEntityOfPage is wrong.
You could check with this page : https://www.penserchanger.com/mot-clef/competences-sociales/amp on the testing tool page from Google.

Here is my settings:
The “Schema Types” page: http://oi67.tinypic.com/akhjdy.jpg
The page settings: http://oi64.tinypic.com/r7vvj4.jpg
The post settings: http://oi64.tinypic.com/4eu6b.jpg

The General settings: http://oi65.tinypic.com/51ppwo.jpg

**Comment by Sanjeevsetu** [comment]
Are you using latest version of AMP?

**Comment by Sanjeevsetu** [comment]
Hi @AdamFartassi . This issue was from our core (ampforwp) default schema. We have fixed that issue and will update in our next release. ref https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3071
