### ISSUE TITLE
Pluging causing slowness when enabled: Multiple calls for images

### ISSUE THREAD

**Issue by yabdali** [ahmedkaludi/schema-and-structured-data-for-wp#2151]
I am troubleshooting our website for issues and bottlenecks. I initially tried Code Profiler plugin and it showed that the SASWP plugin was taking about 4 seconds. The I decided to use loader.io and [tideways](https://app.tideways.io/) to do profiling and send requests to different pages. On the Woocommerce single product pages, I configured SASWP for products schema along with 12 reviews. I am getting the same issue as you can see in the screen shot. When I disabled SASWP I was getting maximum 4seconds on the single product page load. Appreciate your review and advice. 
![image](https://github.com/user-attachments/assets/f37752ab-7785-4b01-8d21-aff5ea9a7023)

**Comment by yabdali** [comment]
WordPress version 6.6 PHP FPM 8.3

**Comment by Sanjeevsetu** [comment]
Hi @yabdali 

Thanks for the details report, We will check it and get back to you on it
