### ISSUE TITLE
Need to automate the Course and Event schema added by Jackrabbit.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2163]
Need to automate the Course and Event schema added by Jackrabbit.

Ref Ticket:https://magazine3.in/conversation/285070?folder_id=29

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/course-schema-for-saswp/commit/2aa121d8d7a2e2c6613e1a34dc37fb1924b07c56
https://github.com/ahmedkaludi/course-schema-for-saswp/commit/3aa92def9bbf286ef960b06faa20f486db27fc61
https://github.com/ahmedkaludi/event-schema-for-saswp/commit/6fcb90f0bf91464444a9b2a0aa1fad38033b531b
