### ISSUE TITLE
Need to make compatibility with the WP Job Board Pro plugin.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2166]
Need to make compatibility with the WP Job Board Pro plugin.

Ref Ticket : https://magazine3.in/conversation/304229?folder_id=4

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/jobposting-schema-compatibility/commit/6e84af82cac4d7979a2e721c14efaf536aee1735
