### ISSUE TITLE
Warning message in logs [Undefined array key “@type”]

### ISSUE THREAD

**Issue by Zuablitsev-Mikhail** [ahmedkaludi/schema-and-structured-data-for-wp#2169]
Hello.
We found the following warning message in the logs: ‘PHP message: PHP Warning: PHP Warning: Undefined array key “@type” in schema-and-structured-data-for-wp/output/output.php on line 1094’

I've created a merge requester. Please have a look.
#2168

**Comment by Sanjeevsetu** [comment]
The PR has been merged into master
