### ISSUE TITLE
Need to add compatability for ACF CPT with JobPosting schema

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/schema-and-structured-data-for-wp#2174]
Need to add computability for ACF CPT with JobPosting schema

Ref ticket: https://magazine3.in/conversation/298958?folder_id=27

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/jobposting-schema-compatibility/commit/c4c93bad9d43df4e042f33de2ce12e0c3d0a810a
