### ISSUE TITLE
Yelp, reviews are not getting fetch

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2187]
Yelp, reviews are not getting fetch

https://prnt.sc/YeVk6bUsV3nv 

Ref ticket : https://magazine3.in/conversation/311185?folder_id=29

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/saswp-server/commit/8fc8e6219c57f13ace3a78f0fdf33ddcc31ce12e

**Comment by Sanjeevsetu** [comment]
It has been fixed at review scrapper server. I am closing it.
