### ISSUE TITLE
Need to add compatibility with Discout Rules plugin

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2190]
When adding discount via Discount Rules plugin in woocommerce, it is picking on regular price instead of both sale and regular price.

Reference user -:https://magazine3.in/conversation/313731?folder_id=23

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/woocommerce-compatibility-for-schema/commit/ecd419db8810e0642ed4d944073c4b30245ad494
