### ISSUE TITLE
Unable to fetch ACF field values. 

### ISSUE THREAD

**Issue by ibadullah25** [ahmedkaludi/schema-and-structured-data-for-wp#2192]
Hello,

I'm using a recipe schema and an events schema for my custom post type "Recipes" and "Events". However, I'm having trouble fetching ACF field values and mapping them to the corresponding schema fields. Please refer to the attached screenshots for more details:

Screenshot 1:
<img width="929" alt="Screenshot 2024-10-03 at 16 33 11" src="https://github.com/user-attachments/assets/7e14af9f-a79f-4ae4-b04e-547b7225fe01">

I've also tried setting up and modifying the fields manually, but I'm still encountering issues. Do I need a premium plugin to resolve this, or am I missing some configuration settings?

Screenshot 2:
<img width="1196" alt="Screenshot 2024-10-03 at 16 35 36" src="https://github.com/user-attachments/assets/6f386481-9d08-4849-94ec-3997e01347e3">

**Comment by Sanjeevsetu** [comment]
Hi @ibadullah25 

Thanks for contacting us. Could you please contact us through https://structured-data-for-wp.com/contact-us/
