### ISSUE TITLE
Need to automate the faqs data added manually in classic editor

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2193]
A user is adding FAQs manually, we have to automate the process.

Reference user -: https://magazine3.in/conversation/314277?folder_id=4

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/faq-schema-compatibility/commit/2d5853611c2175d241feb1e72234d1f637365506
