### ISSUE TITLE
Please add Schema for People or Person

### ISSUE THREAD

**Issue by impurnendu** [ahmedkaludi/schema-and-structured-data-for-wp#220]
Hi, I am building a teachers directory for Students. But Your plugin does not support Person type in the schema, please add it. Thanksss

**Comment by Sanjeevsetu** [comment]
@impurnendu  Are you using any plugin for adding the directory? can you share the details and the website link?

**Comment by Sanjeevsetu** [comment]
Hi @impurnendu . 

Can you please let us know? We are waiting for your response.

**Comment by impurnendu** [comment]
Sorry, I was out of the home. I am using this plugin- https://wordpress.org/plugins/connections/
