### ISSUE TITLE
Rankmath keyword issue with Category and Tag for WebPage schema

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2201]
Ref ticket:- https://magazine3.in/conversation/312212?folder_id=21

Description:
Plugin fetched a wrong keyword, description in category and tags in WebPage schema.

**Comment by shridhamdeveloper** [comment]
Fatal error on user end so reopening the ticket

**Comment by askcode21** [comment]
Same concern: https://wordpress.org/support/topic/plugin-not-working-after-update-version/

**Comment by Sanjeevsetu** [comment]
Issue has been fixed and released in version 1.38.1
