### ISSUE TITLE
Need to add FAQ compatibility with Elementor accordian

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2202]
When user adding an FAQ element using elementor accordian then Question and Answers are not fetching and Google Search Console showing Error for "Missing Main Entity"

Reference user -: https://magazine3.in/conversation/314277?folder_id=23

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/faq-schema-compatibility/commit/6834f1695e2228fd6df960926b911cd2e6740feb
