### ISSUE TITLE
Fatal error when adding a live YouTube video to post

### ISSUE THREAD

**Issue by AlbertoGuerreroMartin** [ahmedkaludi/schema-and-structured-data-for-wp#2205]
I'm facing an issue when adding a YouTube video block on a post. When the video is a live stream (either programmed for emission or currently live streaming), a crash occurs on `class-saswp-youtube.php`, concretely due to the usage of the video duration value (`$vinfo['duration']`), because live videos doesn't have duration, therefore the API returns a value ("P0D") that seems to be not valid to build the DateInterval (the stack trace shows `Fatal error: Uncaught Exception: Unknown or bad format`)

Can you publish an update that handles this issue? I've temporally edited the code to safe check if duration doesn't have the value that the API returns for live videos before doing anything, but I'm pretty sure this is not the best fix:
```
if (isset($vinfo['duration']) && $vinfo['duration'] != 'P0D') {
    $interval = new DateInterval($vinfo['duration']);
    $vinfo['duration_sec'] = $interval->h * 3600 + $interval->i * 60 + $interval->s;
}
```

**Comment by Sanjeevsetu** [comment]
Hi @AlbertoGuerreroMartin 

Thanks for reporting the bug. Yes, I have added this ticket in next milestone and will publish an update soon.
