### ISSUE TITLE
Unable to fetch Etsy Review

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2211]
Ref ticket: https://magazine3.in/conversation/322310?folder_id=21

Description:
We're currently unable to fetch Etsy reviews.

**Comment by shridhamdeveloper** [comment]
https://github.com/ahmedkaludi/saswp-server/commit/bb958e9dbe18490be892681055c9ed2e05fa8ecb

**Comment by Sanjeevsetu** [comment]
This issue has been fixed on reviews for schema server
