### ISSUE TITLE
Update 1.38 caused a CRITICAL ERROR on all my websites. Had to roll back and it works fine.

### ISSUE THREAD

**Issue by nit900** [ahmedkaludi/schema-and-structured-data-for-wp#2212]
So after updating I noticed my site is not working getting a critical error... further investigating and I found out that the cache plugin (any of them) will fail every time and the error is this:

Failed: php
Uncaught Error: Call to undefined function is_product_category() in
/home/u334594277/domains/247garagedoors.ca/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/class-saswp-output-service.php:407
Stack trace:
#0
/home/u334594277/domains/247garagedoors.ca/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/class-saswp-output-service.php(805):
SASWP_Output_Service->saswp_get_meta_list_value()
#1
/home/u334594277/domains/247garagedoors.ca/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php(2905):
SASWP_Output_Service->saswp_replace_with_custom_fields_value()
#2
/home/u334594277/domains/247garagedoors.ca/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/output.php(1760):
saswp_get_modified_markup()
#3
/home/u334594277/domains/247garagedoors.ca/public_html/wp-content/plugins/schema-and-structured-data-for-wp/output/function.php(336):
saswp_schema_output()
#4

And so on... For now I simply rolled back to 1.37 and it works but would love to know why

**Comment by Sanjeevsetu** [comment]
Hi @nit900

We have just released an update with fixed version 1.38.1. Now you can try it and know us if issue still there.
