### ISSUE TITLE
Primary image size was not reflected properly in Schema

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/schema-and-structured-data-for-wp#2213]
Ref: https://magazine3.in/conversation/322340?folder_id=21

Description:
Wrong primary image size was reflected in schema.

Here is the screenshot
https://prnt.sc/IFQBD_QxPOMQ
https://prnt.sc/8QDfP0GD11-a

**Comment by Sanjeevsetu** [comment]
Issue has been fixed and released in version 1.38.1
