### ISSUE TITLE
When adding multiple FAQs, the first FAQ gets overridden

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2215]
When we add FAQ question 1 and question 2, question 1 gets overridden by question 2.

Ref video https://www.loom.com/share/8c0ef8ce2c98411b8f9550d9207e7a8a

Ref Ticket: https://magazine3.in/conversation/322669?folder_id=29

**Comment by sajandara** [comment]
A user is facing the same issue: https://magazine3.in/conversation/322605?folder_id=27
