### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly. 

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/schema-and-structured-data-for-wp#2219]
Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the schema-and-structured-data-for-wp domain was triggered too early.  (This message was added in version 6.7.0.) in /home/skillzr/public_html/wp-includes/functions.php on line 6114

Ref Ticket : https://magazine3.in/conversation/326869?folder_id=29 

Ref Ticket: https://magazine3.in/conversation/326991?folder_id=29

**Comment by sajandara** [comment]
A user is facing the same error: https://magazine3.in/conversation/327053?folder_id=27

**Comment by askcode21** [comment]
same concern: https://wordpress.org/support/topic/php-notice-function-_load_textdomain_just_in_time-was-called-incorrectly-3/#post-18155769

**Comment by andy-1977** [comment]
I've got a fix for this issue, with the following code change, as below:

https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/pull/2222/commits/1474d7d497ba05d1901c8f40c3881deb5f602afb

**Comment by MohammedAkramU7** [comment]
Another user https://magazine3.in/conversation/329035?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user https://magazine3.in/conversation/326504?folder_id=21

**Comment by MohammedAkramU7** [comment]
Another user https://magazine3.in/conversation/329650?folder_id=21
