### ISSUE TITLE
Alot of debug errors 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#229]
[19-Apr-2019 10:59:14 UTC] PHP Notice: Undefined offset: 0 in /home/thecaller/public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php on line 1307

Alot of debug errors 

REF: http://structured-data-for-wp.com/forum/topic/huge-amount-of-notices-in-php-error-log/

**Comment by massayoshi** [comment]
Had to disable the plugin as well due to many errors. Looking forward to the fix.

**Comment by Sanjeevsetu** [comment]
We have fixed this issue as you can see commit. We will push an update tomorrow.

**Comment by massayoshi** [comment]
Thank you @Sanjeevsetu! I have updated the file manually so I can re-enable the plugin.
