### ISSUE TITLE
PHP errors ( wordpress version 5.1.1 )

### ISSUE THREAD

**Issue by GPLshark** [ahmedkaludi/schema-and-structured-data-for-wp#232]
In Query Monitor  gives me all these php errors: 

Notice | Undefined offset: 0 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1269 | Plugin: schema-and-structured-data-for-wp
-- | -- | -- | -- | --
Notice | Undefined offset: 2 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1271 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 1 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1272 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 0 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1273 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 0 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1303 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 2 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1305 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 1 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1306 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 0 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1307 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 0 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1318 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 2 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1320 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 1 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1321 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 0 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1322 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 1 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1324 | Plugin: schema-and-structured-data-for-wp
Notice | Undefined offset: 2 | 2 | -saswp_defaultSettings()wp-content/plugins/schema-and-structured-data-for-wp/admin_section/plugin-installer/install.php:14wp-content/plugins/schema-and-structured-data-for-wp/admin_section/common-function.php:1325 | Plugin: schema-and-structured-d

What do you think it means?

**Comment by Sanjeevsetu** [comment]
Hi @GPLshark,

Yeah, these are valid notice and for the same we have already fixed the issues here #229. We are going to push an update soon.

**Comment by GPLshark** [comment]
Yes, but I'm giving the site problems. 502 Bad Gateway. I need to keep the plugin disabled. If I activate it gives me: 502 Bad Gateway with blank page.

Thank you for your time

**Comment by Sanjeevsetu** [comment]
Till than You can replace the changes from commit and can use our plugin

**Comment by Sanjeevsetu** [comment]
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/commit/e541f766d8dfbcaf11d87b70ef00073882a9e784
