### ISSUE TITLE
Remove shortcode and share button text from schema markup description

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#250]
Because if any other plugins inserting the_content then it takes that content also, it should take it from the excerpt content.

Help Scout Link: https://secure.helpscout.net/conversation/841128982/64323?folderId=2770545

**Comment by TMsravan** [comment]
another issue: https://monosnap.com/file/v0bjYg2xiXsAyKbQu3PZqDhMan6php
