### ISSUE TITLE
Can you add support kk star rating on amp pages

### ISSUE THREAD

**Issue by civilenggnotes** [ahmedkaludi/schema-and-structured-data-for-wp#253]
Amp pages are one of the important things for better user experience, and as i blogger i need to add support a star rating in my blog. I used yet another star rating and kk star rating. But unfortunately none of these are supported in your plugin. So can you add support any of them, in next update??

**Comment by Sanjeevsetu** [comment]
Hi @civilenggnotes, We already have kk star rating support on both amp and non amp in schema. We generate schema markup on both pages either amp or non amp. just you need to enable kk star rating compatibility.

Are you talking about UI part in amp for kk star rating??

**Comment by civilenggnotes** [comment]
Sorry, i already moved to another reting plugin, which supports ratings on amp pages after doing some work.. if i face any problem here, i may move later...
