### ISSUE TITLE
AggregateRating object not filled

### ISSUE THREAD

**Issue by StSaens** [ahmedkaludi/schema-and-structured-data-for-wp#270]
As per request-thread (https://wordpress.org/support/topic/aggregaterating-object/#post-11524894) an issue created here.
The object AggregateRating is not filled automatically with aggregate data (from woocommerce) unless it is filled out by hand per individual product.

(right now I've manually fixed it on the product by filling out the fields by hand. The issue itself can be seen on the screenshot supplied in the thread on Wordpress forums.)

**Comment by Sanjeevsetu** [comment]
Hey @StSaens .

Thanks for contacting us. We will sure help you. 

This issue is stranger, We are not able to create on our side. Can you please provide us wp admin details so that we can help you. Please send us at http://structured-data-for-wp.com/contact-us/

**Comment by StSaens** [comment]
Hi. I'm willing to share whatever information you need, but I won't share
passwords. As an IT-professional myself sharing passwords is a very big
no-no.

Kind regards, Saens.

**Comment by ahmedkaludi** [comment]
Can you atleast do a teamviewer or a Skype session with us so we can atleast analyze the problem?

**Comment by ahmedkaludi** [comment]
@StSaens Can we please work on this one?

**Comment by StSaens** [comment]
Hi,
it's hard for me to be available for such a thing. Can't I supply
screenshots or logs?

Regards,
Saens

**Comment by Sanjeevsetu** [comment]
Hi @StSaens, Have you setup product schema using modify schema on post?. If yes than plz uncheck "aggregateRating" if you do not fill the rating and count. (https://prnt.sc/nq5zfr).  this should fix your issue

**Comment by StSaens** [comment]
Unchecking that box gives error: https://imgur.com/a/d0H5y8e
I've done several combinations of checks. See below. Product-page is the "post-specific schema".
Schema-type page in the plugin means in the "Schema types" window of your plugin.

Unchecking aggregateRating on the product-page and checking it on the schema-type page in the plugin gives the error: https://imgur.com/a/4IADy1e

Unchecking aggregateRating on the product-page and unchecking it on the schema-type page in the plugin gives same the error.

Checking aggregateRating on the product-page and unchecking it on the schema-type page in the plugin, but not filling out the fields on the product-page gives the error: https://imgur.com/a/d0H5y8e

Checking aggregateRating on the product-page and unchecking it on the schema-type page in the plugin, and filling out the fields on the product-page fixes the error. But this is a manual action, which shouldn't be needed.

**Comment by ahmedkaludi** [comment]
@StSaens I understand you can't share the password, can we do a quick Skype session over the call? Book my time on https://appoint.ly/s/ahmed/call

**Comment by ahmedkaludi** [comment]
@StSaens Either we have a call via https://appoint.ly/s/ahmed/call or we contact us via https://structured-data-for-wp.com/contact-us/

When we verify the bug then we will open this bug request
