### ISSUE TITLE
localbusiness setup issues

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#277]
- [ ] While selecting hair salon, It shows Menu and Serves Cuisine 

- [x] Doesn't have hasMap

- [x] need to have social feilds: 
`"sameAs" : ["https://www.facebook.com/justflaunt/",
          "https://www.instagram.com/justflauntsalon",
          "https://twitter.com/JustFlauntSalon",
          "https://plus.google.com/111249287077849341871",
          "https://in.pinterest.com/justflauntsalon/"]
`

- [x] description feild

**Comment by keshavsharma333** [comment]
https://secure.helpscout.net/conversation/892318059/72323?folderId=3044500

One more issue regarding the second point.
