### ISSUE TITLE
Basic issues

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#283]
- [x] icons should come from the plugins own directory: https://monosnap.com/file/YOZKeidInFYZ5I8aHjaeDUv6SZclup

- [x] After installation as a user, the non-AMP was un-checked: https://monosnap.com/file/YStdhvIbmes8STmOmk5EsDP4pc4GGs
It shouldn't be the case.

- [x] If the logo is not there, then it shows the publisher missing error.

**Comment by Sanjeevsetu** [comment]
Regarding:  After installation as a user, the non-AMP was un-checked: 

I checked after installing new wordpress and it remain checked for the first time installation.
