### ISSUE TITLE
Duplicate query found 

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#296]
SELECT wp_posts.*FROM wp_postsWHERE 1=1AND wp_posts.post_type = 'saswp'AND ((wp_posts.post_status = 'publish'))ORDER BY wp_posts.post_date DESC 

| 6 |

 W3TC\DbCache_Wpdb->default_query

6 calls |

 saswp_paywall_data_for_login
5 callss
as
wp_schema_output
1 call
-- | -- | -- | --

https://monosnap.com/file/6QcQMydcnFesVsbGbk85ACQmn6jYji

**Comment by Sanjeevsetu** [comment]
We have already implemented cache method to this function. This error may have come when cache was clear.
