### ISSUE TITLE
Settings sections is empty

### ISSUE THREAD

**Issue by Alexlamaravillosa** [ahmedkaludi/schema-and-structured-data-for-wp#301]
I can't see the options on the settings section:
![Captura de pantalla 2019-05-28 a las 19 38 31](https://user-images.githubusercontent.com/51132327/58499337-3797c100-8180-11e9-9c8c-6f7563728402.png)

**Comment by ahmedkaludi** [comment]
@Alexlamaravillosa can you please contact us directly on ampforwp.com/support ?

We will personally debug this issue

**Comment by ahmedkaludi** [comment]
@Alexlamaravillosa can you please contact us directly on https://structured-data-for-wp.com/contact-us/ ?

We will personally debug this issue
