### ISSUE TITLE
Add custom property

### ISSUE THREAD

**Issue by mkdizajn** [ahmedkaludi/schema-and-structured-data-for-wp#315]
Hi, 

I'd like to add custom schema on landing pages for doctors, and this one is that I need to add 

`https://schema.org/Physician`

and I guess it has to replace top `WebPage` schema and also map some child properties on that pages somehow..

Can this be doable with this plugin?

**Comment by ahmedkaludi** [comment]
can you give me more details with more practicality? 
such as URL and the data that you need on the page?

**Comment by ahmedkaludi** [comment]
@mkdizajn follow up

**Comment by mkdizajn** [comment]
Hey @ahmedkaludi 

it's simple, I'd like to have correct schema for my doctors (for each doctor I'll have separate landing page), I guessed that `https://schema.org/Physician` schema is correct to use here,, but I dont know how to implement it..

**Comment by mkdizajn** [comment]
I need standard stuff like, name, title, featured image, working hours, medical speciality etc..

**Comment by ahmedkaludi** [comment]
Currently, we don't have the Physician Schema support but we are planning to implement it via https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/334

Once we have that, you can target it on a specific page using our placement option and then  modify it according to your needs via: http://structured-data-for-wp.com/docs/article/how-to-add-custom-schema-without-writing-code-in-wordpress/

**Comment by ahmedkaludi** [comment]
Currently, You can prepare the JSON LD code and then add it to a post via "Custom Schema" option which is available below every post: https://monosnap.com/file/Stf7ISnol2emaIhccKmXLlXDPmC4AO

when the above-mentioned feature will be built in that ticket then you won't have to write a single line of code as well.

Do you think that would solve the problem for you?

**Comment by ahmedkaludi** [comment]
@mkdizajn following up on the last reply

**Comment by mkdizajn** [comment]
Hey @ahmedkaludi 

thank you for following up with this and sorry for not getting back to you earlier!

I'd rather not prepare json code manually but rather leave it to plugin to generate it automatically based on content of post. 

Ok, so great news for plans to implement it in future but I dont understand something.. 

Will I be able (when you implement it) to set in post some text for example to be doctors telephone, picture or anyother field and to have it outputted in schema for that page correctly?

**Comment by ahmedkaludi** [comment]
@mkdizajn The github issues are for valid tried and tested bugs or enhancements with clarity. 

At the current stage of the issue, I suggest you to have a quick conversation with our technical team on https://structured-data-for-wp.com/contact-us/
