### ISSUE TITLE
How to add "potentialActions" of "@type": "ReserveAction"?

### ISSUE THREAD

**Issue by atopala** [ahmedkaludi/schema-and-structured-data-for-wp#326]

**Comment by akashagrjsr** [comment]
Can you please explain the use case?

**Comment by ahmedkaludi** [comment]
@atopala Please help us understand this properly.

**Comment by ahmedkaludi** [comment]
@atopala Need more data on this please?

**Comment by ahmedkaludi** [comment]
please write to us with more details on this issue through https://structured-data-for-wp.com/contact-us/
