### ISSUE TITLE
"Structure Data For Non AMP" option should be automatically enabled if AMP is not available on the website

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#329]
Screenshot: https://monosnap.com/file/HdmekYdoSmO4fFCp56bna68P9RgwSS

Before push needs to reviewed from Ahmed Sir

**Comment by Sanjeevsetu** [comment]
This error occurs when user migrate from AMPFORWP structured data and we need to fix it in our core.

Ref ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3343
