### ISSUE TITLE
Analytics issue as ads permanence doesn't  tracked properly [Priority user]

### ISSUE THREAD

**Issue by ansaritalha** [ahmedkaludi/schema-and-structured-data-for-wp#332]
There are more than 700 pageViews still there are 0 impression and 0 clicks are showing in the Analytics section. https://monosnap.com/file/pnzWCg7xpstptxCobF1J4BUhI5qz0X

https://secure.helpscout.net/conversation/868626590/69412?folderId=1914715

**Comment by ahmedkaludi** [comment]
Issue moved to [ahmedkaludi/ads-for-wp #201](https://github.com/ahmedkaludi/ads-for-wp/issues/201) via [**ZenHub**](https://www.zenhub.com/)
