### ISSUE TITLE
Impliment MedicalBusiness Schema

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#334]
How did we missed this? It's a critical one for our users: 

- [ ] https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/153

- [ ] https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/42#issuecomment-442397662

- [ ] https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/315

**Now, we need to implement the MedicalBusiness schema properly, under LocalBusiness with all the subtypes**

CommunityHealth
Dentist
Dermatology
DietNutrition
Emergency
Geriatric
Gynecologic
MedicalClinic
Midwifery
Nursing
Obstetric
Oncologic
Optician
Optometric
Otolaryngologic
Pediatric
Pharmacy
Physician
Physiotherapy
PlasticSurgery
Podiatric
PrimaryCare
Psychiatric
PublicHealth

**Comment by Sanjeevsetu** [comment]
The reason is these all schema types are not known to google structured data testing tool

https://prnt.sc/p1kv88
