### ISSUE TITLE
The default schema generated Page (Migrated from AMPforWP) or post (Migrated from AMPforWP) 's  Target Location is showing empty by default

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#336]
Des: The default schema generated Page (Migrated from AMPforWP) or post (Migrated from AMPforWP) 's Target Location is showing empty by default 

https://monosnap.com/file/OjNLCr4coDP0WXWsHKlChRtfx745XR

 
Once it is updated then is showing 

https://monosnap.com/file/STClAybafV1Oz7kcy1PkJxVRewwtE1

**Comment by ahmedkaludi** [comment]
**There are also other problems. So, 

⚠️ I will review this personally, before closing ⚠️**

**Comment by Sanjeevsetu** [comment]
We have to change the code in core plugin (AMPFORWP). This migration code is written in core.

**Comment by Sanjeevsetu** [comment]
I have created a ticket in AMPFORWP.
Ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3343
