### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#34]
- [x] return to dashboard

- [x] logo

- [x] about and contact text

- [x] social profiles are not clickable

- [x] Where would you like to enable the schema - Select Schema

- [x] Would you like to setup Social Profiles?

- [x] General Settings settings ka padding

- [x] save should be next

- [x] quick setup and feedback box positioning

- [x] in the add new schema 'Positioning' - where would you like this to be displayed?

- [x] button css in add, or 
`    padding: 3px 10px;
    color: #0d0d0d;
    font-size: 14px;
    border: 1px solid #aaa;
    border-radius: 2px;
    background: linear-gradient(#ededed, #ffffff);`

- [x] delete icon should be trash icon

- [x] remove gap and border from conditional feilds: http://take.ms/Rt6Jt

- [x] Make sure the add new schema only appears to the user who has capability to add new post.

- [x] If there's no value then it should not display: https://monosnap.com/file/S5dds4utZzlfTd4DBM2POgI3F3CEDS

- [x] If the migration is done, then the it should have a label (Migrated from Schema plugin)

- [x] It should load last: http://take.ms/vNHxR

- [x] Need to remove the Alternative name

- [x] Organisation name is not displaying after importing

- [x] Schema type should be called MISC

- [x] AMP option Positioning after tools option 

- [x] Except dashboard all the icons should be removed

- [x] Email Mailbox is not working

- [x] Form  Should be displayed in the Help section, Help section should be called support, the support tab should be removed, The title below the form should be Frequently Asked Questions.

- [x] Breadcrumb and Archive should be moved to General  http://take.ms/YATb8

- [x] Default options should be skipped from the Schema type when we are importing
http://take.ms/OmC7g

- [x] Need to place the 3 to 4 schema type and tested it in Structure data testing tool

- [x] Array is displaying before schema output

- [x] Need to remove the default structure data logo and custom logo size options.

- [x] the logo is being displayed in the place of the image in the JSON markup
- [x] about and contact us should display the markup on their respected page.

- [ ] archive and breadcrumbs output check with validator.

- [ ] Structured data validation testing on (Homepage, Single, Page, Taxonomy, Post Type & Conditional with include and exclude)

**Comment by beingsmart3** [comment]
- [ ] Need to remove the Alternative name

- [ ] Organisation name is not displaying after importing

- [ ] Schema type should be called MISC

- [ ] AMP option Positioning after tools option 

- [ ] Except dashboard all the icons should be removed

- [ ] Email Mailbox is not working

- [ ] Form  Should be displayed in the Help section, Help section should be called support, the support tab should be removed, The title below the form should be Frequently Asked Questions.

- [ ] Breadcrumb and Archive should be moved to General  http://take.ms/YATb8

- [ ] Default options should be skipped from the Schema type when we are importing
http://take.ms/OmC7g

- [ ] Need to place the 3 to 4 schema type and tested it in Structure data testing tool

- [ ] Array is displaying before schema output

**Comment by ahmedkaludi** [comment]
- [ ] In this case, the notification should always be displayeD: http://take.ms/XBVqV - it should show instead of 'No posts found.' which should not be dismissable.
