### ISSUE TITLE
Review is appearing two times for the same review for product "Add Schema Markup in footer" option is enabled

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#341]
Screenshot: https://monosnap.com/file/9zEv3hBsRhg4IsEpEtjmmdq1tGSLwP

Ref: https://secure.helpscout.net/conversation/879345354/70733?folderId=1060556

The issue is recreated in local.

**Comment by Sanjeevsetu** [comment]
This issue is coming from AMP Woocommerce Pro extension. We have created a ticket on trello
