### ISSUE TITLE
Need to make compatibility with Calendarize It plugin

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#354]
@SayyadF commented on [Mon Jun 24 2019](https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3360)

REF:https://secure.helpscout.net/conversation/886256909/71544?folderId=3008055

**Comment by Sanjeevsetu** [comment]
We already have this compatibility. Let me know if user faces any issue after using it.
