### ISSUE TITLE
Micro data clean up is not working properly.

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/schema-and-structured-data-for-wp#359]
screenshot:  https://monosnap.com/file/KY7CZ3zuLx2zZgWPKevLhh0R0wFJfY
Ref: https://secure.helpscout.net/conversation/888773060/71859?folderId=3004564

**Comment by akashagrjsr** [comment]
One more user is facing this issue
Screenshot: https://monosnap.com/file/5GGyJb3dRjwwisGJOdvH3ZR6otrhGW
Help Scout Link: https://secure.helpscout.net/conversation/882939946/71174/
