### ISSUE TITLE
 Need to add some more field  in the product schema

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/schema-and-structured-data-for-wp#360]
REF:https://secure.helpscout.net/conversation/888757341/71857?folderId=3008055

 Need to add some more field  in the product schema :

1.Missing field "aggregateRating"
"aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.4",
    "reviewCount": "89"
  },
2.Missing field "review"
 "review": {
    "@type": "Review",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "4",
      "bestRating": "5"
    },
3.Missing product ID
  "sku": "0446310786",
  "mpn": "925872",
4.Missing field "brand"
 "brand": {
    "@type": "Thing",
    "name": "ACME"
  },

Need to add by default data.

**Comment by ahmedkaludi** [comment]
@SayyadF please correct the title.

**Comment by ahmedkaludi** [comment]
@Sanjeevsetu we need to add this in the default data, it's a great idea that we can discuss
