### ISSUE TITLE
Schema title attributes show invalid title when yoast compatibility is enabled , like this (%%title%%%page%%sep)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#364]
Help Scout Link: https://secure.helpscout.net/conversation/892727926/72377/#modal

Need To fix it urgently

**Comment by akashagrjsr** [comment]
Ref: https://secure.helpscout.net/conversation/892727926/72377/

**Comment by ahmedkaludi** [comment]
there's one more issue: https://wordpress.org/support/topic/json-headline-not-the-right/
