### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/schema-and-structured-data-for-wp#368]

**Comment by MohammedKaludi** [comment]
If the output is only post_id the use `intval()` instead of `sanitize_text_field`

https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/1.8.9/view/post_specific.php#L53

**Comment by MohammedKaludi** [comment]
`EDD_SAMPLE_ITEM_NAME` undefined Constant.  https://take.ms/ytzwo

**Comment by MohammedKaludi** [comment]
Why Empty Suffix is created and why it passed as empty?
https://take.ms/G4qWU

and https://take.ms/ORpj7j 

also escaping is missing.

**Comment by MohammedKaludi** [comment]
Credits are missing,
Merlin WP and jquery-timepicker

**Comment by MohammedKaludi** [comment]
Post id should be sanitized as post id as integer value   https://take.ms/No5en 
and escaping is also required https://take.ms/N6yBX

**Comment by MohammedKaludi** [comment]
https://take.ms/bQXpY
