### ISSUE TITLE
Need to compatibility of AMP(AMP Project Contributors ) and AMPforWP in adon mode.

### ISSUE THREAD

**Issue by Nitesh221194** [ahmedkaludi/schema-and-structured-data-for-wp#370]
**If AMP(AMP Project Contributors ) and AMPforWP activate with schema it will show a fatal error.**
-------------------------------
Fatal error: Uncaught Error: Call to undefined function ampforwp_is_non_amp() in C:\xampp\htdocs\nitesh\wordpress\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php:567 Stack trace: #0 C:\xampp\htdocs\nitesh\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\structured-data-for-wp.php(45): ampforwp_is_amp_endpoint() #1 C:\xampp\htdocs\nitesh\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\function.php(857): saswp_non_amp() #2 C:\xampp\htdocs\nitesh\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\function.php(734): saswp_global_option() #3 C:\xampp\htdocs\nitesh\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\function.php(21): saswp_remove_yoast_product_schema() #4 C:\xampp\htdocs\nitesh\wordpress\wp-includes\class-wp-hook.php(286): saswp_schema_markup_hook_on_init('') #5 C:\xampp\htdocs\nitesh\wordpress\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 C:\xampp\htdocs\nitesh\wordpress\wp-includes\pl in C:\xampp\htdocs\nitesh\wordpress\wp-content\plugins\accelerated-mobile-pages\accelerated-moblie-pages.php on line 567

**Comment by Sanjeevsetu** [comment]
This ticket has dependencies on https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3415

**Comment by Sanjeevsetu** [comment]
This issue has been fixed to its dependencies ticket in ampforwp https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3415
