### ISSUE TITLE
Undefined variable: schema in /view/post_specific.php

### ISSUE THREAD

**Issue by chrome-cgi** [ahmedkaludi/schema-and-structured-data-for-wp#376]
#### Issue description
Saving post fails when there is only one Schema Type setting.

#### Steps to reproduce the issue
1. Create a HowTo Schema Type, and delete other Schema Types.
2. Create a post with HowTo Schema Type.
3. Add some HowTo steps.
3. Save the post.
4. HowTo steps aren't saved properly. debug.log shows like this:
   ```
   PHP Notice:  Undefined variable: schema in /var/www/html/wp/wp-content/plugins/schema-and-structured-data-for-wp/view/post_specific.php on line 1310
   PHP Notice:  Trying to get property of non-object in /var/www/html/wp/wp-content/plugins/schema-and-structured-data-for-wp/view/post_specific.php on line 1310
   ```

#### Possible solution
You should add code like this around [line 1255 in /view/post_specific.php](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/c52c4043e977373a5be3679c41644589f8d385f4/view/post_specific.php#L1255):
```
$schema = $all_schema[0];
```

**Comment by Sanjeevsetu** [comment]
Hi @chrome-cgi,

Yeah, you are write, this is a valid issue. we have fixed this and will update today.
Thanks for support
