### ISSUE TITLE
Sub business type should have "LocalBusiness" type as well

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/schema-and-structured-data-for-wp#380]
sub business type should have "LocalBusiness" type as well

Ref:https://secure.helpscout.net/conversation/899784406/73291?folderId=3008055

**Comment by ahmedkaludi** [comment]
Same as https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/293

**Comment by ahmedkaludi** [comment]
do not close it, it's important
