### ISSUE TITLE
when the schema and structured is used along with the WP Recipe Maker, the image is smaller than the recommended size error should not get appeared.

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#382]
Des: when the schema and structured is used along with the WP Recipe Maker, the image is smaller than the recommended size error should not get appeared.

https://secure.helpscout.net/conversation/887482268/71694?folderId=2632028

**Comment by Sanjeevsetu** [comment]
Connected with https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/323
