### ISSUE TITLE
Not compatible with Orbital theme

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/schema-and-structured-data-for-wp#385]
This theme is adding extra schema and taking excerpt data as a header. Theme can be found at telegram group

![Screenshot (30)](https://user-images.githubusercontent.com/44563327/61119972-9065b380-a4b9-11e9-850f-57656f085f3a.png)

Ref:  https://secure.helpscout.net/conversation/897480355/72980?folderId=3081347

**Comment by zJar84** [comment]
This is the code on the footer.php of the theme:

`
<div class="site-overlay"></div>

<?php wp_footer(); ?>

</body>
</html>`

I think that is a plugin. I guess it is Yoast SEO.
