### ISSUE TITLE
String Length Error

### ISSUE THREAD

**Issue by vpjm** [ahmedkaludi/schema-and-structured-data-for-wp#393]
I have a custom post type on a client site that has some posts with very long titles. I'm using the NewsArticle schema type for this particular post type and when I test it with Google's Structured Data Testing Tool, I get an error in the "headline". The error says "String length of headline must be in range [0, 110]". Is there anyway to have an automatic character count on what the plugin pushes into the "headline" field?

**Comment by Sanjeevsetu** [comment]
We have fixed this issue in this ticket and going to push in next update. https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/396
