### ISSUE TITLE
Please kindly add type "Review"

### ISSUE THREAD

**Issue by SomeGuy2019** [ahmedkaludi/schema-and-structured-data-for-wp#407]
It would be great to add 'Thing > ReviewAction' per spec at https://schema.org/ReviewAction

I looked through issues tagged 'Enhancement' and didn't see this yet, sorry if it's a duplicate.

**Comment by ahmedkaludi** [comment]
The type schema Review is available under CreativeWork parent item,
See: 
![image](https://user-images.githubusercontent.com/16532359/62423758-62534800-b6e2-11e9-9dd8-0bb2c0f66d19.png)

Unless and until you meant the "ReviewAction" specifically?
