### ISSUE TITLE
"[POST, PAGE] Specific Schema" options don't show up in /wp-admin/post-new.php

### ISSUE THREAD

**Issue by SomeGuy2019** [ahmedkaludi/schema-and-structured-data-for-wp#409]
When creating a new post, the schema options drop down does not show up in /wp-admin/post-new.php

It only shows up after publishing the post, then when I come to edit I can setup the schema at /wp-admin/post.php?post=ID&action=edit

This behavior is duplicated with the appropriate new/edit urls for PAGES too.

I would expect to be able to setup the schema options when writing the post before publishing.

**Comment by ahmedkaludi** [comment]
Sounds great @SomeGuy2019  - I will make sure that we will make the change next time.
