### ISSUE TITLE
Google review is not working properly in AMP version

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#417]
When Google review is added through shortcode it is not showing stars in the AMP version, Instead of stars, it is showing only Google icon only.

Screenshot: https://prnt.sc/opiy7u

The issue is occurring in localhost

**Comment by sglotzer** [comment]
I do not want receive notifications from you.

I ve been unsubscribed from this thread but still receiving..
Could you exclude me?


.

**Comment by ahmedkaludi** [comment]
@sglotzer Maybe you are watching is repository, try to unwatch it.

**Comment by sglotzer** [comment]
http://prntscr.com/opmllv

**Comment by Sanjeevsetu** [comment]
This issue has been fixed in new review module
