### ISSUE TITLE
New Schema Type

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/schema-and-structured-data-for-wp#42]
Ref:   https://secure.helpscout.net/conversation/679231392/36526/

- [ ]  Rentcar 

- [x]  Service
Ref:   https://secure.helpscout.net/conversation/683120011/37171?folderId=1914712

- [x] Q&A
- [ ] How To
- [x] Event
https://secure.helpscout.net/conversation/697438906/39007?folderId=1914712

**Comment by Rkroy** [comment]
Another request for Q&A schema : 
https://secure.helpscout.net/conversation/704659272/39943?folderId=2322652

**Comment by bt-elder** [comment]
Hi, I would like to second the request for Event Schema. For me, event is a custom post type with a single event per post.

**Comment by Rkroy** [comment]
Another user for event schema type : 
https://secure.helpscout.net/conversation/771341180/54402?folderId=2322652

**Comment by ahmedkaludi** [comment]
Only event schema is pending and it'll be taken care of in #157
