### ISSUE TITLE
 SEO Ultimate Compatibility

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/schema-and-structured-data-for-wp#425]
Building Schema and structured data plugin compatible with SEO Ultimate and SEO Framework schema plugin

Ref: https://secure.helpscout.net/conversation/924674590/77895?folderId=1060556

**Comment by Sanjeevsetu** [comment]
We are currently not going to make compatibility with SEO Ultimate. The reason is, This plugin  was last updated on wp.org 3 years ago. From there many version of wordpress have come and that plugin is not compatible with wordpress latest version. We will make in future if it is up to date.
