### ISSUE TITLE
Schema Blocks Module for Gutenberg

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#436]
this feature with the fallback support
https://wordpress.org/support/topic/bug-yoast-how-to-schema-is-deleted-by-this-plugins/#post-11841163

**Comment by TMsravan** [comment]
- [ ] How to 

- [ ] FQA

- [ ] Review

- [ ]

**Comment by ahmedkaludi** [comment]
Similar to https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/348

We can discuss this one

**Comment by Sanjeevsetu** [comment]
Two How to and FAQ schema type have been added in 1.9.7 version.
