### ISSUE TITLE
Debug error

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#439]
Warning: Invalid argument supplied for foreach() in /public_html/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 1545
https://wordpress.org/support/topic/invalid-argument-supplied-for-foreach-in-structure_admin-php/
https://wordpress.org/support/topic/unparsable-structured-data-report/#post-11850910

**Comment by ArtFl-2** [comment]
The same thing happened when I was updating my plugin Admin Columns but it didn't repeat when I was updating another plugin -  WP mail SMTP. So, it probably depends on the plugin.
