### ISSUE TITLE
Compatibility code for The SEO Framework results in invalid output.

### ISSUE THREAD

**Issue by Icarleug** [ahmedkaludi/schema-and-structured-data-for-wp#452]
The compatibility code returns false which results in a `<script type="application/ld+json">[false]</script>` output block in the header.

compatibility.php
```
public function saswp_the_seo_framework_override(){  
              
   add_filter('the_seo_framework_receive_json_data', '__return_false');
}
```

Should be changed to __return_null in order to fix it.

**Comment by Sanjeevsetu** [comment]
Hi @Icarleug 

Thanks for the support. Yes you are right. We changed it
