### ISSUE TITLE
Add field in Modify Schema Output defaults to null

### ISSUE THREAD

**Issue by Icarleug** [ahmedkaludi/schema-and-structured-data-for-wp#455]
If the Add field button in Modify Schema Output is clicked, a new item row appears.
If you do not change the first drop-down-box (defaults to Name) it will not store the correct setting, but "null" instead. Selecting another value and then the correct one will save the item properly.

Since it will also read "null" but default it to Name it will be hard to spot until you analyze the scheme output.
To reproduce, add a field and update the scheme (Product in my case).

saswp_meta_list_val
`a:2:{s:32:"saswp_product_schema_description";s:12:"custom_field";s:4:"null";s:8:"blogname";}`

**Comment by Sanjeevsetu** [comment]
We did this fix in this ticket #456
