### ISSUE TITLE
Suggestion: Remove Modified Schema Output item.

### ISSUE THREAD

**Issue by Icarleug** [ahmedkaludi/schema-and-structured-data-for-wp#456]
It would be nice with a button to remove a modified schema field.
Currently there is an add button but not a remove button.

If you decide that you no longer need a field you currently need to edit post_meta saswp_meta_list_val manually.

**Comment by Sanjeevsetu** [comment]
Hey @Icarleug. 

Thanks for the support. We have added this option.
