### ISSUE TITLE
New specific schema option in tags & category section

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/schema-and-structured-data-for-wp#466]
New specific schema option in tags & category section

Ref: https://secure.helpscout.net/conversation/948344980/80399?folderId=3081347

**Comment by akashagrjsr** [comment]
Ref: https://secure.helpscout.net/conversation/1097722710/114104?folderId=2770545

We need to provide the feature to add the FAQ schema for the post category pages.

**Comment by DikshantJoshi** [comment]
Need to make an option to allow users to change the SCHEMA information in the TAG page settings
Ref: https://secure.helpscout.net/conversation/1437452041/182609?folderId=3514643

**Comment by Sanjeevsetu** [comment]
This feature has been added. Please check with our latest version 1.12
