### ISSUE TITLE
Previously set schema markups "stick" on the website by default.

### ISSUE THREAD

**Issue by bijaca** [ahmedkaludi/schema-and-structured-data-for-wp#475]
If I set say article or webpage for a  SINGLE page of my site, and then add Product markup to my woocommerce product type, then ALL of my product pages will also show webpage and article markups enabled by default, which causes like a dozen errors in the Google structured data test tool.

I also had a similar issue before where the product markup would appear on pages, but that may be because I may have enabled the product markup globally when I first installed the plugin by mistake. However, even after I deleted that markup, it would stick there. Eventually it disappeared.

I use the Fastest Cache plugin, and I did notice that if I don't delete cache/JS, then Google will find the same errors even after I disable webpage and article on product pages. But after I delete the cache, the errors no longer appear on Google's test tool. HOWEVER, the webpage and article markups continue to remain enabled by default on other pages.

Excluding it via post type doesn't seem to work either. I tried post type equal product AND post type exclude article and it didn't work. The article was still enabled by default on product pages.

Also, when I manually leave product-only enabled on a product page by modifying the schema, it still gives 3 errors: 

One of url or contentUrl must be provided.

seller -- The property seller is not recognized by Google for an object of type Product.

aggregateRating -- The aggregateRating field is recommended. Please provide a value if available.

The last one I understand as I don't have reviews and I also got it with Yoast and Rank Math. But I don't know why I'm getting the others.

**Is there anything I can do right away to fix the issue of either product markup appearing on pages or article markup appearing on products without having to manually disable them on each page, until the bugs are fixed?**

Additional errors I've noticed is that when I press the modify markup button, I see stuff like published date: -0001-11-30, or price valid until: -0001-11-30T00:00:00Z. And sometimes the article descriptions disappear, too.

Also, the defragment option seems to create yet another error, something about Corporation being invalid for Publisher. Disabling it seems to fix the error.

I love all the features of the plugin, but I think the codebase needs a bottom-up code audit and clean-up, as too many things seem broken, maybe even by a third-party.

**Comment by ahmedkaludi** [comment]
Let's discuss this and see if we can find something to do in this milestone.

**Comment by Sanjeevsetu** [comment]
Hi  @bijaca,

Thank you so much. Could you provide your urls to check the schema makrup. I have gone through your issue's list and found that most of the issues are valid and need to be address soon.
We are working on it.

**Comment by ahmedkaludi** [comment]
Defragmented schema issue will be tackled in https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/505
