### ISSUE TITLE
Uncaught exception with message 'WC_Product::get_categories is <Strong>deprecated<Strong> since version 3.0

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#481]
User is facing this error while using our schema plugin please check with below screenshot.

Screenshot: 
https://monosnap.com/file/BceiP24IRMEigWM4kcUYPOYk5qkhtX

Ref Ticket: https://secure.helpscout.net/conversation/950785618/81421?folderId=3126461#modal

**Comment by Sanjeevsetu** [comment]
This issue is in AMP WooCommerce. It shoud be moved to Trello.
