### ISSUE TITLE
Image size smaller than recommended size

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#485]
Image size smaller than the recommended size

Facing this waring and in the testing tool no warning has getting displayed but in the google search console, URLs are not getting crawled throwing this warning.

We need to to do an experiment as:

Changing the order of the images in the structured data array the images, as the featured images to be placed first and then after the content images.

Please discuss this issue with Ahmed sir.

**Comment by Rkroy** [comment]
User facing image size warning in the structured data.
Ref: https://secure.helpscout.net/conversation/958040013/83385?folderId=2322651

**Comment by akashagrjsr** [comment]
One more user is facing the same issue:
Ref: https://secure.helpscout.net/conversation/892727926/72377?folderId=1060554

**Comment by ahmedkaludi** [comment]
Another Issue: https://wordpress.org/support/topic/image-size-smaller-than-recommended-size-3/

**Comment by Rkroy** [comment]
Another user: https://secure.helpscout.net/conversation/961390196/84954?folderId=2322651
