### ISSUE TITLE
Review schema and webpage given an error "Thing is not a known valid target type for the itemReviewed property."

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/schema-and-structured-data-for-wp#488]
According to google format, we need to change in review schema 

Tested url:

https://www.wishterrain.com/alone-status-to-express-your-loneliness/

REF:https://secure.helpscout.net/conversation/958203692/83454?folderId=3008055
https://secure.helpscout.net/conversation/959679362/84021?folderId=3008055

**Comment by TMsravan** [comment]
Another user facing the same issue: https://secure.helpscout.net/conversation/960551199/84521?folderId=2632030
