### ISSUE TITLE
Review CSS are not loading based on condition

### ISSUE THREAD

**Issue by RajuJeelaga** [ahmedkaludi/schema-and-structured-data-for-wp#492]
Review CSS are not loading
1). CSS not loading screenshot
https://monosnap.com/file/gwH9GWpmioxCQX2lnhYoCGKB2rVxTn
2) CSS loading Screenshot
https://monosnap.com/file/0Y6dkkEZ0jRHiFc6vTUwzOTFUiHhiQ

**Comment by akashagrjsr** [comment]
One more user is facing the same  issue:
https://secure.helpscout.net/conversation/959551762/83963?folderId=1060554

Screenshot: https://monosnap.com/file/6pgqp8eTqSnVgCp9MMWfU24NS2kt7f
