### ISSUE TITLE
In sructure data Review  does not  display properly 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/schema-and-structured-data-for-wp#504]
When the shortcode is added of reviews in any post then it does not display properly, Its not display as par style.

See this screenshot:
https://monosnap.com/file/1MnldukIHH7snBEhIsaUyf3A4W7hVZ

REF:https://secure.helpscout.net/conversation/959551762/83963?folderId=3008055

**Comment by Sanjeevsetu** [comment]
It is fixed in latest version. Please update to latest v1.9.8 and let us know.

**Comment by SayyadF** [comment]
Issue fixed in our latest update and its working properly now.
