### ISSUE TITLE
ItemList and CollectionPage schema are not being added on custom texonomy page

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#521]
As per user requirement  an option to add itemlist and collectionpage schema for custom taxonomy types just like category schema.

Ref Ticket:
https://secure.helpscout.net/conversation/967233456/86358?folderId=3126461

**Comment by ranavaqar** [comment]
**Example:** 

_Default Category Page_

[https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.studypk.com%2Fcategory%2Fblog%2F](url)

_Custom Taxanomy Page_

[https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.studypk.com%2Fmerit-lists-by-course%2Fdoctor-of-physical-therapy-dpt%2F](url)
