### ISSUE TITLE
WP_Postratings not visible anymore

### ISSUE THREAD

**Issue by dimon00** [ahmedkaludi/schema-and-structured-data-for-wp#528]
I'm using version 1.9.10  and and have the WP-PostRatings option flagged but the AggregateRating is not visible anymore.

**Comment by dimon00** [comment]
I made a rollback, a version at a time, and the last working is 1.9.7

**Comment by Sanjeevsetu** [comment]
Which type of schema are you using.? Actually Google has made some new changes regarding this. https://developers.google.com/search/docs/data-types/review-snippet. 

Now, Article, NewsArticle, BlogPost, TechArticle etc.. schema will no longer have any aggregateRating.

**Comment by dimon00** [comment]
Probably my post was confusing.
If I test the same page:
https://www.trovafrasi.com/citazioni/frasi-filosofia/
with 
https://search.google.com/structured-data/testing-tool/u/0/
(or in the page source)
I can see the aggregaterating only with the plugin 1.9.7.
With later versions the property is not there anymore.

**Comment by Sanjeevsetu** [comment]
Yes, I agree with you. But what I told you that google is only supporting aggregateRating with this (https://developers.google.com/search/docs/data-types/review-snippet.) list. You can not find BlogPost there in the list.

You can see the markup in json using 1.9.7 but it is not valid by google. Error ( https://prnt.sc/pet9d8  )

**Comment by dimon00** [comment]
"You can not find BlogPost there in the list.". Ok. But that is a google decision. Other engines can support it. And google can change its mind. AggregateRating should be displayed in the code of the page and left the decision fo the support to the search engine.

If you check https://schema.org/BlogPosting aggregateRating is a valid property

**Comment by Sanjeevsetu** [comment]
Your point is valid but you know most of the users follow google's guidelines. How you are testing schema markup for other search engines. If we keep old method again for you than google will not validate it for you. Is it ok for you?

**Comment by dimon00** [comment]
Maybe a way to decide? A flag somewhere to force the aggregatetarget markup to show up?

**Comment by ahmedkaludi** [comment]
Github is for tested and re-creatable bugs, for support please go to http://structured-data-for-wp.com/support/
