### ISSUE TITLE
Multiple Instances of Schema Type (i.e. LocalBusiness) Merging Improperly on Same Page

### ISSUE THREAD

**Issue by ibweb** [ahmedkaludi/schema-and-structured-data-for-wp#537]
When creating a LocalBusiness schema (given appropriate subtype), we find that it works successfully on individual pages it is assigned.  For instance a location page, https://www.customcompleteautomotive.com/our-locations/215-s-providence-rd-columbia-mo-65203/
Schema inserts and validates properly.

However, we want these individual LocalBusiness schemas to **additionally** display on the Homepage of the website.  However, when we assign to the homepage of the website, the schema merges into one overarching LocalBusiness schema.  See example:
![merging-example](https://user-images.githubusercontent.com/5447062/66418254-4d877f00-e9c7-11e9-9845-190459b72ea5.png)

While this doesn't throw technical errors in the Structured Data Testing Tool, our understanding is this is not the correct format. Google wants to see a separate instance of each LocalBusiness so that it can associate the NAP information with that particular location and understand that there are multiple locations for that given business.  Thus, the schemas need to be split out separately.    
Here's an example of our location settings on the backend which all validate great on the individual location pages
![example-of-location-schema](https://user-images.githubusercontent.com/5447062/66418375-95a6a180-e9c7-11e9-8868-7d676f76ad53.png)

To confirm, we have the "Defragment" setting **disabled** 
![defragment-disabled](https://user-images.githubusercontent.com/5447062/66418350-86275880-e9c7-11e9-8ab0-1e3438e7c34b.png)

Here's an example of a successful schema integration (non WordPress) for multi-location (multiple LocalBusiness schemas, in this case "General Contractor") assigned: https://p1group.com/ 

Our thoughts would be that the Plugin needs to be able to recognize these separate schemas automatically (ideal implementation, but may cause conflicts) to avoid merging.  **Or**, the user needs to be able to define a unique @id for that schema type (via Modify Output) to avoid the auto merge.

**Comment by Sanjeevsetu** [comment]
We have gone through your issues. Yes, We should separate them by providing unique id. We are now going to add @id field in modify schema output.

**Comment by ibweb** [comment]
@Sanjeevsetu Sounds great!  Thanks for the quick reply and tackling the issue.
