### ISSUE TITLE
Adding Reviews Manually

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/schema-and-structured-data-for-wp#538]
Add reviews from the customers that aren't entered from other websites.

Ref: https://secure.helpscout.net/conversation/975347894/88975?folderId=3250553

**Comment by akashagrjsr** [comment]
Ref: https://secure.helpscout.net/conversation/985823032/93239?folderId=2770545

**Comment by akashagrjsr** [comment]
another https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/59
and https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/298

**Comment by Joao-Paulo-LP** [comment]
Hello Sanjeev

Is it possible for the reader to evaluate our articles? How do we do it?

Best regards,
Joao Paulo

Sanjeev Kumar <notifications@github.com> escreveu no dia segunda,
16/12/2019 à(s) 05:07:

**Comment by Joao-Paulo-LP** [comment]
Hi there

I saw that it is already possible for the reader to comment and rate an article.

**Allow me some suggestions:**
- The insertion should be automatic in all articles and not by shortcode.
- You should be able to rate the post without having to type the name and comment.
- The number of ratings and their average should be visible.

Look at this picture (in the red rectangle for an example: https://prnt.sc/qcsyky

**Comment by ahmedkaludi** [comment]
@Joao-Paulo-LP Sounds good, we will certainly think of building this
