### ISSUE TITLE
In AMP Bench Testing Tool if SASWP plugin is activated the featured image is not showing

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#551]
Screenshot: https://monosnap.com/file/VuFRzQY95hidHl2UBkeWr9OKZfRUII

Ref: https://secure.helpscout.net/conversation/957907295/83343/

**Comment by Sanjeevsetu** [comment]
This ticket is no more valid. You can read here the reason.  http://ampbench.appspot.com/, https://github.com/ampproject/ampbench/issues/126
