### ISSUE TITLE
Real Breadcrumb list is not rendering in schema markup(WooCommerce Compatibility for Schema.)

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#563]
Real Breadcrumb list is not rendering in the schema markup(WooCommerce Compatibility for Schema.)

https://secure.helpscout.net/conversation/984813655/92768?folderId=2632030

**Comment by amer07** [comment]
Case-II
https://secure.helpscout.net/conversation/978202969/89996?folderId=2770543

**Comment by nommanshaik18** [comment]
https://secure.helpscout.net/conversation/993474778/95603/

another user
