### ISSUE TITLE
Add a functionality to import  all reviews from other plugin such has WP Rich Snippets. 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#565]
Add functionality to import all reviews from other plugin such has WP Rich Snippets. 

https://secure.helpscout.net/conversation/986018568/93276?folderId=1060556

**Comment by Sanjeevsetu** [comment]
Waiting for user reply for more clarity on this

**Comment by Sanjeevsetu** [comment]
Need to discuss with team. Once I get more clarity I will work on this.

**Comment by Sanjeevsetu** [comment]
We do not have more data to work on this ticket. I am closing this ticket for now. If we get request again, we will create new ticket.
