### ISSUE TITLE
Compatibility of BNE Testimonial plugin

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/schema-and-structured-data-for-wp#566]
building Compatibility of BNE Testimonial plugin

Ref: https://secure.helpscout.net/conversation/987063560/93604/

https://wordpress.org/plugins/bne-testimonials/

**Comment by SayyadF** [comment]
Ref: https://secure.helpscout.net/conversation/987063560/93604/ when this ticket is completed then implement at user end.
