### ISSUE TITLE
Need to make compatible with Wp-product review plugin.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#568]
Ref; https://secure.helpscout.net/conversation/987593406/93801?folderId=2770543

**Comment by Sanjeevsetu** [comment]
REF:https://secure.helpscout.net/conversation/1089116056/112422?folderId=3528427

(https://prnt.sc/r7wn13) needed to added features
and to make compatible with the user can migrate the reviews of the wp-product review.
