### ISSUE TITLE
Make compatibility with rating plugin

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#570]
We need to make schema and structured data compatible with the rating plugins.

Ref: https://secure.helpscout.net/conversation/987596351/93805?folderId=3257665

**Comment by nommanshaik18** [comment]
Another user
 https://secure.helpscout.net/conversation/988552601/94222?folderId=3081347

**Comment by ahmedkaludi** [comment]
Review > Local Business > Modify Schema
