### ISSUE TITLE
Need to add a softwarApplication schema type and need to make compatiblity with applay theme

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#572]
Need to add a software application schema type

Need to make compatibility with the theme applay theme.

https://secure.helpscout.net/conversation/985777060/93228?folderId=2632030

**Comment by Sanjeevsetu** [comment]
This theme uses WooCommerce to list the SoftwareApplication and we already have that compatibility so We are closing this ticket. If user gets any issue we will create new ticket for that.
