### ISSUE TITLE
Make compatibility with Featured Video Plus

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/schema-and-structured-data-for-wp#576]
Make compatibility with Featured Video Plus so that it can be shown as a snippet on Google.

Ref: https://secure.helpscout.net/conversation/986471918/93352?folderId=3250553

URL: https://macleodtraildental.ca/family-dentist/

URL: https://macleodtraildental.ca/teeth-whitening/

**Comment by Laxmikanth2502** [comment]
DES: video duration is unable to view in the structured data testing tool.
REF:https://secure.helpscout.net/conversation/1159555258/128546?folderId=3528427

REF:https://wordpress.org/plugins/video-thumbnails/
