### ISSUE TITLE
Need to add DefinedTerm in schema

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/schema-and-structured-data-for-wp#596]
Need to add structured data of the type Dictionary or Defin Terms to WEB.

Ref: https://secure.helpscout.net/conversation/997948945/96759?folderId=3250553

**Comment by kunalaharika** [comment]
Another user also requesting for the "Define Term" in the schema 

ref: https://secure.helpscout.net/conversation/1419236121/179778?folderId=1060556

**Comment by Sanjeevsetu** [comment]
The term is not fully integrated to schema.org. Once it is. We will add it in our plugin.
