### ISSUE TITLE
Need to add compatibility of "WP Customer Reviews" inside Reviews for Schema

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#597]
Ref: https://secure.helpscout.net/conversation/995290202/96010?folderId=1060554

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/1024763938/101153?folderId=2632030


- [ ]  We need to create an option to import the reviews from this plugin.

- [ ] Need to show the column where we can find the Reviews are from which post or page.

Like this: https://monosnap.com/file/SuvydH2MENdslnz12RI2zXyPZ6y6rd
