### ISSUE TITLE
claimreview support

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#6]
We need to add this support but we are waiting to hear from the user about it's use-case.

https://wordpress.org/support/topic/questions-about-schema-and-structured-data-for-wp-amp/

**Comment by christopheran** [comment]
Hi Ahmedkaludi,

I run a consumer news and advocacy site and we'll be doing fact checks/claim reviews on claims by companies/affiliates/reviewers as per the instructions provided by Google:  https://developers.google.com/search/docs/data-types/factcheck 

Thanks for looking into this,

Chris

**Comment by ahmedkaludi** [comment]
Sure @christopheran We will add this support.

But how are you adding the data? In the custom fields or the directly n in the Content editor?

and how are you adding the structured data in the non-AMP version?

**Comment by ahmedkaludi** [comment]
@christopheran Any update on this?

**Comment by christopheran** [comment]
Hi Ahmed,

I'm sorry it took me a while to get back to you on this. I got overwhelmed with trying to do too many things on my site all at once. 

I don't have an example page for you as I haven't actually done any factcheck/claimreview articles yet, I want to get this set up for the near future, but what I picture is putting the required information into custom fields. 

Chris

**Comment by christopheran** [comment]
You mention putting it directly into the editor... how would that be done? I'm willing to try and learn either,

Chris

**Comment by ahmedkaludi** [comment]
@christopheran Data can be input in many ways. If you haven't started then it's probably better idea to setup in a way that your inputs works perfectly with claimreview structure. I have few ideas about how we can implement this but then it is important for me to see real world usecase to see if that solution is worthy enough or not. In this case, we dont have a real use case, if you could give one, I can provide a faster solution

**Comment by ahmedkaludi** [comment]
Until you provide us a real life demo, we can't do anything on this. So, we're closing this one for now. If you need more help, just email us on team@magazine3.com
