### ISSUE TITLE
Need to add "ItemList" schema type.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#605]
As per the user concern that need to add the "ItemList" schema type.

Ref: https://secure.helpscout.net/conversation/1001148694/0/?folderId=3126461

Example: please refer to 5th example in the Link
https://schema.org/ItemList

**Comment by ahmedkaludi** [comment]
- [ ] Default integration

- [ ] Gutenberg mod

- [ ] 3rd party compat

- [ ] auto UL list

**Comment by sardarui** [comment]
Please check with the below site for an Example:

https://bharatstories.in/top-5-best-toothpaste-brands-in-india/
