### ISSUE TITLE
Problem With Review Schema

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/schema-and-structured-data-for-wp#606]
The Review Schema has problems – the plugin does not support both Review Name and Product Name. When I do this the Product Name will not save in the modified schema and the Product URL reverts to a random value (Site Title).

Ref: https://wordpress.org/support/topic/problem-with-review-schema/

**Comment by salcan** [comment]
Thanks for picking up my issue. I will follow along.
