### ISSUE TITLE
Title Field uses incorrect title

### ISSUE THREAD

**Issue by salcan** [ahmedkaludi/schema-and-structured-data-for-wp#608]
When your structured data pulls in "Title" it's using the website title:
wp_title()

This is useful in a very limited number of circumstances. I would prefer to see post title:
get_the_title()

This would be helpful for Review and Product schema where the name of the product is often the name of the post. The name of the website is almost never helpful.

**Comment by ahmedkaludi** [comment]
@Sanjeevsetu we can discuss this but seems like a valid so I am adding it to the milestone

**Comment by Sanjeevsetu** [comment]
Just contact us on https://structured-data-for-wp.com/contact-us/. This issue is not clear to us.
