### ISSUE TITLE
Wordpress 5.3 :- Modify button keeps loading in Schema Type

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#609]
The latest version of Wordpress has a bug with Structured data and schema 
Screenshot:- https://monosnap.com/file/4AqdIAwQ67Y1RkSfEtmOLZgzeWuPr6
In schema type the modify button keeps on loading.

**Comment by itsHall** [comment]
Any idea when this fix will be released?

Love the plugin, guys! Keep up the good work.

**Comment by ahmedkaludi** [comment]
We are planning a release today

**Comment by Sanjeevsetu** [comment]
Issue has been fixed and pushed in v1.9.16.1
