### ISSUE TITLE
referencing custom entities inside html/gutenberg

### ISSUE THREAD

**Issue by dimon00** [ahmedkaludi/schema-and-structured-data-for-wp#610]
I'd like to be able to create entities inside my html and reference the main schema generated by schema-and-structured-data-for-wp.

My goal is to avoid to replicate the text/entities in a JSON-LD in order to have a better Text/HTML Ratio.

For example: my main content, in gutenberg has a series of subsection, each represent a "question" (https://schema.org/Question). I'd like to mark them as https://schema.org/Question in my html and the reference, in some way the https://schema.org/BlogPosting in my JSON-LD create by schema-and-structured-data-for-wp

**Comment by ahmedkaludi** [comment]
Let's discuss this ticket, but I'm still adding in the milestone

**Comment by dimon00** [comment]
My goal is to tag the content of my wordpress pages which is inside gutenberg.
I wouldn't like to use a JSON-LD because I don't want the text/source to deteriorate.

The only solution I can think is to insert microdata in the HTML and to refer (maybe with itemref) the entities in the JSON-LD created by your plugin.

To make it more simple I could wrap all the gutenberg content in a tag ( a https://schema.org/CollectionPage ?) and have my entities (https://schema.org/Question) inside.

What I cannot see is a way to link a HTML microdata tag to the JSON.

Any idea?

**Comment by Sanjeevsetu** [comment]
Hi @dimon00.

You want to achieve something like this: -

<html>
<head>
<title>Article headline</title>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Blogposting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://google.com/article"
  },
  "headline": "Article headline",
  "image": [
    "https://example.com/photos/1x1/photo.jpg",
    "https://example.com/photos/4x3/photo.jpg",
    "https://example.com/photos/16x9/photo.jpg"
   ],
  "datePublished": "2015-02-05T08:00:00+08:00",
  "dateModified": "2015-02-05T09:20:00+08:00",
  "mainEntity":{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [{
    "@type": "Question",
    "name": "What is the return policy?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Most unopened items in new condition and returned within <strong>90 days</strong> will receive a refund or exchange. Some items have a modified return policy noted on the receipt or packing slip. Items that are opened or damaged or do not have a receipt may be denied a refund or exchange. Items purchased online or in-store may be returned to any store.<br /><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
    }
  }, {
    "@type": "Question",
    "name": "How long does it take to process a refund?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "We will reimburse you for returned items in the same way you paid for them. For example, any amounts deducted from a gift card will be credited back to a gift card. For returns by mail, once we receive your return, we will process it within 4–5 business days. It may take up to 7 days after we process the return to reflect in your account, depending on your financial institution's processing time."
    }
  }, {
    "@type": "Question",
    "name": "What is the policy for late/non-delivery of items ordered online?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Our local teams work diligently to make sure that your order arrives on time, within our normaldelivery hours of 9AM to 8PM in the recipient's time zone. During  busy holiday periods like Christmas, Valentine's and Mother's Day, we may extend our delivery hours before 9AM and after 8PM to ensure that all gifts are delivered on time. If for any reason your gift does not arrive on time, our dedicated Customer Service agents will do everything they can to help successfully resolve your issue. <br/> <p><a href=https://example.com/orders/>Click here</a> to complete the form with your order-related question(s).</p>"
    }
  }, {
    "@type": "Question",
    "name": "When will my credit card be charged?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "We'll attempt to securely charge your credit card at the point of purchase online. If there's a problem, you'll be notified on the spot and prompted to use another card. Once we receive verification of sufficient funds, your payment will be completed and transferred securely to us. Your account will be charged in 24 to 48 hours."
    }
  }, {
    "@type": "Question",
    "name": "Will I be charged sales tax for online orders?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text":"Local and State sales tax will be collected if your recipient's mailing address is in: <ul><li>Arizona</li><li>California</li><li>Colorado</li></ul>"}
    }]
  },
  "author": {
    "@type": "Person",
    "name": "John Doe"
  },
   "publisher": {
    "@type": "Organization",
    "name": "Google",
    "logo": {
      "@type": "ImageObject",
      "url": "https://google.com/logo.jpg"
    }
  },
  "description": "A most wonderful article"
}
</script>
</head>
<body>
</body>
</html>

**Comment by dimon00** [comment]
Hello Sanjeevsetu,
no, I don't want that.
In particular I don't want the questions and answers in the JSON-LD.
I want them only in my HTML.

**Comment by Sanjeevsetu** [comment]
Ok, You mean, you do not want schema markup for that. If so, you can disable it in Schema settings tab named 'AMP'.

**Comment by dimon00** [comment]
No, I want it in the schema markup but not inside the JSON.
If I place it in the JSON I'm going to worsen my Text/HTML Ratio.

What I wish is to mark my questions inside the HTML and in some way link it to the JSON produced by the plugin.

**Comment by dimon00** [comment]
I see you need more data. 
I'm available to answer your questions.

**Comment by Sanjeevsetu** [comment]
Have you checked our FAQ Gutenberg block?

**Comment by Sanjeevsetu** [comment]
We only generate schema markup in Json format recommended by Google based on content.

**Comment by ahmedkaludi** [comment]
We are already aware of this, we will note this internally, can't have this on github because we want to have a clear idea on the bugs reported here.
