### ISSUE TITLE
Review Field

### ISSUE THREAD

**Issue by salcan** [ahmedkaludi/schema-and-structured-data-for-wp#611]
Google structured data tool: 
"The review field is recommended. Please provide a value if available."

What does this mean, the review field is missing? Is this ReviewBody? There warning is very unclear.

Example: [Pilot S20 Review](https://unsharpen.com/pen/pilot-s20-ballpoint-pen/)

**Comment by ahmedkaludi** [comment]
GitHub is for recreatable issues, We are providing technical support via email. Please contact https://structured-data-for-wp.com/contact-us/ and we will help you fix this
