### ISSUE TITLE
Issue with Physician Schema

### ISSUE THREAD

**Issue by itsHall** [ahmedkaludi/schema-and-structured-data-for-wp#612]
<img width="140" alt="physician properties" src="https://user-images.githubusercontent.com/31418688/68954212-8dddd800-0791-11ea-9502-442b28056f1c.png">

There are unnecessary properties listed for the physician object. Also, **a required property: name, is missing**. This requires users to use the Person object instead for medical professionals.

**Comment by Sanjeevsetu** [comment]
Just put the name inside 'Business Name'. this is same as Name.

**Comment by itsHall** [comment]
> Just put the name inside 'Business Name'. this is same as Name.

That worked for the Physician type.

Now I'm seeing an issue where selecting Oncologic instead of Physician (I imagine this is an issue for similar types under Local Business > Medical Business) throws an error in the Structured Data Tester from Google for not being a valid type.

<img width="647" alt="invalid oncologic type" src="https://user-images.githubusercontent.com/31418688/69173984-e9300300-0ace-11ea-8492-20aa1ce674b5.png">

Also, the type for the address object when having Oncologic selected is unspecified.

<img width="654" alt="invalid oncologic address type" src="https://user-images.githubusercontent.com/31418688/69174064-18df0b00-0acf-11ea-8de0-c2347b0eb388.png">

**Comment by ahmedkaludi** [comment]
it's because it's not recognized by Google, so you can't use it at the moment.
