### ISSUE TITLE
improve AMP compatibility

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#615]
- [ ] 1. PenCi Soledad AMP - WordPress Complete AMP

- [ ] 2. Better AMP

https://secure.helpscout.net/conversation/1001331174/97224?folderId=1060554

**Comment by rajat-nrich** [comment]
3. WP AMP — Accelerated Mobile Pages for WordPress and WooCommerce

Please add

**Comment by SayyadF** [comment]
One more user-requested for WP AMP — Accelerated Mobile Pages for WordPress and WooCommerce compatibility

Ref:https://secure.helpscout.net/conversation/1016501902/99656/
