### ISSUE TITLE
Woocommerce product shows reviews in schema when they are disabled

### ISSUE THREAD

**Issue by cschot** [ahmedkaludi/schema-and-structured-data-for-wp#616]
I got a website where there are products in Woocommerce.
I got reviews disabled in woocommerce and this plugin.
But there are still reviews showing up in the structured data output.

Plugin version: 1.9.16.1
Wordpress 5.2.4
Woocommerce 3.8.0

Current output:

`[{"@context":"https:\/\/schema.org","@type":"Product","@id":"****","url":"****","name":"****","sku":"*****","description":"******","image":[{"@type":"ImageObject","url":"*****","width":"2481","height":"3508"},{"@type":"ImageObject","url":"*****","width":"724","height":"1024"},{"@type":"ImageObject","url":"*****","width":"212","height":"300"},{"@type":"ImageObject","url":"******","width":"150","height":"150"}],"mpn":"***","brand":{"@type":"Thing","name":"******"},"aggregateRating":{"@type":"AggregateRating","ratingValue":"5","reviewCount":1},"review":[{"@type":"Review","author":"*****","datePublished":"2019-04-03T12:33:22+01:00","description":"******","reviewRating":{"@type":"Rating","bestRating":"5","ratingValue":"5","worstRating":"1"}}]}]
`

**Comment by Sanjeevsetu** [comment]
Actually, If the reviews are not there in product schema. Google testing tool gives us warning. To remove that warning we have placed one default review. But now as per user requirement, We are going to add an option to show it or not which will be covered in this ticket https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/619.
