### ISSUE TITLE
A value for the mainEntity field is required. on FAQ Schema

### ISSUE THREAD

**Issue by dreamm160** [ahmedkaludi/schema-and-structured-data-for-wp#622]
Hi,

Highly appreciate your works.

I would like to report that FAQ Schema is not properly working.

After inputting Questions and Answers and testing it, the testing tool gives an error as follows.

A value for the mainEntity field is required.

Thank you

**Comment by ahmedkaludi** [comment]
Can you please share the url through https://structured-data-for-wp.com/contact-us/

So we can help you with it
