### ISSUE TITLE
A value for the url field is required when feature image select in modify schema output option 

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#630]
Case: I
https://secure.helpscout.net/conversation/1015528471/99523?folderId=2770543
Also, recreate in local 
Explain:
In modifying schema output when we select image property type in this select feature image type it does not fetch the URL of the featured image.
See these screenshots:

1.https://prnt.sc/q25imn
2.https://prnt.sc/q25iwg

**Comment by Sanjeevsetu** [comment]
This is invalid ticket. I try to re-create the issue and found that featured image was not there on that post.
