### ISSUE TITLE
RDFa CleanUp

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#632]
We need to remove all the RDFa generated by other plugins.

Ref: https://secure.helpscout.net/conversation/1002169130/97323?folderId=3257665

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/1025564756/101295?folderId=2632030

**Comment by TMsravan** [comment]
https://secure.helpscout.net/conversation/1026760851/101507?folderId=2632030

**Comment by akashagrjsr** [comment]
One more user having the issue:
https://secure.helpscout.net/conversation/1023152136/100794/
