### ISSUE TITLE
Custom schema shows not a valid json even validated from google structure data testing tool

### ISSUE THREAD

**Issue by Monalisha5595** [ahmedkaludi/schema-and-structured-data-for-wp#637]
json code which is validated from structure data testing tool but does not support in custom schema.

For reference: https://wordpress.org/support/topic/trip-properties/

**Comment by Sanjeevsetu** [comment]
This ticket is invalid. Actually json was not valid. Please test using any json validator tool. such as http://jsonviewer.stack.hu/
