### ISSUE TITLE
php 7.4 testing

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#644]
https://wordpress.org/support/topic/crashed-site-had-to-pull-backup-image/#post-12211025

**Comment by Sanjeevsetu** [comment]
https://wordpress.org/support/topic/1-9-17-generates-fatal-error-under-php-7-4/

**Comment by mhair** [comment]
The fatal error I was getting is this (also on PHP 7.4):
An error of type E_ERROR was caused in line 62 of the file I:\inetpub\boardofednew.webdev.idaho.gov\wp-content\plugins\schema-and-structured-data-for-wp\modules\reviews\reviews_collection.php. Error message: Uncaught Error: Using $this when not in object context in I:\inetpub\boardofednew.webdev.idaho.gov\wp-content\plugins\schema-and-structured-data-for-wp\modules\reviews\reviews_collection.php:62

**Comment by Sanjeevsetu** [comment]
Hi @mhair,
Thank you for reporting a bug. Yes this is the bug in 7.4. We have fixed this and will update in next release.
