### ISSUE TITLE
Need to add compatibility to fetch "freelancer.com" reviews in "Reviews for schema"

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#658]
As per the user, he wants to fetch freelancer reviews on his Website.

Ref: 
https://secure.helpscout.net/conversation/1030554890/102107?folderId=3126461

Doc: 
https://developers.freelancer.com/docs/projects/reviews#reviews-get

**Comment by Sanjeevsetu** [comment]
Waiting for customer reply to get more data.
