### ISSUE TITLE
Improvement in archive page schema

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/schema-and-structured-data-for-wp#660]

**Comment by Sanjeevsetu** [comment]
@ahmedkaludi, We have to discuss it as there may be more changes

**Comment by ahmedkaludi** [comment]
@Sanjeevsetu sure , what exactly is the ticket for?

**Comment by Sanjeevsetu** [comment]
currently there is no more point to be discussed regarding this so I am closing this ticket
