### ISSUE TITLE
The images are broken on the AMP pages

### ISSUE THREAD

**Issue by lapnayh** [ahmedkaludi/schema-and-structured-data-for-wp#661]
After the last update ( 1.9.18) the content images do not appear for pages in any of the AMP modes. 

However, HTML pages do not have that problem. I have tried disabling several plugs, and I found the problem solved by deactivating: Schema & Structured Data for WP & AMP

### wp-core ###

version: 5.3.1
site_language: es_ES
user_language: es_ES
timezone: America/Mexico_City
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 4
dotorg_communication: true

### wp-plugins-active (28) ###

Ad Inserter: version: 2.5.10, author: Igor Funa
AMP: version: 1.4.1, author: AMP Project Contributors
Astra Widgets: version: 1.2.1, author: Brainstorm Force
Classic Editor: version: 1.5, author: WordPress Contributors
Easy Table of Contents: version: 1.7, author: Steven A. Zahm
Elementor: version: 2.8.1, author: Elementor.com
Facebook for WooCommerce: version: 1.9.15, author: Facebook
Glue for Yoast SEO & AMP: version: 0.5, author: Joost de Valk
Google Analytics Dashboard for WP (GADWP): version: 5.3.10, author: ExactMetrics
Gutenberg: version: 7.1.0, author: Gutenberg Team
Invisible reCaptcha: version: 1.2.3, author: Mihai Chelaru
Mailchimp for WooCommerce: version: 2.3, author: Mailchimp
MailMunch - Grow Your Email List: version: 3.1.2, author: MailMunch
Ocean Extra: version: 1.5.19, author: OceanWP
Official Facebook Pixel: version: 1.8.0, author: Facebook
Really Simple SSL: version: 3.2.6, author: Rogier Lankhorst, Mark Wolters
Redirection: version: 4.5.1, author: John Godley
Share Buttons by AddThis: version: 6.2.6, author: The AddThis Team
TinyMCE Advanced: version: 5.3.0, author: Andrew Ozz
UpdraftPlus - Backup/Restore: version: 1.16.21, author: UpdraftPlus.Com, DavidAnderson
WebP Express: version: 0.17.2, author: Bjørn Rosell
WooCommerce: version: 3.8.1, author: Automattic
WooCommerce Google Analytics Integration: version: 1.4.15, author: WooCommerce
WooCommerce PayPal Checkout Gateway: version: 1.6.18, author: WooCommerce
Wordfence Security: version: 7.4.2, author: Wordfence
WP-Optimize - Clean, Compress, Cache: version: 3.0.14, author: David Anderson, Ruhani Rabin, Team Updraft
WPForms Lite: version: 1.5.7, author: WPForms
Yoast SEO: version: 12.7.1, author: Team Yoast

### wp-plugins-inactive (2) ###

Schema & Structured Data for WP & AMP: version: 1.9.18, author: Magazine3
WP GDPR Cookie Notice: version: 1.0.0-beta.2, author: Felix Arntz

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.26.2.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.3.12 64bit
php_sapi: cgi-fcgi
max_input_variables: 5400
time_limit: 90
memory_limit: 256M
max_input_time: 60
upload_max_size: 10M
php_post_max_size: 10M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.46-cll-lve

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

**Comment by lapnayh** [comment]
I have downloaded and installed version 1.9.17 and there is no problem.

**Comment by ahmedkaludi** [comment]
Github is for valid & re-creatable bugs. Technical support is provided at https://structured-data-for-wp.com/contact-us/
