### ISSUE TITLE
Generate schema for related product

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#673]
we need to generate schema for related product also instead of creating schema only for the product.
Ref:
https://secure.helpscout.net/conversation/1028806556/0/?folderId=3257665

**Comment by Sanjeevsetu** [comment]
As per google guidelines. This is not recommended so we should not add this. Once google does support this kind of structure. We will add it. 

Ref: https://developers.google.com/search/docs/data-types/product#guidelines
