### ISSUE TITLE
Version 1.9.20 Conflict with Yoast Faq Schema Mark Up

### ISSUE THREAD

**Issue by wayansuadnyana** [ahmedkaludi/schema-and-structured-data-for-wp#698]
Dear Admin,

After updating the Schema & Structured Data for WP & AMP to Version 1.9.20, I find out the Yoast FAQ is missing from Google Index. Then I do several tests on google structured data testing tool and find out the Yoast schema mark up is missing. Then I check the Schema & Structured Data for WP & AMP setting on compatibility setting, and the Yoast SEO Plugin is on the checkmark. 

To find out the conflict, then I deactivate Schema & Structured Data for WP & AMP and do several tests on google structured data testing tool. After the test, I can see the Yoast schema FAQ mark is appear normal. Therefore, I take a conclusion; the issue is on  Schema & Structured Data for WP & AMP  Version 1.9.20.

Please help to fix the issue.

Regard,

Wayan Suadnyana.

**Comment by ahmedkaludi** [comment]
Github is for re-creatable and verified issues. Kindly ask this issue to our technical team and they will help you validate this. Contact them via https://structured-data-for-wp.com/contact-us/
