### ISSUE TITLE
Role based access does not work properly with default role Administrator(Default)

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#700]
When admin is accessing the dashboard then he should not see the option Administrator(Default) In the Role-based access section.
screenshot: https://monosnap.com/file/O8El7d1qWSv8XIoTDTHHtJ6jhZ6EYq

Ref: https://secure.helpscout.net/conversation/1045211711/0/?folderId=3257665

**Comment by Sanjeevsetu** [comment]
https://wordpress.org/support/topic/user-role-issue-3/
