### ISSUE TITLE
Need to add description field in VideoObject.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/schema-and-structured-data-for-wp#73]
Need to add description field in VideoObject.
Ref : https://secure.helpscout.net/conversation/715443745/41912?folderId=2322652
![structured data testing tool - videoobject](https://user-images.githubusercontent.com/43204388/48968220-4efbc300-f012-11e8-816e-3f6ff0a90174.png)

**Comment by Sanjeevsetu** [comment]
Description field is already there in our VideoObject type. They have no description value in the field thats why error occurred.
