### ISSUE TITLE
Warning and debug errors in schema

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#746]
Ref: https://secure.helpscout.net/conversation/1062796505/107788/

[warning_error_file.txt](https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/files/4107775/warning_error_file.txt)

**Comment by Sanjeevsetu** [comment]
Notice: Undefined index: sd-person-job-title in /Applications/MAMP/htdocs/wp48/wp-content/plugins/schema-and-structured-data-for-wp/output/output.php on line 124

Notice: Undefined index: sd-person-phone-number in /Applications/MAMP/htdocs/wp48/wp-content/plugins/schema-and-structured-data-for-wp/output/output.php on line 133
