### ISSUE TITLE
 Offer is not a known valid target type for the image property

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/schema-and-structured-data-for-wp#752]
User have getting an error, that is Offer is not a known valid target type for the image property in schema.
Reference:   https://wordpress.org/support/topic/error-offer-is-not-a-known-valid-target-type-for-the-image-property/

**Comment by adrianmarquez2020** [comment]
![FireShot Capture 327 - Herramienta de prueba de datos estructurados - search google com](https://user-images.githubusercontent.com/58829697/73271660-5ccd4b00-41b7-11ea-924a-a6827ac87d0c.png)

Yes, I am having this problem in all the schemes of my products
https://blucatreddog.is/shop-embroidery-designs/corvette/corvette-1963-nose-emblem/

**Comment by adrianmarquez2020** [comment]
Yes, I am having this problem in all the schemes of my products
https://blucatreddog.is/shop-embroidery-designs/corvette/corvette-1963-nose-emblem/

![FireShot Capture 328 - Herramienta de prueba de datos estructurados - search google com](https://user-images.githubusercontent.com/58829697/73271976-f72d8e80-41b7-11ea-8f3b-32ca96fc725e.png)
