### ISSUE TITLE
Filters not called when using Gutenberg block?

### ISSUE THREAD

**Issue by BrunoCartier** [ahmedkaludi/schema-and-structured-data-for-wp#753]
Hey,

I was trying to use the `saswp_modify_faq_schema_output` filter to change the output of a schema for a Gutenberg FAQ. I lost a lot a time trying to make it work, but it doesn't :/

It looks like `$input1 = apply_filters('saswp_modify_faq_schema_output', $input1 );` is never called when generating the FAQ Schema.

In the "normal" output generator, it is called:
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/fab1d3b01a6cff753bce9d68414d00f613c253ae/output/output.php#L243

But not in the Gutenberg output generator:
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/eadfed25d69b7ba226159cfe150983eb720bd7aa/output/gutenberg.php#L234

Is it a bug, or is it a technical impossibility?
Maybe I am missing something:
- How else can I modify the output for the schema generated for a Gutenberg FAQ Block?
- Is there, somewhere, a filter that modify every output, including `output/gutenberg.php` output?

Thanks.

**Comment by Sanjeevsetu** [comment]
Hi @BrunoCartier,

This is a bug. Actually that apply_filter is missing in Gutenberg FAQ block. We are going to fix it in our next milestone.
