### ISSUE TITLE
Need to make compatibility with Yotpo reviews plugin.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#756]
We need to make compatibility with the Yotpo reviews plugin (Yotpo.com) as a Woo/WP plugin.
Ref: https://secure.helpscout.net/conversation/1064714778/108062/

**Comment by HaripriyaHari** [comment]
Another user needs to make compatibility with the Yotpo reviews plugin.
Reference: https://wordpress.org/support/topic/doesnt-work-with-yotpo/

**Comment by tallcoder** [comment]
Yotpo still doesn't appear to work. Had to move on to another plugin.
