### ISSUE TITLE
Invalid article schema is loading due to "The SEO Framework - Extension Manager" plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#771]
Ref: https://secure.helpscout.net/conversation/1068526808/108619?folderId=2770545

We need to remove the invalid article schema loading due to the plugin "The SEO Framework - Extension Manager".

**Comment by Sanjeevsetu** [comment]
The SEO Framework - Extension Manager plugin has been closed permanently in 2018. No more users are getting this issue. so I closing it.
