### ISSUE TITLE
Strip all other shortcode from content

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#777]
Case:1https://secure.helpscout.net/conversation/1074137933/109650?folderId=2770543
Note: only plain text will allow.

**Comment by TMsravan** [comment]
Case2: https://secure.helpscout.net/conversation/1094224331/113422?folderId=2632030

formating tags are rendering in the Product and Review descriptions.

Example: Example from a product review description:
[vc_row center_row="yes"][vc_column][vc_column_text] Learn to Play the Harp the Hands On Way [/vc_column_text][vcex_spacing][vc_column_text]We think that the traditional way to learn to play harp, i.e. weekly or fortnightly lessons, is not only unnecessarily expensive, but also not the best way to learn.[/vc_column_text][vcex_spacing][vc_column_text]You can join our subscription web site for just £20 a month, or £10 a month…

REf: https://www.handsonharps.com/product/online-harp-lessons-course-subscription/
