### ISSUE TITLE
Warning with FAQ block in DIVI builder.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#780]
/FaqBlockChild/FaqBlockChild.php:85  SASWP_Divi_FaqBlockChild::get_advanced_fields_config():
You're Doing It Wrong! SASWP_Divi_FaqBlockChild::$advanced_tab_options doesn't exist.

Ref:- https://secure.helpscout.net/conversation/1072642407/109154?folderId=3243584

*Recreated on local.

**Comment by messynaman22** [comment]
I'm facing the same issue on my Divi Theme. Is there any solution for the same yet?

**Comment by mahnunchik** [comment]
Any news?
