### ISSUE TITLE
Custom fields for Author not updated

### ISSUE THREAD

**Issue by mellema-marketing** [ahmedkaludi/schema-and-structured-data-for-wp#785]
After asigning a differend author to an Page through "Quick edit" in the section "All pages" the person fields for Article are not updated:
e.g.
saswp_article_author_description_247
saswp_article_author_name_247
saswp_article_author_url_247

**Comment by ahmedkaludi** [comment]
I would love to help you but the bug needs to be confirmed yet, can you please confirm from https://structured-data-for-wp.com/contact-us/
