### ISSUE TITLE
Need to add speakable schema type support in the plugin.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/schema-and-structured-data-for-wp#79]
Desc: Need to add speakable schema type support in the plugin.
Ref: https://secure.helpscout.net/conversation/720512534/43293?folderId=2169248

More Info

https://pending.schema.org/speakable
https://developers.google.com/search/docs/data-types/speakable

**Comment by beingsmart3** [comment]
One more Ref:  https://secure.helpscout.net/conversation/817145687/62108?folderId=1914712
