### ISSUE TITLE
comaptibility with the "Ratency - Review & Magazine Theme"

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#793]
Need to make compatibility with the "Ratency - Review & Magazine Theme"
https://themeforest.net/item/ratency-review-magazine-theme/21303977

Ref: https://secure.helpscout.net/conversation/1052849412/106096?folderId=3257665

**Comment by Sanjeevsetu** [comment]
Waiting for user reply
