### ISSUE TITLE
Image size is smaller than recommended size warning on a multilingual website.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#796]
Ref:- https://secure.helpscout.net/conversation/1082979504/111137?folderId=3243584

**Comment by Sanjeevsetu** [comment]
Still waiting for user's reply

**Comment by Sanjeevsetu** [comment]
Since User is not reply from long time and we need more data about this so we are closing this ticket
