### ISSUE TITLE
Invalid post type in Multisite 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/schema-and-structured-data-for-wp#817]
Reference:  https://wordpress.org/support/topic/invalid-post-type-9/

**Comment by ahmedkaludi** [comment]
We need to test properly in multi site and understand his usecase

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
I tested this issue using user's use cases and It was working fine so I am going to close this ticket. If I get anything related to it, I will reopen it.
