### ISSUE TITLE
Need to build an option to display post rating on review page.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#822]
The user is using our rating on Posts and those ratings are displaying perfectly on single post but the user wants to show those post ratings on the review page where all the posts are listed.

Ref Ticket: https://secure.helpscout.net/conversation/1079161966/110474?folderId=3126461

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
Still wating for user reply

**Comment by Sanjeevsetu** [comment]
Since user is not active related to this ticket so I am going to close this one.
