### ISSUE TITLE
Compatibility issue with the Blackbar plugin

### ISSUE THREAD

**Issue by pryley** [ahmedkaludi/schema-and-structured-data-for-wp#83]
When the [Blackbar plugin](https://wordpress.org/plugins/blackbar/) is activated, it is not possible to run the quick setup or add a new schema. This is happening because you are overriding the default page load process which is preventing Blackbar from enqueuing its assets. 

The easiest way to fix this is to add the following code to the beginning of [add-new.php](../tree/master/admin_section/add-schema/add_new.php).

```php
if( in_array( filter_input( INPUT_GET, 'page' ), array( 'saswp-setup-wizard', 'saswp_add_new_data_type' ))) {
    add_filter( 'blackbar/enabled', '__return_false' );
}
```

**Comment by Sanjeevsetu** [comment]
Hi @pryley, 

Thanks for the support. After adding the given code in add-new.php it is working fine so we have pushed that code here you can see. It will be released with our new update.
