### ISSUE TITLE
Add articles link underneath the "schema type" dropdown in edit schema type panel

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#830]
Adding a link to the appropriate How-To-Article from our documentation(every time a schema type is selected) underneath the dropdown, the user can simply click on it and will get the help without searching.

Screengrab: https://monosnap.com/file/mJDYEffvhQqLzRBBfTFI0BFvmAHVPo
ref: https://secure.helpscout.net/conversation/1089246910/112472/

**Comment by Sanjeevsetu** [comment]
This is similar issue to https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/838. So will be covered in it.
