### ISSUE TITLE
needed to migrate the reviews from wp-porduct review plugin

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/schema-and-structured-data-for-wp#836]
REF:https://secure.helpscout.net/conversation/1089116056/112422?folderId=3528427

(https://prnt.sc/r7wn13)  needed to added features
and to make compatible with the user can migrate the reviews of the wp-product review.

**Comment by Sanjeevsetu** [comment]
this is duplicate to https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/568. so i am closing it.
