### ISSUE TITLE
The following external resources have small response bodies. Inlining the response in HTML can reduce blocking of page rendering.

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/schema-and-structured-data-for-wp#839]
REF:https://secure.helpscout.net/conversation/1074451467/109733?folderId=3528427

The following external resources have small response bodies. Inlining the response in HTML can reduce blocking of page rendering.
previewed in the screenshot(https://prnt.sc/r8i9tr)

**Comment by ahmedkaludi** [comment]
-[] why is divi script loading in the front end?

**Comment by ahmedkaludi** [comment]
why was it removed from 1.9.28? - let me know if you need help in this ticket
