### ISSUE TITLE
Errors in the structured data testing tool.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#840]
When the user has set the values through the modify schema. then also errors are coming in the testing tool.

Steps to create an issue on localhost:
1. In review schema type. I ahve selected Item review type as product and then added Rating value by modifying schema:
https://monosnap.com/file/A31oxIB0mLCMxJlRyMKH7dDslZHVK5
2. and then also in the structured data testing tool showing an error regarding the rating value.
https://monosnap.com/file/7NvsqVQfBgrCg1ob7z4Ras4wcjHtH7

at users end: https://search.google.com/structured-data/testing-tool/u/0/?hl=fr#url=https%3A%2F%2Fblogautomobile.fr%2Fessai-volvo-s60-polestar-engineered-les-scandinaves-se-rechauffent-336809

Ref: https://secure.helpscout.net/conversation/1089139531/112430?folderId=3257665

**Comment by Sanjeevsetu** [comment]
The issue is not valid however its enhancement will be done in https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/849
