### ISSUE TITLE
Need to add Review Stars in Comment Form in Word press default

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#844]
Need to add review stars in comment form in Wordpress default

Ref:https://secure.helpscout.net/conversation/1097357144/114025?folderId=3575684
screenshot ref:https://prnt.sc/ra93hi

**Comment by vladilil** [comment]
Hi Team, just checking in to see if you need help testing this from a user's end. Thank you.

**Comment by ahmedkaludi** [comment]
https://wordpress.org/plugins/stars-rating/ this is the plugin user users for inspiration
