### ISSUE TITLE
user is getting PHP warning while activating the plugin.

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#847]
The user is getting PHP warning while activating the plugin.
2020/02/29 11:07:02 [error] 12162#12162: *63312 FastCGI sent in stderr: "PHP message: PHP Warning: array_map(): Argument #2 should be an array in /wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 270
PHP message: PHP Warning: array_filter() expects parameter 1 to be array, null given in /wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 156
PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 157

Ref: https://secure.helpscout.net/conversation/1096660582/113875?folderId=3257665

**Comment by Sanjeevsetu** [comment]
Notice: Undefined index: saswp_review_name_260 in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2614

Notice: Trying to access array offset on value of type null in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2614

Notice: Undefined index: saswp_review_url_260 in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2615

Notice: Trying to access array offset on value of type null in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2615

Notice: Undefined variable: review_author in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2638

Notice: Undefined index: saswp_review_item_reviewed_260 in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2660

Notice: Trying to access array offset on value of type null in D:\XAMPP\htdocs\wordpress\wp-content\plugins\schema-and-structured-data-for-wp\output\markup.php on line 2660
