### ISSUE TITLE
Validation errors: The mandatory tag 'link rel=canonical' is missing or incorrect due to schema

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#848]
When the schema is activated validation errors occurring with the specific content type of data, such below URL's content.

Validation errors: The mandatory tag 'link rel=canonical' is missing or incorrect

https://monosnap.com/file/4mW7KqnqOgZcVICYVn35OBtecC9i7O

https://secure.helpscout.net/conversation/1098663650/114296?folderId=2632030
https://ignaciosantiago.com/seguridad-en-wordpress-como-configurar-htaccess-para-evitar-hackeos/amp/

https://ignaciosantiago.com/trucos-google-analytics/amp/

**Comment by Sanjeevsetu** [comment]
waiting for user reply
