### ISSUE TITLE
If job post schema has been expired than its markup should not be shown

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#858]
If job  post has been expired than its markup should not be shown but it is raising an error in the console
screenshot: https://prnt.sc/rci4zn
ref:https://secure.helpscout.net/conversation/1100928855/115051?folderId=3575684

**Comment by jawadkhakh** [comment]
Please update the plugin. I got manual action by google due to this issue and website's all traffic is lost.

**Comment by jawadkhakh** [comment]
> If job post has been expired than its markup should not be shown but it is raising an error in the console
> screenshot: https://prnt.sc/rci4zn
> ref:https://secure.helpscout.net/conversation/1100928855/115051?folderId=3575684

Please update the plugin. I got manual action by google due to this issue and website's all traffic is lost.
