### ISSUE TITLE
It showing an error when option multiple Size Image Creation is enable

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#860]
It showing an error in the test when option multiple Size Image Creation is enabled in the schema

ref:https://secure.helpscout.net/conversation/1101934452/115235?folderId=1060556

**Comment by Sanjeevsetu** [comment]
Waiting for user reply

**Comment by Sanjeevsetu** [comment]
Issue is not valid. I am unable to re create it or see it at user end.
