### ISSUE TITLE
when we update schema type,it is throwing the warnings

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#861]
issue occurring at the user end.
Warning: count(): Parameter must be an array or an object that implements Countable in /home/loansav1/public_html/wp-includes/post-template.php on line 284

Warning: Cannot modify header information - headers already sent by (output started at /home/loansav1/public_html/wp-includes/post-template.php:284) in /home/loansav1/public_html/wp-includes/pluggable.php on line 1219

https://secure.helpscout.net/conversation/1101562289/115167?folderId=2632030

**Comment by lsn12321** [comment]
Thanks. Has this been resolved?

What was the issue?

Thanks
Colin

**Comment by lsn12321** [comment]
Hi, I also note the premium version is not activated with reviews. Can you advise if this is working / can be reactivated.

Note - previously the reviews would not download reviews from google.
