### ISSUE TITLE
images not found in customizer

### ISSUE THREAD

**Issue by cschot** [ahmedkaludi/schema-and-structured-data-for-wp#868]
When in customizer I see these errors in the console:

Failed to load resource: the server responded with a status of 404 () xxxxx.com/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/css/images/ui-bg_glass_65_ffffff_1x400.png:1
Failed to load resource: the server responded with a status of 404 () xxxxxxxx.com/wp-content/plugins/schema-and-structured-data-for-wp/admin_section/css/images/ui-bg_glass_75_e6e6e6_1x400.png:1

When I look in the plugin directory I cannot find the the directory admin_section/css/images

Am I the only one getting these errors or is it a bug?

**Comment by Sanjeevsetu** [comment]
Hi @cschot. 

We checked it and found it is a valid bug. We are going to fix it soon.
