### ISSUE TITLE
needed to be added to hotel room schema

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/schema-and-structured-data-for-wp#870]
REF:https://secure.helpscout.net/conversation/1106484869/116174/

**Comment by LaxmiBhavani-98** [comment]
REF: https://secure.helpscout.net/conversation/1149450972/125610/

**Comment by anthemwild** [comment]
I've got Version 1.9.40 and I don't see any reference to HotelRoom or Room

https://developers.google.com/hotels/hotel-content/proto-reference/lodging-schema
https://schema.org/Room

Thanks!
