### ISSUE TITLE
Add property(modify schema output) does not load properties.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/schema-and-structured-data-for-wp#872]
Add a property(modify schema output) does not load properties for the user to choose.
 The user is using the following plugins: https://prnt.sc/rfppx2.

**Comment by Sanjeevsetu** [comment]
this issue is not valid. The issue is causing due to other plugins. theme or php file which are adding byte order mark. All the ajax request for this customer have parse error.
