### ISSUE TITLE
Review are not getting Fetched at some users end

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#875]
User1:https://secure.helpscout.net/conversation/1103014382/115452?folderId=2632030
The above user has only issue with a Facebook review that is also only one review.

User2: https://secure.helpscout.net/conversation/1104154757/115770?folderId=1060556

**Comment by akashagrjsr** [comment]
One more user is facing the same issue:

https://secure.helpscout.net/conversation/1120659306/118976/

**Comment by Arihantkankariya09** [comment]
User is unable to fetch Facebook reviews https://secure.helpscout.net/conversation/1122520386/119428?folderId=3243584
