### ISSUE TITLE
Need to add  EventAttendanceMode & Virtual location.

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#883]
Case:1https://secure.helpscout.net/conversation/1114669940/117669?folderId=2770543

**Comment by ahmedkaludi** [comment]
add support in 

- [ ] core

- [ ] event schema plugin

**Comment by amer07** [comment]
Case 2:https://secure.helpscout.net/conversation/1115208364/117790?folderId=2770543
