### ISSUE TITLE
Want to display reviews from "WP Customer Reviews"

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#888]
Want to display reviews from "WP Customer Reviews" in the website 

Ref:https://secure.helpscout.net/conversation/1096055712/113754?folderId=3575684

**Comment by HLBabu** [comment]
Hi Team,

Need your urgent help on this pending issue.

We directly collect customer Rating and Reviews for large number of Doctors listed in our website through [WP-Customer Review plugin 
](https://wordpress.org/plugins/wp-customer-reviews/)

We are using Schema and Structured Date plugin for markup. 

We have enabled  Add Schema Type (Local Business)--> Modify Schema Output -->Automatic and given all required fields. 

We are facing issue with Aggregate Rating field (Rating and Number of Reviews). We are want to fectch wpcr3_review_ratingValue and wpcr3_aggregateRating_reviewCount values here automatically and put in markup.

We are trying this past 2 months but no success. 

Kindly guide us how to configure rightly or should we change any code?

Really appreciate your support. It's very urgent for us please.

**Comment by Sanjeevsetu** [comment]
Hi @HLBabu. 

We are working on it and it will come in current milestone 1.9.33. Please wait for few more days.

Thanks

**Comment by Sanjeevsetu** [comment]
Hi @HLBabu. 

We have added its compatibility. Please check it.
