### ISSUE TITLE
Load script(function-list.min.js) on required pages only.

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#889]
https://secure.helpscout.net/conversation/1116505468/118096?folderId=1060556

The user is unable to activate the SASWP extension manager license key. Getting the error attached in the screenshot 
![12](https://user-images.githubusercontent.com/23516562/77320537-c476c100-6d36-11ea-858f-938478ead0e9.PNG)

**Comment by Sanjeevsetu** [comment]
we already loading script based on conditions...

**Comment by Sanjeevsetu** [comment]
User issue was due to another conflict which has been solved
