### ISSUE TITLE
Category selection is not working correct in placement

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#890]
Use case:

When the schema placement is set as a post category1 and post category2,

Then select the same categories for the post, category1, and category2 

based on the condition the setup schema is not getting generated on the post.

Refer this video for more info, please:

For example, I have set a news article schema type:
https://monosnap.com/file/Fi40KZuRlKmE831lrmqdkV5qG04p4V

The use case  for the user is:

When movie review  category is selected along with any category review schema should get generated

Ref:https://secure.helpscout.net/conversation/1102039293/115254?folderId=2632030

**Comment by Psykonevro** [comment]
I believe the issue could be solved by adding a new option, either select "only" a category or "include" the selected category.

This is indeed an issue for those of us who put several categories to a single post.
