### ISSUE TITLE
Need to add the properties "event AttendanceMode" and "event Status"

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#891]
Need to add the properties "event AttendanceMode" and "event Status" in the Event schema type 

ref:https://secure.helpscout.net/conversation/1118705480/118569?folderId=3575684

**Comment by ahmedkaludi** [comment]
add support in 

- [ ] core

- [ ] event schema plugin

**Comment by amer07** [comment]
Case:2 https://secure.helpscout.net/conversation/1115208364/117790?folderId=2770543
