### ISSUE TITLE
Need to add an placement option for generting schema as per the post date published

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#895]
The use case for it is:

There are certain fields that are in mandatory in Review Schema like Movie Name, Director, rating value, etc. So we have made backend changes and created database fields for these so that they can be mapped using your schema plugin. So any new pages that we newly create will have these database fields populated, however all the old review pages will not have these database fields. This will cause all the old review pages to go on errors in google schema validation. We are using custom schemas on our old pages so we would not want to apply Review schema for old pages.

Ref: https://secure.helpscout.net/conversation/1119030083/118616?folderId=2632030

**Comment by TB7722** [comment]
When do you plan to implement this. As of now we are not able to enable Review schema since we do not have this placement option

**Comment by TB7722** [comment]
Do you have any update for us.
