### ISSUE TITLE
Conflict with wp-travel plugin.(last update)

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/schema-and-structured-data-for-wp#901]
Case 1: https://secure.helpscout.net/conversation/1119173698/118660?folderId=2770543

Conflicting with the wp-travel plugin. (last update).

Please see these screenshots:

This is how it looks now:

https://www.dropbox.com/s/qs5yxcos3qe7esa/1-affected.png?dl=0

This is how it should look:
https://www.dropbox.com/s/zv65bmhu4iae6xm/2-not%20affected.png?dl=0

**Comment by Sanjeevsetu** [comment]
This conflict is due to WP Travel plugin. They are not using prefix to some of their classes and overriding WordPress default css.

Ref : https://wordpress.org/support/topic/prefix-is-misssing-in-class-name/
