### ISSUE TITLE
RecipeInstruction are not fetching from the total recipe generator plugin

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#905]
RecipeInstruction is not fetching from the total recipe generator plugin, Compatibility issue.

The Recipe Instructions are present on the page but they are not rendering in the schema markup.

https://comohacersalsa.com/bechamel/brocoli-con-bechamel/amp/

Due to this warning appears in the schema and structure data tool.

1.Ref:  https://monosnap.com/file/r7X0PHanpX21lCMQaL0TmzBSIUxwfW

https://secure.helpscout.net/conversation/1059875910/107297?folderId=2632030

**Comment by Sanjeevsetu** [comment]
this issue has been fixed in its pro version as it was related to that
