### ISSUE TITLE
Need to add feature to fetch new reviews

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#907]
Ref: https://secure.helpscout.net/conversation/1120659306/118976?folderId=2770545

We don't have currently feature to fetch the new reviews. When we fetch new reviews it does not fetch it and fetches the old as it is.

**Comment by amer07** [comment]
one more user.
https://secure.helpscout.net/conversation/1111979616/117194?folderId=2770543
