### ISSUE TITLE
Error in Schema Markup when Person data type is selected in Knowledge Graph. 

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/schema-and-structured-data-for-wp#914]
https://secure.helpscout.net/conversation/1122607093/119447?folderId=3243584

1. Logo URL error. 
2. Publisher name error.

**Comment by Sanjeevsetu** [comment]
this is not a valid issue. Actually user has not filled organization name in either schema or wordpress general settings
