### ISSUE TITLE
Fatal Error with FAQ block

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/schema-and-structured-data-for-wp#931]
child 51 said into stderr: "NOTICE: PHP message: /FaqBlockChild/FaqBlockChild.php:85 get_advanced_fields_config()

https://wordpress.org/support/topic/few-functions-many-error-2/

**Comment by mahnunchik** [comment]
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/780
