### ISSUE TITLE
Gutenberg comments are not being stripped from article content

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/schema-and-structured-data-for-wp#949]
Article” type not stripping out things like 

Reference: https://wordpress.org/support/topic/how-to-remove-comments-from-json-data/

**Comment by thanhphu** [comment]
Hello, thanks for checking this out.

I tried to remove the comments by doing a regular expression search like the following in function.php, line 347

```
                    // Strip out gutenberg comments from mainEntityOfPage
                    $gutenberg_comments_pattern = '/<!--\s+(\/)?wp:[a-z\-]+(\s+(\{.*?\}))?\s+-->/';
                    $no_comments_webpage = preg_replace($gutenberg_comments_pattern, "", $webpage['@id']);

                    $output['mainEntityOfPage'] = $no_comments_webpage;
```

I tested the code elsewhere and it seemed to work, but not with the plugin. can you prove some sample output of `$webpage['@id']` or provide some pointers? :)
