### ISSUE TITLE
Admin scripts enqueued on all screens

### ISSUE THREAD

**Issue by ajaydsouza** [ahmedkaludi/schema-and-structured-data-for-wp#950]
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/blob/645d3544a8a8fc2e53426b264937e44dbf7fe523/admin_section/settings.php#L2821

It looks like there are no checks are made to see if this in the plugin's settings page and so is loaded across the entire admin area.

Result is that it interferes with other plugins admin screens.

**Comment by MohammedKaludi** [comment]
Hi @ajaydsouza 

Thank you for the creating the ticket, will look into and if the issue is valid the we will fix it and push it in next update.
