### ISSUE TITLE
when seo plugins are activate take keywords from there in keyword section

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#951]
when seo plugins are activate take keywords from there in keyword section
the user is using: Rankmath plugin for Seo
Ref: https://secure.helpscout.net/conversation/1133414698/0/?folderId=3257665

**Comment by Sanjeevsetu** [comment]
Waiting for user's reply.

**Comment by Sanjeevsetu** [comment]
Since, User is not reply from long time so I am closing this ticket
