### ISSUE TITLE
"Unspecified" schema type is loading in the wp recipe maker schema setup

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#954]
Ref: https://secure.helpscout.net/conversation/1142243637/124123/

Screenshot: https://prnt.sc/s3qqt4

URL: https://www.viaggi-usa.it/ricetta-brownies/

Schema test: https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.viaggi-usa.it%2Fricetta-brownies%2F

**Comment by Sanjeevsetu** [comment]
this issue is due to recipe schema (Pro extension) so it has been fixed in that extension.
