### ISSUE TITLE
Author archive page has PHP errors

### ISSUE THREAD

**Issue by jonathanstegall** [ahmedkaludi/schema-and-structured-data-for-wp#955]
When loading an archive for an individual author, I see the following PHP errors:

```
[22-Apr-2020 18:03:17 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 989
[22-Apr-2020 18:03:17 UTC] PHP Notice:  Trying to get property 'display_name' of non-object in /wp-content/plugins/schema-and-structured-data-for-wp/admin_section/structure_admin.php on line 992
```

This appears to be because you are calling `global $author` but `$author` is not a global variable in WordPress. There is a `global $authordata` if that is what is supposed to be loaded?

**Comment by Sanjeevsetu** [comment]
It is there in current author. You will get an id of that author by using global $author However to remove notice I have added if condition there.

**Comment by jonathanstegall** [comment]
No, I mean there is no `global $author`, at least not in WordPress core. Here's a [list](https://developer.wordpress.org/apis/handbook/global-variables/) of global variables in WordPress. `$authordata` is probably what you should be loading instead.

**Comment by Sanjeevsetu** [comment]
Yes, I got what you are saying. there is no global $author in core however when I define it I get author id in the variable $author. But may be at your end its not getting id of author. 

global $authordata, as its known. I am going to use it here.

Thank you for the help
