### ISSUE TITLE
Howto schema

### ISSUE THREAD

**Issue by gionthelawa** [ahmedkaludi/schema-and-structured-data-for-wp#958]
It works properly. Nice job man. 
First of all, it would be greater if it is compatible with this plugin https://wordpress.org/plugins/ultimate-blocks/ it has Howto block.
But here is the one issue with the Howto values in your project. Image URLs goes into the text of the itemListElement, with the Alt text. You should check here https://search.google.com/structured-data/testing-tool

Look at this screen also. 
https://ibb.co/QMTyPHk

**Comment by Sanjeevsetu** [comment]
I have removed image from text and for compatibility with Ultimate blocks, I have created a separate ticket for it and we will make it. https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/963

**Comment by gionthelawa** [comment]
I found one more issue, probably I don't know if it is exactly right. In the Website schema with the **potentialAction** markup, (**@type | SearchAction**) perhaps this is the problem, _https://www.example.com/?s={search_term_string}_ because of the search string of my **WP** website is such a _https://www.example.com/?s=search_term_string_ this string. Devs should check the validity of this strings.
