### ISSUE TITLE
Aggregate rating of attorney are not updating when Added manually or automatically.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#969]
Please check the below video to understand the issue in detail:

https://www.dropbox.com/s/a4yulh0msqcjvuh/Attorney%20Aggregate%20Rating%20Issue.mp4?dl=0

Ref ticket:
https://secure.helpscout.net/conversation/1137063680/0/?folderId=3126461

**Comment by Sanjeevsetu** [comment]
Issue is not being created on localhost. Waiting for users reply.

**Comment by Sanjeevsetu** [comment]
still waiting for user reply

**Comment by Sanjeevsetu** [comment]
I have personally written to user and waiting for his reply again
