### ISSUE TITLE
Errormessage "Sorry, you do not have permission to access this page"

### ISSUE THREAD

**Issue by HispanicLA** [ahmedkaludi/schema-and-structured-data-for-wp#977]
I am installing Schema & Structured Data for WP & AMP in Wordpress 5.4, to work with the official AMP plugin 1.5.3 and Yoast SEO premium 14.0.4. While setting the plugin with the Wizard I get the above mentioned error message "Sorry, you do not have permission to access this page". Now the same error message appears with the regular Setting. I didn't find references to this yet. Site is hispanicla.com . Many thanks. G

**Comment by ahmedkaludi** [comment]
Thats really strange, can you share a screenshot or something?

also try to disable all the plugins and see if that fixes it

**Comment by HispanicLA** [comment]
I disabled all the plugins and still got the error message while going to
the regular "Settings".
And "Settings Wizard" I went again through all the personalization because
it did not retain the previous settings. Then, at the end of the process if
I click on "Let's go" again the error message. If I click on "return to
dashboard" it takes me, to the dashboard. See:
Setup Done. Have fun!

Basic Setup has been done. Navigate to plugin options panel to access all
the options.
Let's Go
<https://mailtrack.io/trace/link/a150e0b3c846c26bfbcd583eb9db851d5ccc4689?url=https%3A%2F%2Fhispanicla.com%2Fwp-admin%2Fedit.php%3Fpost_type%3Dsaswp%26page%3Dstructured_data_options&userId=4682497&signature=b891aa782812c6cc>

   -
   -
   -


   1.
   <https://mailtrack.io/trace/link/7a4720914796496562febf27a4c669f76701732f?url=https%3A%2F%2Fhispanicla.com%2Fwp-admin%2Fplugins.php%3Fpage%3Dsaswp-setup-wizard%26_saswp_nonce%3D429313e1de%26step%3D1&userId=4682497&signature=3a1fd607cad1c0de>

   2.
   <https://mailtrack.io/trace/link/7eb403ca0e0fb009ad23a2773852c5fd8df27ecd?url=https%3A%2F%2Fhispanicla.com%2Fwp-admin%2Fplugins.php%3Fpage%3Dsaswp-setup-wizard%26_saswp_nonce%3D429313e1de%26step%3D2&userId=4682497&signature=27a21a2d86131ac0>

   3.
   <https://mailtrack.io/trace/link/a26f0d0579199d896b25af5cdf87b179cba3d2d7?url=https%3A%2F%2Fhispanicla.com%2Fwp-admin%2Fplugins.php%3Fpage%3Dsaswp-setup-wizard%26_saswp_nonce%3D429313e1de%26step%3D3&userId=4682497&signature=fc9e61b85dd2e654>

   4.
   <https://mailtrack.io/trace/link/ab950e3f64b36cc6d0edf3d4ba010bafa421c517?url=https%3A%2F%2Fhispanicla.com%2Fwp-admin%2Fplugins.php%3Fpage%3Dsaswp-setup-wizard%26_saswp_nonce%3D429313e1de%26step%3D4&userId=4682497&signature=d36606dde6827c3f>

Return to dashboard
<https://mailtrack.io/trace/link/fe854ea5f622c4aa8ebfb0207d5ccd0e2bd6488d?url=https%3A%2F%2Fhispanicla.com%2Fwp-admin%2Fadmin.php%3Fpage%3Dstructured_data_options&userId=4682497&signature=10b249f264be8ba1>

**Comment by ahmedkaludi** [comment]
Github is for tried and tested bugs, this issue seems a strange one, please contact our technical team for this: https://structured-data-for-wp.com/contact-us/
