### ISSUE TITLE
Need to implement feature to import the "FAQ" markup of the "FAQ Schema Markup – FAQ Structured Data" plugin

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#981]
Ref: https://wordpress.org/plugins/faq-schema-markup-faq-structured-data/

**Comment by udiudiudiudi** [comment]
hello, any update on this?

**Comment by udiudiudiudi** [comment]
this plugin is basically implemented schema ld inside desktop pages, and it would be nice if your plugin implements integration support to it, so these FAQ questions/answer will show on the amp pages as well

**Comment by udiudiudiudi** [comment]
Hello,
How do i import the schema markup acceptedanswers to your plugin?

**Comment by Sanjeevsetu** [comment]
just go to advanced tab in settings tab and there is migration section below

**Comment by udiudiudiudi** [comment]
i think you have a bug

When I try to save the checkbox of FAQ Schema Markup in the compatibility menu,
It is not saved

**Comment by Sanjeevsetu** [comment]
clear the cache and try it again with hard refresh because at our end it is working fine or inspect and see in console is there any js error

**Comment by udiudiudiudi** [comment]
It is not the cache, since i disabled it
You have a BUG 100%
because the checkbox of yoast and and ampforwp is checkboxed
but when i checkbox  FAQ Shema markup and save
it tells me its saved
but when i enter compatibility again, its not checkboxed.
