### ISSUE TITLE
Post format placement is not working fine.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#986]
The user is placing 'post format' placement on 'Video' in Video object-schema type but it is not placing correctly.

Ref Ticket: 
https://secure.helpscout.net/conversation/1144530907/124560?folderId=3126461

**Comment by Sanjeevsetu** [comment]
I tested this issue on locahost and at user end as well and found that user was doing some wrong in setting up schema. The issue is not valid so I am closing it.

**Comment by ahmedkaludi** [comment]
let's discuss before closing
