### ISSUE TITLE
User experiece issues, in Fetching the reviews

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#994]
- [ ] Unable to fetch the updated reviews.

- [ ] In some cases, while fetching the update reviews the previous old review will also get fetched.
and the count gets reduce even for the duplicate review which is fetched already.

https://www.trustpilot.com/review/www.wecleanhands.co.za

https://www.wecleanhands.co.za/

https://secure.helpscout.net/conversation/1151416685/126149?folderId=2632030

**Comment by akashagrjsr** [comment]
One more user is facing the duplicate review issue
Ref: https://secure.helpscout.net/conversation/1165175267/129873?folderId=2770545

**Comment by TMsravan** [comment]
One more user with the duplicate reviews issue.
https://secure.helpscout.net/conversation/1171609403/131109?folderId=2632030

**Comment by Sanjeevsetu** [comment]
The  code related to this issue has been pushed on private server
