### ISSUE TITLE
Compatibility Issue with Yoast 14.0.x

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/schema-and-structured-data-for-wp#999]
Reference: https://wordpress.org/support/topic/compatibility-issue-with-yoast-14-0-x/

**Comment by Sanjeevsetu** [comment]
This issue is not being recreated. I tested with yoast 14.XX all latest version. I think the issue is no more exists. May be Yoast, itself has some conflict with other plugins which has been fixed by them.
